### ISSUE TITLE
possible for less restrictive install_requires?

### ISSUE THREAD

**Issue by gdub** [seleniumbase/SeleniumBase#1063]
I notice that `install_requires` in `setup.py` currently pins many dependencies to single versions, which has caused some pain with dependency conflicts when upgrading packages in a project that also uses seleniumbase. Would it be possible to specify compatible versions ranges (e.g. `>=x.y.z`) to be less restrictive?

https://packaging.python.org/discussions/install-requires-vs-requirements/
> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

**Comment by mdmintz** [comment]
@gdub Was there a specific dependency that you wanted more flexibility with? One of the secrets to why there are so few bugs with SeleniumBase is the hard pins on many dependencies, which makes testing a lot easier because otherwise there would be millions of combinations to test SeleniumBase on different dependencies. Several times there have been changes to dependencies that would've broken SeleniumBase if not for the pins. In nearly every case we try to use the latest version of a dependency when possible. Currently the only dependency that isn't at the latest version is ``pytest-html`` (it's set to ``2.0.1`` instead of ``3.1.1``, which broke things). For many dependencies, you'll see that there is no hard pin. Eg: ``pip>=21.3.1``, ``packaging>=21.2`` , ``setuptools>=58.5.3``, etc, where there is only a minimum version set, and no max version. These are the "trusted" dependencies that have never broken SeleniumBase when a new version of those dependencies became available.

**Comment by gdub** [comment]
@mdmintz Right, I figured testing/maintainability was the motivation for the pins, and respect that choice.

From perspective of a user, I pin requirements for production stability and typically make minimal dependency updates aside from periodic updating of all/most dependencies (depending on compatibility). As a user of SeleniumBase, I incur the trade-off of reduced flexibility in the package sets I can run with. A dependency version upgrade can break my own code just as it can break SeleniumBase, and with so many exact pins, SeleniumBase is effectively dictating the packages I can run rather than allowing me more of that control.

In my particular case that spurred this ticket, I hit an issue when adding the `streamlit` package to an existing project using pip-tools and a pinned requirement to `seleniumbase==1.63.23`. `streamlit==1.1.0` pulled in new package `pydeck==0.7.1`, which pulled in new package `ipykernel==6.5.0`, which required `traitlets<6.0,>=5.1.0`; however, `seleniumbase==1.63.23` required `traitlets==5.0.5`.
```
Could not find a version that matches traitlets<6.0,==5.0.5,>=4.2,>=4.3.1,>=4.3.2,>=5.1.0 (from pydeck==0.7.1->streamlit==1.1.0->-r requirements.in (line 24))
Tried: 0.0.1, 0.0.2, 4.0.0, 4.0.0, 4.1.0, 4.1.0, 4.1.0, 4.2.0, 4.2.0, 4.2.0, 4.2.1, 4.2.1, 4.2.1, 4.2.2, 4.2.2, 4.2.2, 4.3.0, 4.3.0, 4.3.1, 4.3.1, 4.3.2, 4.3.2, 4.3.3, 4.3.3, 5.0.0, 5.0.0, 5.0.1, 5.0.2, 5.0.2, 5.0.3, 5.0.3, 5.0.4, 5.0.4, 5.0.5, 5.0.5, 5.1.0, 5.1.0, 5.1.1, 5.1.1
Skipped pre-versions: 4.0.0.dev0, 4.0.0.dev0, 4.0.0.dev0, 4.1.0b1, 4.1.0b1, 4.1.0b1, 4.1.0b1, 4.1.0b1, 4.3.0b1, 4.3.0b1, 4.3.3.dev0, 4.3.3.dev0, 5.0.0b1, 5.0.0b1, 5.0.0rc2, 5.0.0rc2
There are incompatible versions in the resolved dependencies:
  traitlets>=4.3.2 (from pydeck==0.7.1->streamlit==1.1.0->-r requirements.in (line 24))
  traitlets>=4.2 (from ipython==7.26.0->seleniumbase==1.63.23->pytest-seleniumbase==1.63.23->-r requirements.in (line 21))
  traitlets==5.0.5 (from seleniumbase==1.63.23->pytest-seleniumbase==1.63.23->-r requirements.in (line 21))
  traitlets<6.0,>=5.1.0 (from ipykernel==6.5.0->pydeck==0.7.1->streamlit==1.1.0->-r requirements.in (line 24))                                                                                                             
  traitlets (from matplotlib-inline==0.1.2->seleniumbase==1.63.23->pytest-seleniumbase==1.63.23->-r requirements.in (line 21))                                                                                             
  traitlets>=4.3.1 (from ipywidgets==7.6.5->pydeck==0.7.1->streamlit==1.1.0->-r requirements.in (line 24)) 
```

OK, so then if I upgrade `pytest-seleniumbase` and `seleniumbase` to attempt to resolve the above conflict, but get another conflict:
```
Could not find a version that matches pluggy<1.0.0a1,==1.0.0,>=0.12 (from seleniumbase==2.1.4)
Tried: 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.4.0, 0.4.0, 0.5.0, 0.5.1, 0.5.1, 0.5.2, 0.5.2, 0.6.0, 0.6.0, 0.7.1, 0.7.1, 0.8.0, 0.8.0, 0.8.1, 0.8.1, 0.9.0, 0.9.0, 0.10.0, 0.10.0, 0.11.0, 0.11.0, 0.12.0, 0.12.0, 0.13.0, 0.13.0, 0.13.1, 0.13.1, 1.0.0, 1.0.0
Skipped pre-versions: 1.0.0.dev0, 1.0.0.dev0
There are incompatible versions in the resolved dependencies:
  pluggy==1.0.0 (from seleniumbase==2.1.4)
  pluggy<1.0.0a1,>=0.12 (from pytest==6.2.4->-r requirements.in (line 16))
```

So then tried updating `pytest` as well, and successfully got no more dependency errors.

**Comment by mdmintz** [comment]
I'll loosen the requirements on ``traitlets`` in the next version of SeleniumBase (``2.1.6``) so that there's only a minimum version set. As for ``pluggy``, that should be synced with the ``pytest`` version, so I'll have to keep that one pinned, but it is currently at the latest version.

Here's what things will look like after I push the next release for the NON-Pinned dependencies when using at least Python 3.7 or newer:
(Note the ``traitlets>=5.1.1;python_version>="3.7"``)

```
pip>=20.3.4;python_version<"3.6"
pip>=21.3.1;python_version>="3.6"
packaging>=20.9;python_version<"3.6"
packaging>=21.2;python_version>="3.6"
typing-extensions>=3.10.0.2
setuptools>=44.1.1;python_version<"3.5"
setuptools>=50.3.2;python_version>="3.5" and python_version<"3.6"
setuptools>=58.5.3;python_version>="3.6"
setuptools-scm==5.0.2;python_version<"3.6"
setuptools-scm>=6.3.2;python_version>="3.6"
tomli>=1.2.2;python_version>="3.6"
wheel>=0.37.0
attrs>=21.2.0
PyYAML>=6.0;python_version>="3.6"
traitlets==4.3.3;python_version<"3.7"
traitlets>=5.1.1;python_version>="3.7"
certifi>=2021.10.8
```

I'll be shipping this change to ``traitlets`` with the next release (``2.1.6``), which should be out in the next 2 hours.

**Comment by mdmintz** [comment]
@gdub That change to ``traitlets`` (setting only a minimum bound) was made in https://github.com/seleniumbase/SeleniumBase/releases/tag/2.1.6

**Comment by QuLogic** [comment]
The version requirements in `install_requires` should not be so strict. [See the second last paragraph of this section from PyPA.](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#install-requires)

I realize this pinning is used to make SeleniumBase _as an application_ stable (though personally, I don't think it's useful for that either), but this makes using SeleniumBase with other Python libraries extremely difficult. Perhaps the default requirements could be expanded and these extremely-specific pins could be put in an extra, or pipenv/poetry.

**Comment by mdmintz** [comment]
Hi @QuLogic, there are many dependencies that aren't pinned:

```bash
pip>=20.3.4;python_version<"3.6"
pip>=21.3.1;python_version>="3.6"
packaging>=20.9;python_version<"3.6"
packaging>=21.3;python_version>="3.6"
setuptools>=44.1.1;python_version<"3.5"
setuptools>=50.3.2;python_version>="3.5" and python_version<"3.6"
setuptools>=59.6.0;python_version>="3.6" and python_version<"3.7"
setuptools>=60.3.1;python_version>="3.7"
setuptools-scm>=5.0.2;python_version<"3.6"
setuptools-scm>=6.3.2;python_version>="3.6"
tomli>=1.2.2;python_version>="3.6" and python_version<"3.7"
tomli>=2.0.0;python_version>="3.7"
wheel>=0.37.1
attrs>=21.4.0
PyYAML>=6.0;python_version>="3.6"
traitlets>=4.3.3;python_version<"3.7"
traitlets>=5.1.1;python_version>="3.7"
certifi>=2021.10.8
```

For the ones that are pinned, they caused trouble at least once when they were pinned. Is there a specific dependency that you want eased restrictions on? Being string on dependencies like this has virtually eliminated all bugs. And generally, SeleniumBase is installed into its own virtual environment on machines that have more than one Python project. Alternatively, cloning the repo and making changes to dependencies might solve your issue, but it might cause other unintended side effects.

**Comment by QuLogic** [comment]
All of those unpinned dependencies are not imported by SeleniumBase and should not even be included in `install_requires` in the first place. Some of them (e.g., `setuptools`) are build-time requirements and can be put in `pyproject.toml`. Some are transitive (like `certifi`) and shouldn't be specified anywhere.

> For the ones that are pinned, they caused trouble at least once when they were pinned. Is there a specific dependency that you want eased restrictions on? Being string on dependencies like this has virtually eliminated all bugs. And generally, SeleniumBase is installed into its own virtual environment on machines that have more than one Python project. Alternatively, cloning the repo and making changes to dependencies might solve your issue, but it might cause other unintended side effects.

Sorry, I don't have specifics, I'd prefer all of them unpinned. This is a disconnect between running SeleniumBase as an application and as a library. While working on a Python project, I need to be able to install SeleniumBase in the same virtual environment as my project because I'm running pytest on it, and SeleniumBase is simply one of many tests. If every library I depended on pinned every library they depended on to some specific version, I'd never be able to produce an environment that worked.

Perhaps SeleniumBase is too heavy for what I need. I only need pytest integration (though the recorder is nice), and none of the framework around it as a testing application (which necessitates all the pinning.)

**Comment by mdmintz** [comment]
@QuLogic  I agree that it would be great if I didn't have to pin dependencies like that, but due to so many bugs in earlier versions of other dependencies, I couldn't keep SeleniumBase bug-free unless I pinned dependencies like I do. And SeleniumBase isn't just a library to import... it's a complete framework. I do my best to keep the dependencies up-to-date, and with frequent releases to stay on track. You mentioned that you "only need pytest integration", "and none of the framework around it as a testing application"... how does that work? pytest to run scripts without any testing? The more I know about your situation, the better I can try shaping SeleniumBase to work better for you and everyone else.

**Comment by mdmintz** [comment]
Many required dependencies were removed today: https://github.com/seleniumbase/SeleniumBase/commit/bc6b0cf472b29b110cc6a14943871474fd6504e9
