### ISSUE TITLE
The default assert method can not work well in seleniumBase

### ISSUE THREAD

**Issue by miaodahua** [seleniumbase/SeleniumBase#107]
Hi, Selenium base is, however, the most powerful framework for automation in python+selenium, but while I'm trying to add assertion in it, it does not work as well.

While I run below command:
self.check_assert_text(u'1783元','#ddxx_ul'), the expected text is '1784元', and execution completed with "Pass", that is unexpected.
In case the text I provided in assertion include Chinese character, is it possible the reason which blocked the assertion?
Please don't be hesitate to tell me if it is a real issue or just a user error.

Thanks a lot!
![Uploading assertion does not work.png…]()
![page info](https://user-images.githubusercontent.com/28770672/28297971-473332ec-6ba3-11e7-89a1-7d01a70ddef6.png)

**Comment by surevs** [comment]
could you please print the extracted text in console and check,

**Comment by mdmintz** [comment]
Hi @miaodahua. The default asserts in SeleniumBase are self.assert_text() and self.assert_element(). However, the self.check_assert_text() and and self.check_assert_element() are special methods that were build to handle the case of doing multiple assertions on the same page in-a-row without failing the test immediately until all assertions have been completed. At the end of your check_assert methods, you need to call self.process_checks() which will then run all the assertions at once and fail the test if any have passed. (See https://github.com/seleniumbase/SeleniumBase/blob/68c6ff9013a7ab422f63d6a8ddb269d6df863ec3/seleniumbase/fixtures/base_case.py#L1172)

This feature was built to save time during testing. If a web page being tested had multiple failures, then rather than failing the test right away on the first failure (and then having to make a fix before continuing through the rest of the test) now, instead, the test would report all the failures together, once self.process_checks() was called.

In many cases, you might want the test to fail immediately after the first failed assertion, in which case you should use self.assert_text() and self.assert_element() instead. But if you use the "check_assert_" methods, you must use self.process_checks() or else the test will not fail. Does this help?

**Comment by miaodahua** [comment]
@mdmintz Thanks a lot! That works for either assert_text() and check_assert_text() with process_checks() now!
@ktp420 Thanks for your time, too.

So I'll close this issue as a user error.

**Comment by mdmintz** [comment]
@miaodahua, the latest version of SeleniumBase (https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.3.26) will now call self.process_checks() in the tearDown() phase after the test if there are uncalled exceptions from self.check_assert_element() and self.check_assert_text(), assuming that the end of the test is reached without any other exceptions getting raised.

**Comment by Sonics2009** [comment]
Hi @mdmintz, I'm also the user of SeleniumBase, thanks for the kindly handling of process_checks().
Meanwhile, I'm also trying to promote this framework to my mates in China, on social media. You did a greate job, thank you.
