### ISSUE TITLE
get_link_status_codeprovides misleading results

### ISSUE THREAD

**Issue by grahamhar** [seleniumbase/SeleniumBase#1105]
I was using get_link_status_code to aide in some debugging of a test. The response was 404, when in fact the link being checked was failing with a connection failed.

I'm not sure if this is by design or not. Should this either be documented so people don't get caught out or should it actually return the Exception raised?

I'm happy to pull a PR together based on the answer.

**Comment by mdmintz** [comment]
@grahamhar If it helps:

```python
"""Get the status code of a link.
    If the timeout is exceeded, will return a 404.
    For a list of available status codes, see:
    https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
    """
    status_code = None
    try:
        response = requests.get(
            link, allow_redirects=allow_redirects, timeout=timeout
        )
        status_code = response.status_code
    except Exception:
        status_code = 404
    return status_code
```

So yes, by design it returns a 404 when there's an exception in getting the status code, which simplifies things in my opinion. If you're picky about that, you could just use:
``status_code = requests.get(link).status_code``, and wrap any exception-handling that you want.

 ``self.get_link_status_code(link)`` is a part of the loop for ``self.assert_no_broken_links()``, and whether or not the link is a 404 or doesn't return on time, it's still considered "broken". The timeout can be changed to wait longer if needed.
 
 ```
 def get_link_status_code(self, link, allow_redirects=False, timeout=5):
        """Get the status code of a link.
        If the timeout is set to less than 1, it becomes 1.
        If the timeout is exceeded by requests.get(), it will return a 404.
        For a list of available status codes, see:
        https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
        """
```

**Comment by grahamhar** [comment]
I guess I'm think from a rest point of view where a 404 is a perfectly valid response. I  did find the code after I opened the issue and if that behaviour is part of the design of the library I think it should be documented.

**Comment by mdmintz** [comment]
@grahamhar It's in the docstring comments for BaseCase methods. There's method summaries here: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md (but that's just the method names and args). For some code editors that autocomplete method names, there's an option to include docstrings.
