### ISSUE TITLE
install in python3

### ISSUE THREAD

**Issue by cjydayang** [seleniumbase/SeleniumBase#111]
Hi @mdmintz 
Thank you for sharing the Framework, I'm very interested in it, but I encounter some problems when I try to install:

1.The program need python2.7 to run, but my environment is python3,
so BeautifulSoup module cannot be installed successfully（this module seems to be "bs4" in the python), I don't know how to custom the installation environment and how to run it normally.

2.Have you ever considered to encapsulate a function to operate Yaml file，i think it‘s useful to manage testcase

Thanks

**Comment by Sonics2009** [comment]
@cjydayang guessing we are in the same situation while try to organize test cases. That will benifit us a lot if we don't want to use hard code in cases and which can also help us to reuse sources such as cookies, in case we have Yaml file or any kind of property files.

**Comment by mdmintz** [comment]
Hi @cjydayang and @Sonics2009, the latest version of SeleniumBase now uses BeautifulSoup4 and fully supports Python 3. Now at Version 1.4.0 . The settings.py file (https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/config/settings.py) is what there is now to make big configurations for your test environment. I'd try looking there first. Otherwise, the only major YAML file in SeleniumBase is https://github.com/seleniumbase/SeleniumBase/blob/master/.travis.yml , which is used to make sure the build is passing. You might be able to create your own version of that.

As for this ticket, since it's about Python 3, I'll close it if SeleniumBase works fine for you on Python 3. For other issues, create a separate ticket. Thanks!

**Comment by cjydayang** [comment]
@mdmintz Version 1.4.0 work fine on python3!!! Thanks for your work. I feel so excited when i found the project and i would like to do something for this project, but i am a beginner in python and selenium，so maybe cannot create my own branch to develop.Hope soon will and if i have any other problems，i will create issue for the project.Thanks again!

**Comment by cjydayang** [comment]
@Sonics2009 i found a framework：https://github.com/Louis-me/selenium 
i think the method to manage test cases is very useful,you can try it If you are interested。

**Comment by mdmintz** [comment]
@cjydayang Great to hear that it works for you now! I'm closing out this issue as resolved. SeleniumBase is now at version 1.4.1.
