### ISSUE TITLE
RFE: switch from `boto` to `boto3` in test suite

### ISSUE THREAD

**Issue by kloczek** [seleniumbase/SeleniumBase#1134]
Looks like `boto` is no longer mainained and and it is not even well updated to python 3.x because `boto` test suite is still usinng nose which should not not  be used with python 3.x.
https://nose.readthedocs.io/en/latest/

**Comment by mdmintz** [comment]
@kloczek From that website: “nose itself supports python 3”. Do you have any stack traces to show for any of the issues that you’ve had with boto or nose? I’ll need to see the stack traces for both of those, specifically with SeleniumBase examples that I can verify. They might not be maintained anymore, but that doesn’t mean they no longer work. The SeleniumBase CI tests use both nose and pytest, without issue. As for boto, that is specifically for uploading log files to S3 from the SeleniumBase integration. I’ll need to see a stack trace of that failing for you when configured properly.

**Comment by kloczek** [comment]
That issue is not straight related to SeleniumBase.
As `nose` code is no longer maintained and its test suite do not passes on top of python 3.x .. simple it affects `boto` testing. `boto3` test suite already has been fully migrated to `pytest`.

**Comment by mdmintz** [comment]
@kloczek, I have maintained ``nosetests`` compatibility with SeleniumBase. It works on Python 3, and things would break for customers if I removed it now. Here's an example of ``nosetests`` working with Python 3 for a SeleniumBase test:

```bash
nosetests test_mfa_login.py -v
test_mfa_login (examples.test_mfa_login.TestMFALogin) ... ok

----------------------------------------------------------------------
Ran 1 test in 6.433s

OK
```

If your issue is not related to SeleniumBase, then there is no issue. Please show me stack traces for specific SeleniumBase issues where you have your problems.

**Comment by kloczek** [comment]
IMO it is waste of effort ..
Better would be use https://github.com/schollii/nose2pytest/ and migrate to `pytest`.

**Comment by mdmintz** [comment]
@kloczek In SeleniumBase, the tests are exactly the same for both test runners. The only difference is the run command to start the test. Example below, where ``nosetests`` (2nd) ran faster than ``pytest`` (1st):

```bash
pytest test_mfa_login.py -v
============================== test session starts ===============================
platform darwin -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/michael/.virtualenvs/sbase9/bin/python
metadata: {'Python': '3.9.2', 'Platform': 'macOS-10.14.6-x86_64-i386-64bit', 'Packages': {'pytest': '6.2.5', 'py': '1.11.0', 'pluggy': '1.0.0'}, 'Plugins': {'html': '2.0.1', 'xdist': '2.5.0', 'forked': '1.4.0', 'rerunfailures': '10.2', 'metadata': '1.11.0', 'ordering': '0.6', 'cov': '3.0.0', 'seleniumbase': '2.3.0'}}
rootdir: /Users/michael/github/SeleniumBase/examples, configfile: pytest.ini
plugins: html-2.0.1, xdist-2.5.0, forked-1.4.0, rerunfailures-10.2, metadata-1.11.0, ordering-0.6, cov-3.0.0, seleniumbase-2.3.0
collected 1 item                                                                 

test_mfa_login.py::TestMFALogin::test_mfa_login PASSED

=============================== 1 passed in 8.70s ================================

nosetests test_mfa_login.py -v
test_mfa_login (examples.test_mfa_login.TestMFALogin) ... ok

----------------------------------------------------------------------
Ran 1 test in 6.590s

OK
```

**Comment by mdmintz** [comment]
Same test again with ``pytest`` and ``nosetests`` in quiet mode, for clarity. ``nosetests`` was slightly faster, probably because there weren't any additional plugins to load.

```bash
pytest test_mfa_login.py -q
.
1 passed in 6.55s

nosetests test_mfa_login.py -q
----------------------------------------------------------------------
Ran 1 test in 6.349s

OK
```

**Comment by mdmintz** [comment]
The main point is that your issue is off-topic because you brought up ``nosetests`` as the reason for ``switching`` from ``boto`` to ``boto3``. Nothing prevents users from installing ``boto3`` as an additional dependency, given that ``boto`` is only used for uploading log files to ``S3`` for users who have configured their SeleniumBase settings to specifically do so for that very specific integration.

Both ``pytest`` and ``nosetests`` will work with SeleniumBase, and they are interchangeable on the command-line (although ``nosetests`` won't have access to the additional ``pytest`` plugins that are being used).

**Comment by mdmintz** [comment]
boto3 replaced boto a year ago: https://github.com/seleniumbase/SeleniumBase/commit/eb57c34587249fd0fba967b8ed73a4ece597cd68
