### ISSUE TITLE
Not able to generate dashboard view in pytest html report

### ISSUE THREAD

**Issue by krishnakishore014** [seleniumbase/SeleniumBase#1157]
Iam running the command
Python -m py.test example.py --dashboard --running--headless
dashboard.html is not available in latest_logs or root folder
Seleniumbase version 2.3.7

![20220105_113724](https://user-images.githubusercontent.com/34539392/148169560-ab69bb42-d52d-4fcb-9d79-b0746e673256.jpg)

**Comment by mdmintz** [comment]
Hi @krishnakishore014, based on the pytest-html report of your screenshot, I don't think you installed it via SeleniumBase because you have version 3.1.1 of pytest-html, but the SeleniumBase setup.py file and the requirements.txt file both specify 2.0.1 as the latest supported version, which are necessary if you want to see screenshots from failing tests. And based on your run command, I'm not sure how you generated it because you never specified ``--html=FILE.html`` in it. Also, you have a command-line option that I've never seen ("running"), which should give an error, especially if it's attached to your "headless" option. I'm guessing it was not a direct copy/paste. You should start by reinstalling SeleniumBase (so that it installs pytest-html ``2.0.1``), and then you should try running a command like this:
``pytest --dashboard --html=report.html --headless`` and then see if you have any issues. You can run ``pip list`` to see which Python dependencies are installed, and the versions they're on.

**Comment by krishnakishore014** [comment]
Hi Michael,

Thanks for your reply.

I have installed seleniumbase using pip. I have tried with html 2.0.1 version as well but no luck. After running dashboard.html is not displaying properly. I am attaching screen prints for your reference. I have used --html before as well 
![20220105_195830](https://user-images.githubusercontent.com/34539392/148235054-9d703791-e83b-4e0b-829f-c41f1179cc6b.jpg)
![20220105_195443](https://user-images.githubusercontent.com/34539392/148235087-b06edfc2-f732-4ed1-a9af-521a54a3d4b5.jpg)

**Comment by mdmintz** [comment]
Hi @krishnakishore014, according to your screenshot, a Dashboard was being generated at ``C:/Users/kd95018/PycharmProjects/161811-glrs-test_automation_devops/ui_testcases/dashboard.html``. Is there no file at that location? If you open that path in a web browser, what do you see?

**Comment by krishnakishore014** [comment]
Dashboard is not displaying in that location. Also path is not displaying like this:
C:/Users/kd95018/PycharmProjects/161811-glrs-test_automation_devops/ui_testcases/dashboard.html

It is showing backward slash before dashboard.html 
. When I open it in browser your file could not be accessed is displaying 
![Uploading 20220105_204053.jpg…]()

**Comment by mdmintz** [comment]
@krishnakishore014  I'm not sure what's happening. The direction of slashes shouldn't matter. I'll need a closer look. Send me a private message on https://gitter.im/seleniumbase/SeleniumBase and then we can start a video call with a screen share.

**Comment by mdmintz** [comment]
@krishnakishore014 Maybe try searching your file system for the missing files to see if your PyCharm was initiating the test run from somewhere else. Easiest way to verify is by running tests directly from a Bash shell, a DOS prompt, a SygWin terminal, or a regular Mac terminal (instead of running from PyCharm). Or maybe you have another script running somewhere that is deleting the files after they are created. I'm not really sure without more information. I would need to see a stacktrace from after your pytest run to learn more.

**Comment by krishnakishore014** [comment]
Iam not using virtual environment in my project.will that be an issue. Can you share me the required dependencies list and installation steps to install from pip. I'm using python 3.8 version

**Comment by mdmintz** [comment]
@krishnakishore014 ``pip install seleniumbase --upgrade`` should be all you need. But if you are sharing that environment with another Python project that has different dependencies, you may find conflicts unless you switch SeleniumBase to use its own virtual environment.

With the dashboard working correctly, an html report should look something like this:

<img width="360" alt="Screen Shot 2022-01-05 at 4 57 02 PM" src="https://user-images.githubusercontent.com/6788579/148295757-b62f2109-2708-4cd4-a2d8-9bdafbf52979.png">

**Comment by krishnakishore014** [comment]
Hi Michael,
Sorry for coming back again. I have done some debbing and found that python is installed on my machine on below path and path variable is set
C/program files/python380/Scripts 
But when I installed seleniumbase using pip 
, all the dependencies are installed in below path for which path variable is not set
C/users/abc/Appdata/roaming/python/python38/Scripts 

Do I need to set path variable for this as well . My team is eagerly looking to use seleniumbase.looking for your help

![16414591376532925581574489202094](https://user-images.githubusercontent.com/34539392/148356140-9ab699fd-57a8-4d5f-9e27-a049c22256c3.jpg)
![20220106_141523](https://user-images.githubusercontent.com/34539392/148356180-47b696b9-0156-4e92-8661-414f7247fd9e.jpg)
![20220106_141451](https://user-images.githubusercontent.com/34539392/148356188-1de6aaf1-c6ed-4f36-8ffa-9fdbf65b582c.jpg)

**Comment by mdmintz** [comment]
@krishnakishore014, try adding that line to your path under System Environmental Variables and see if that solves your issue.
