### ISSUE TITLE
Use "--with-testing_base" configuration will not save logs when tests fail

### ISSUE THREAD

**Issue by cjydayang** [seleniumbase/SeleniumBase#117]
Hi, @mdmintz 
I use pytest to run demo in the example:

```
from seleniumbase import BaseCase

class MyTestClass(BaseCase):

    def test_4(self):
        # This test should FAIL
        print("\n(This test fails on purpose)")
        self.open("http://xkcd.com/1670/")
        self.find_element("FakeElement.DoesNotExist", timeout=0.5)
```
Here is the command that i ran the test:
`
pytest test.py -with-selenium --browser=firefox --with-testing_base --with-basic_test_info --log_path=./Log/
`
after running,i can't find log file in the log path i have set,only a empty dictionary called “archived_logs” in the working dictionary.
In addition,screenshot will not generate.

Is there anything wrong with my command? or any other problem？

My environment is python3.5 on linux.
Hope you can give me some advice.
Thanks!

**Comment by mdmintz** [comment]
Hi @cjydayang. First, it looks like you're missing a second dash in front of the "with" in "--with-selenium", but when using pytest instead of nosetests, you might not need that part at all. Second, if you're using "--with-testing_base", then by default all logs including screenshots will be stored UNLESS you individually pick out which logs you want. In your script above, you only put "--with-basic_test_info", which means SeleniumBase will only use that unless you also add "--with-screenshots". So either add that, or remove "--with-basic_test_info" (So that only "--with-testing_base" is used). Third, try using "--log_path=Log/" instead of "--log_path=./Log/" (or stick with the default "latest_logs"). Forth, the archived logs folder will stay empty unless you have ARCHIVE_EXISTING_LOGS set to True in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/config/settings.py . That prevents the archived logs folder from getting too huge with screenshots. Here's a full command you can try to see if a "latest_logs" folder gets created with data: (from examples/ folder) "pytest test_fail.py --with-selenium --with-testing_base --browser=firefox". If that works fine, you can add in the "--log_path=Log/".

If you're still having issues, I'll be back in 12 hours.

**Comment by cjydayang** [comment]
@mdmintz sorry to bother you.

sorry about "-with-selenium" , it is my mistake when copying command,and i use "pytest test_fail.py --with-selenium --with-testing_base --browser=firefox" got the same result.

I try to use Nosetests,which might be work fine:
`nosetests test.py --with-testing_base --with-selenium --browser=firefox -s --report `
 after running test ,i got latest_logs and latest_report. So,is there a bug when using pytest?

Another question about using nosetests:
In dir "latest_logs" contains a log file "basic_test_info.txt",which logs will add into this file? i only got these in my test in the basic_test_info.txt:
```
Last_Page: https://xkcd.com/1670/
Browser: firefox 
Traceback: NoneType: None
```
Is this normal? 
will some nosetests debug log add into this file?(such as some debug logs print on the terminal.)

Thanks again for your reply.

**Comment by mdmintz** [comment]
@cjydayang Ah, I figured it out. It's a Python 3 bug in SeleniumBase. I mostly run SeleniumBase on Python 2, which didn't have any issues. When I updated SeleniumBase to run on Python 3 last week, I must've forgotten to check that the log files are generated correctly. I'm going to find a fix for this. Thanks for finding this bug!

**Comment by mdmintz** [comment]
So far, I'm seeing that sys.exc_info() in the pytest tearDown() method of base_case.py shows something different based on whether I'm running on Python 2 or Python 3. In Python 2, the exception info of the failing test gets displayed, but nothing shows up on Python 3.

**Comment by mdmintz** [comment]
I found the solution to the bug. It appears that I'll need to handle different versions of Python differently for this, based on an answer I found on StackOverflow: https://stackoverflow.com/a/39606065   `self._outcome.errors` can see the exception info in Python 3, while `sys.exc_info()` can see the exception info in Python 2. I'll code up the fix for this soon.

**Comment by cjydayang** [comment]
@mdmintz Honored to help you find this bug! I will check it when you fix the bug.

**Comment by mdmintz** [comment]
@cjydayang Changes are in. Should be fixed now. Give it a try with the latest SeleniumBase (1.4.4) and let me know how it goes. Thanks!

**Comment by cjydayang** [comment]
@mdmintz using nosetests works well,Exception will add in basic_test_info.txt->Traceback.
but i use pytest get the same result as before.

**Comment by mdmintz** [comment]
Which version of Python 3 are you using? You may need at least 3.4. If you have that, can you verify that "python3 setup.py install" installed the latest version of SeleniumBase after you pulled the latest version of the repo? Can you paste the run command you used to run the example test? I've tested both on Python 2 and 3, with both pytest and nosetests, working correctly on a Mac computer.

**Comment by cjydayang** [comment]
@mdmintz Sorry... I copy "base_case.py" into my own project and use it,when i update SeleniumBase, i forget to update base_case.py in my own project...
Now everything works well after i try again,thank you for your reply and If I have other problems i wiil create separate issue.
Thanks for your help again.

**Comment by mdmintz** [comment]
@cjydayang Sounds good! I will close this issue as resolved.
