### ISSUE TITLE
how to use setupclass and tearDownClass?

### ISSUE THREAD

**Issue by shmily-cwt** [seleniumbase/SeleniumBase#1243]
I want my test cases to initialize once, then execute all the cases, and then end. Not every test case needs to be initialized

**Comment by mdmintz** [comment]
If you run ``pytest`` using ``--reuse-session`` (or ``--rs``), then only the first test will spin up the browser, and then all other tests will reuse the browser session. If you need more initialization, you can mark a test to go first by adding  ``@pytest.mark.run(order=1)``, or calling it ``test_aaa`` since it runs alphabetically. You could name the last test ``test_zzz`` to have it run last.

```python
import pytest
from seleniumbase import BaseCase

class MyTests(BaseCase):
    @pytest.mark.run(order=1)
    def test_aaa(self):
        ...
```

While reusing a session with ``--reuse-session``, all tests will run in the same browser window because only the first test gets initialized.

**Comment by shmily-cwt** [comment]
Don't you develop a setupclass and teardown class? This makes it more flexible to use

**Comment by mdmintz** [comment]
That was described above. For a per-test basis there’s overriding setUp() and tearDown() as seen here: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py
