### ISSUE TITLE
Help：How do I start a write case from seleniumBase

### ISSUE THREAD

**Issue by wang-qa** [seleniumbase/SeleniumBase#1252]
I don't know how to use it to write a new case  

1. `pip install seleniumbase`

```python
# I write
# The goal is to open Baidu.com
from seleniumbase import BaseCase


class openURL(BaseCase):
    def test_openbaidu(self):
        self.open('www.baidu.com')
        print('ok')

```

```python
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGoogle():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_google(self):
    # Test name: google
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.google.com.hk/")
    # 2 | setWindowSize | 1234x839 | 
    self.driver.set_window_size(1234, 839)
    # 3 | Waiting for the page to open | 1234x839 | 
    time.sleep(5)
    # 4 | close |  | 
    self.driver.close()
  
```
2. Runing
- Run using Python  
![image](https://user-images.githubusercontent.com/58168764/158538009-ae11cc9e-a653-4e47-bfe2-1995c6d4b2cc.png)
- Run using Pytset  
![image](https://user-images.githubusercontent.com/58168764/158538165-349e8292-c2e7-4925-9132-1c4a5729c340.png)

**Comment by mdmintz** [comment]
Hi @wang-qa You can't name your file ``selenium.py`` because then you would be overriding the built-in module that has the same name. Instead, give it a name like this: ``my_test.py``. Tests should be run with ``pytest``. You can use the SeleniumBase Recorder to generate tests instead of using Selenium IDE. More info on the SeleniumBase Recorder here: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/recorder_mode.md

Here are lots of example tests that you can run: https://github.com/seleniumbase/SeleniumBase/tree/master/examples

There's also a Chinese translation of SeleniumBase, if it helps: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/translations/chinese_test_1.py

```python
from seleniumbase.translate.chinese import 硒测试用例  # noqa


class 我的测试类(硒测试用例):
    def test_例子1(self):
        self.开启("https://zh.wikipedia.org/wiki/")
        self.断言标题("维基百科，自由的百科全书")
        self.断言元素('a[title="首页"]')
        self.断言文本("新闻动态", "span#新闻动态")
        self.输入文本("#searchInput", "舞龍")
        self.单击("#searchButton")
        self.断言文本("舞龍", "#firstHeading")
        self.断言元素('img[src*="Chinese_draak.jpg"]')
        self.输入文本("#searchInput", "麻婆豆腐")
        self.单击("#searchButton")
        self.断言文本("麻婆豆腐", "#firstHeading")
        self.断言元素('div.thumb div:contains("一家中餐館的麻婆豆腐")')
        self.输入文本("#searchInput", "精武英雄")
        self.单击("#searchButton")
        self.断言元素('img[src*="Fist_of_legend.jpg"]')
        self.断言文本("李连杰", 'li a[title="李连杰"]')
```

**Comment by wang-qa** [comment]
Yes，I think I solved the problem
This document helped me >> https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/recorder_mode.md
