### ISSUE TITLE
(Windows) sbase behave-gui fails when processing example calculator.feature file

### ISSUE THREAD

**Issue by sarchule** [seleniumbase/SeleniumBase#1352]
Using Seleniumbase ver. 3.2.6, Windows 10, Python 3.10.4

Within examples\behave_bdd directory, attempt to open behave gui by issuing "sbase behave-gui". Fails with following:
  File "C:\workproj\python\github_sbase\seleniumbase\console_scripts\sb_behave_gui.py", line 374, in main
    for row in output.decode("utf-8").split("\n"):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 1542: invalid continuation byte

If I rename calculator.feature file so that it is not processed, then behave gui appears as expected. Problem appears to start with third scenario (line 25, "6 x 7 x 8 x 9 = 3024"), where multiplication symbol is non-ascii. Also, if I change encoding within sb_behave_gui.py from "utf-8" to "latin1", then issue does not appear but not sure whether that is the correct solution.

**Comment by mdmintz** [comment]
@sarchule Thanks for finding and reporting this! I'm trying to determine the best solution. Looks like Windows and macOS handle this a bit differently, and trying "latin1" instead of "utf-8" can garble the non-ascii characters. Worst case scenario: need to use if statements to parse the output differently on different OSs, best case scenario is finding a simple solution that works on any OS. I'll figure that out and ship a fix today in a new release.

**Comment by sarchule** [comment]
Sure, no problem. Just starting to take a look at the Seleniumbase BDD features and not very familiar with Python behave. Curious whether behave has some unit test which they use to verify different feature file encodings? If so, that test might be useful to you in coming up with a solid solution--just a suggestion. I know you're quick to address issues, but no pressure from me to get this resolved today. I can certainly continue investigating by simply ignoring that calculator feature file for now. Thanks!

**Comment by mdmintz** [comment]
@sarchule Fixed in https://github.com/seleniumbase/SeleniumBase/releases/tag/v3.2.7
