### ISSUE TITLE
How does the "downloaded_files" folder work?

### ISSUE THREAD

**Issue by M-Zubair10** [seleniumbase/SeleniumBase#1557]
SeleniumBase Driver creates downlaod_files folder inside my working dir when initialized
This is weird, it must be inside pypi package folder

**Comment by mdmintz** [comment]
SeleniumBase creates the ``downloaded_files`` folder in the working directory where ``pytest`` is invoked. Any click-initiated downloads will go there. It's also used for any special files needed. It also holds lock files to prevent issues with multi-threading. The folder resets at the start of every new ``pytest`` run so that past test runs don't interfere with new ones. The folder is hard-coded there to prevent issues. And since the folder is reset at the start of new ``pytest`` runs, you wouldn't want to use any other existing folders for it.

There are lots of built-in test methods that are specially made for that folder, such as:

```python
self.get_downloads_folder()

self.get_browser_downloads_folder()

self.get_path_of_downloaded_file(file)

self.is_downloaded_file_present(file)

self.delete_downloaded_file_if_present(file)
# Duplicates: self.delete_downloaded_file(file)

self.assert_downloaded_file(file)
```

If you need files in a different folder, use Python ``os``, ``sys``, and ``shutil`` libraries for copying the files you need into a different folder after they get downloaded to the ``downloaded_files`` folder.

**Comment by M-Zubair10** [comment]
Fine

**Comment by gmyers-aiq** [comment]
Another user [asked about this](https://github.com/seleniumbase/SeleniumBase/issues/2435) with regard to AWS Lambda, and I don't think the issue should have been closed. You seem to be under the impression that the `downloaded_files` folder is only created when invoked from pytest, but that is not the case. Setting the `proxy` argument to SB, for instance, will have the effect of triggering downloads.

And this flatly does not work in an AWS Lambda environment, where the file system is read-only, with the one notable exception of the `/tmp` directory. So ideally we need the ability to do something like this:

```
with SB(proxy="...", downloads_dir="/tmp") as sb:
    ...
```

I saw in [another thread](https://github.com/seleniumbase/SeleniumBase/discussions/2422) you suggested copying the files out of the `downloaded_files` directory _after_ they are downloaded. But again I must stress that this will not work inside a Lambda function, because they will never get downloaded in the first place. SeleniumBase will crash with an OSError before that can happen.

For my own use case, I am trying to come up with a workaround involving symbolic links to the `/tmp` directory but it is honestly painful. Adding an argument to SB() that would allow the customization of where this folder lives would be a much cleaner solution.

**Comment by mdmintz** [comment]
It's a variable. Variables can be changed:

```python
>>> from seleniumbase.fixtures import constants
>>> constants.Files.DOWNLOADS_FOLDER
'downloaded_files'
```

If you need it changed, do so before launching the browser with `SB()`.

**Comment by gmyers-aiq** [comment]
Unfortunately, that won't work. The reason is because the [`__init__.py` file](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/__init__.py) under the parent seleniumbase folder performs a number of imports—which have the effect of using the initial constant value _before_ any change can be made.

So in your short two line example, running the first line (`from seleniumbase.fixtures import constants`) does the following:

* Runs `from seleniumbase.core.browser_launcher import get_driver` (among other imports)
* That, in turn, runs `from seleniumbase.core import proxy_helper` (among other imports)
* Runs code like this:
    ```
    DOWNLOADS_DIR = constants.Files.DOWNLOADS_FOLDER
    PROXY_ZIP_PATH = os.path.join(DOWNLOADS_DIR, "proxy.zip")
    ```

And all of that happens on import—before I have the chance to change the variable. So as a result of importing seleniumbase.fixtures, there are now half a dozen global constants that need changing as well.

From a user perspective, it feels really bad to override the value of a hard-coded variable in a third-party library like this, because that means whatever code I write to do so is now tightly-coupled to this specific release of SeleniumBase. But what happens if, in a future release, some of those variables that I'm monkey-patching are removed? Or if new ones are added? I hope you can recognize that is not really sustainable.

**Comment by mdmintz** [comment]
You should be aware that there's a reason for the hard-coding. The `downloaded_files` folder is a special temporary folder that gets cleaned out in SeleniumBase processes, such as new `pytest` runs, so that new runs are fresh. If that folder location was to be easily changed, someone might accidentally set it to a system folder, which could then be accidentally deleted. It's made hard to change on purpose.

It's more of a limitation on the AWS Lambda side, due to their read-only directory structure, which has caused issues with other frameworks, such as here: https://github.com/microsoft/playwright/issues/27775.
To quote Microsoft in https://github.com/microsoft/playwright/issues/27775#issuecomment-1777521209: "Sounds like a problem with AWS since it is running locally."

Fortunately, there are workarounds available in SeleniumBase, and you can just set some variables.
Here's a more complete list of variables to set for changing the `downloaded_files` folder for AWS:

```python
>>> from seleniumbase.fixtures import constants
>>> constants.Files.DOWNLOADS_FOLDER
'downloaded_files'
>>> from seleniumbase.core import proxy_helper
>>> proxy_helper.DOWNLOADS_DIR
'downloaded_files'
>>> proxy_helper.PROXY_ZIP_PATH
'downloaded_files/proxy.zip'
>>> proxy_helper.PROXY_ZIP_LOCK
'downloaded_files/proxy.lock'
>>> proxy_helper.PROXY_DIR_PATH
'downloaded_files/proxy_ext_dir'
>>> proxy_helper.PROXY_DIR_LOCK
'downloaded_files/proxy_dir.lock'
>>> from seleniumbase.core import download_helper
>>> download_helper.DOWNLOADS_DIR
'downloaded_files'
>>> download_helper.downloads_path
'/Users/michael/github/SeleniumBase/examples/downloaded_files'
>>> from seleniumbase.core import browser_launcher
>>> browser_launcher.DOWNLOADS_FOLDER
'/Users/michael/github/SeleniumBase/examples/downloaded_files'
```

For people who needed SeleniumBase to work on AWS Lambda, the workarounds have been effective.

**Comment by gmyers-aiq** [comment]
If you're fully opposed to making it configurable, fine. But why not just hard-code it to live underneath `tempfile.gettempdir()` instead of the user's working directory? The temp dir seems to perfectly fit the use case you described.

**Comment by mdmintz** [comment]
> If you're fully opposed to making it configurable, fine. But why not just hard-code it to live underneath `tempfile.gettempdir()` instead of the user's working directory? The temp dir seems to perfectly fit the use case you described.

@gmyers-aiq That would break backwards-compatibility.
Downloaded files and some temporary system files are expected in the `./downloaded_files` folder from the user's working directory where scripts were initiated. Then users know where to access those files.

Before proposing changes that may break backwards-compatibility, consider the many businesses, schools, and individual developers using SeleniumBase that expect certain things to be consistent. It's part of the documentation.

**Comment by Vander-Bilt** [comment]
The problem persists after many years.
