### ISSUE TITLE
Parameter to maximize the browser window?

### ISSUE THREAD

**Issue by M-Zubair10** [seleniumbase/SeleniumBase#1558]
I cannot find any paramet to maximize window
How to parse Options object to it

**Comment by mdmintz** [comment]
There are multiple ways to maximize the window depending on how you're calling SeleniumBase.

If running the tests with pure ``python``, you can use the ``SB`` context manager:

```python
from seleniumbase import SB

with SB(maximize=True, uc=True) as sb:
    sb.open("https://nowsecure.nl")
    sb.wait_for_text("OH YEAH, you passed!", "h1")
    print(sb.get_text("body"))
    screenshot_name = "now_secure_image.png"
    sb.save_screenshot(screenshot_name)
    print("\nScreenshot saved to: %s" % screenshot_name)
```

You can also pass in ``--maximize`` as a command-line option to initiate it. Also works with any of the ``pytest`` formats from https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md

**Comment by M-Zubair10** [comment]
Thanks, sys.argv is good

**Comment by M-Zubair10** [comment]
Wait, maximize not working with Driver class

**Comment by mdmintz** [comment]
It's not part of the raw ``driver`` initialization process. Maximizing the driver is done with ``driver.maximize_window()`` after the ``driver`` has already been initialized. The ``SB`` context manager does extra because it works with the driver after it has been initialized. See the example above with the ``SB`` context manager.

**Comment by M-Zubair10** [comment]
Ok, thanks for the clarification.
