### ISSUE TITLE
Page that refreshes infinitely during the script

### ISSUE THREAD

**Issue by KolyStudio** [seleniumbase/SeleniumBase#1587]
Hello, when executing my script, at some point, the script starts to refresh the page infinitely and no longer execute the code.

I put some rest times, but if I remove them, then the page restarts in a loop

```
while(groups>0):
                try:    
                        self.sleep(0.5)
                        self.click('button[title="Nouveau Chat"]') # BOUTON NOUVEAU CHAT
                        groups = len(self.find_elements('div:contains("BOOSTKOJAK")')) # C0MPTAGE DES GROUPES
                        self.sleep(0.5)
                        self.click('div:contains("BOOSTKOJAK")') # SELECTION D'UN GROUPE
                        self.sleep(0.5)
                        self.click('button.xjFne') # LANCEMENT DU CHAT
                        # self.sleep(0.5)
                        self.click('div.uCVEc') # SELECTION DETAILS DU GROUPE
                        # self.sleep(0.5)
                        self.click('a:contains("Quitter le groupe")') # QUITTER LE GROUPE
                        self.sleep(0.5)
                        print('Groupes restants:', groups)
                       
                except:
                        print('Groupe non supprimé')
```

**Comment by mdmintz** [comment]
You probably have an infinite loop in there causing that, as seen by the ``while(groups>0):`` in your script.
That's something you'll have to debug to figure out. This can help:

```python
import ipdb; ipdb.set_trace()
```

Use that to create a breakpoint in your script so that you can manually step through lines with ``n`` + "Enter", or continue from there with ``c`` + "Enter".

Here's more about ``pytest`` debugging: https://seleniumbase.com/the-ultimate-pytest-debugging-guide-2021/
