### ISSUE TITLE
(Windows) New dependency fancycompleter is broken for python 3.10 / 3.11

### ISSUE THREAD

**Issue by amonroy-logi** [seleniumbase/SeleniumBase#1619]
See:
- https://github.com/pdbpp/fancycompleter/issues/36
- https://github.com/pdbpp/fancycompleter/issues/37

**Comment by mdmintz** [comment]
Thanks for reporting this! Looks like a Windows-only issue. I’ll quickly work to find a workaround and ship a new release in the next 7 hours with either a fix or a revert.

**Comment by mdmintz** [comment]
### Here's a chart of who's affected by this bug:

<img width="1374" alt="Screenshot 2022-11-25 at 9 16 23 PM" src="https://user-images.githubusercontent.com/6788579/204068646-4ba248bb-95c8-4317-bfbe-8bdcb10f45d7.png">

### (Windows users running Python 3.10 or Python 3.11)

**Comment by mdmintz** [comment]
The best solution here is to remove ``pdbpp`` (and sub-dependencies: ``fancycompleter``, ``pyrepl``, ``wmctrl``) from required dependencies. Hopefully ``pdbpp`` can make changes to fix this bug soon so that it can be added back as the main debugger.

In the meantime (with ``pdbpp`` to be removed in the next release) people can choose their debugger, and install it separately/optionally. ``ipdb`` is also an option, but that one has some large dependencies, such as ``ipython`` and ``jedi``.

**Note:** The standard ``pdb`` debugger comes with Python. It doesn't have any fancy colors or features, but it still works.

**Comment by mdmintz** [comment]
Released in ``4.9.1`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.9.1
CC @amonroy-logi

**Comment by mdmintz** [comment]
I ended up building my own debugger for version ``4.9.2``: https://github.com/seleniumbase/SeleniumBase/issues/1623
