### ISSUE TITLE
How to use SeleniumBase + python Browser (build with PyQt5)

### ISSUE THREAD

**Issue by standfv** [seleniumbase/SeleniumBase#1662]
How to use SeleniumBase + python Browser (build with PyQt5) [Custom browser]
Thanks.

**Comment by mdmintz** [comment]
If you're looking for a GUI for ``pytest``, see the SeleniumBase Commander / GUI: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/commander.md
It uses the Tkinter instead of PyQt5, but it's the same idea. SeleniumBase is a Python framework, so you can use any other Python tools that you need to, such as PyQt5.
