### ISSUE TITLE
Is it possible to use chrome binary location with seleniumbase

### ISSUE THREAD

**Issue by sunny9495-dev** [seleniumbase/SeleniumBase#1682]
Hi,

First of all, I am really impressed with the library.

My question is, is it possible to use chrome binary location with SeleniumBase?

If not, is there any separate parameters to add to PyInstaller to install on client side.

**Comment by mdmintz** [comment]
Hi, SeleniumBase uses the browser binary that it finds on the PATH. Same for the driver, but if the driver is not compatible with the binary, the driver manager will automatically put a matching driver in the ``seleniumbase/drivers`` folder.

If you're trying to use SeleniumBase with PyInstaller, there's a whole thread about that here: https://github.com/seleniumbase/SeleniumBase/issues/1075#issuecomment-973021116

Below is a video showing PyInstaller usage with the SeleniumBase Recorder. The Recorder has had many improvements since then.

https://user-images.githubusercontent.com/6788579/142454125-1b4a82e7-13be-4842-99bd-aedc79f3ddc6.mov

**Comment by mdmintz** [comment]
Hello, and thank you!

SeleniumBase automatically detects the browser binary that's located on the system PATH. If there's no matching driver, SeleniumBase automatically downloads one to the ``seleniumbase/drivers`` folder.

There's a whole thread about using PyInstaller with SeleniumBase here (an example with the SeleniumBase recorder): https://github.com/seleniumbase/SeleniumBase/issues/1075#issuecomment-973021116

Here's a video showing the PyInstaller executable launching the recorder (and SeleniumBase scripts/tests via the Recorder App):

https://user-images.githubusercontent.com/6788579/142454125-1b4a82e7-13be-4842-99bd-aedc79f3ddc6.mov

The SeleniumBase Recorder App has had many improvements since that video was created.

**Comment by mdmintz** [comment]
A newer version of SeleniumBase has options for setting a custom Chrome binary location. See https://github.com/seleniumbase/SeleniumBase/issues/1709
