### ISSUE TITLE
CloudFlare bypass not working on remote server, only locally

### ISSUE THREAD

**Issue by lgcavalheiro** [seleniumbase/SeleniumBase#1711]
Hi! I reached this project from https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/847 but i am experiencing the same issue from when i was using vanilla Selenium: i can use it for scraping normally when developing, but when the project is deployed to an actual server, it can't bypass targets protected by CloudFlare.

The current configurations i'm using for SeleniumBase are as follows ([full file](https://github.com/lgcavalheiro/prihud/blob/candidate/better-scraping-v1/database/scraping/impl/chromium_scraper.py)) :
``` python
self.driver = Driver(headless=True, headless2=True, uc=True)
```

I've also tried with `(headless=True, uc=True)`, `(headless2=True, uc=True)` and `(uc=True)` in an interactive environment from within the server, but without success.

I'm also deploying with docker and docker-compose, here's the [Dockerfile](https://github.com/lgcavalheiro/prihud/blob/candidate/better-scraping-v1/Dockerfile) (target is `composed`) and the [docker-compose.yml](https://github.com/lgcavalheiro/prihud/blob/candidate/better-scraping-v1/docker-compose.yml) in case it helps.

Any help is greatly appreciated and many thanks for making this very cool project available! :)

**Comment by mdmintz** [comment]
Hello! Thank you! A few things... just use the ``headless2`` arg, not both headless modes together. (More info on that here: https://github.com/chromium/chromium/commit/e9c516118e2e1923757ecb13e6d9fff36775d1f4). It'll automatically detect which headless mode to set based on your Chrome version. On Chrome 109 and newer, it'll use ``--headless=new`` automatically for Chrome options, which provides a headless mode that works exactly as regular headed mode.

As for ``uc=True``, I have a repo running GitHub Actions for that mode here: https://github.com/mdmintz/undetected-testing. See if that server setup is different from yours. If you are deploying remote servers, make sure that the chromedrivers used there are the ones specially modified from undetected-chromedriver (SeleniumBase does have it's own version of undetected-chromedriver with a few modifications). By "specially modified", I mean that undetected-chromedriver has a "Patcher" that modifies chromedriver to avoid detection by anti-bot services. If those servers of yours aren't using the modified versions of the drivers, then you'll get detected.

SeleniumBase renames a downloaded chromedriver to ``uc_driver`` in order to not mess with regular Chrome runs. It's easy to get one from outside of tests like this:

```bash
sbase get uc_driver

*** chromedriver version for download = 109.0.5414.74 (Latest)

Downloading chromedriver_mac64.zip from:
https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_mac64.zip ...
Download Complete!

Extracting ['chromedriver', 'LICENSE.chromedriver'] from chromedriver_mac64.zip ...
Unzip Complete!

The file [uc_driver] was saved to:
/Users/michael/github/SeleniumBase/seleniumbase/drivers/uc_driver

Making [uc_driver 109.0.5414.74] executable ...
[uc_driver 109.0.5414.74] is now ready for use!
The file [uc_driver] was saved to:
/Users/michael/github/SeleniumBase/seleniumbase/drivers/uc_driver

Making [uc_driver 109.0.5414.74] executable ...
[uc_driver 109.0.5414.74] is now ready for use!
```

At this point, the only difference is in the name. Once you run a SeleniumBase test in ``uc_mode``, the Patcher will patch that driver, and it will gain abilities that will allow it to bypass detection on sites.

But do note that running the ``sbase get uc_driver`` script automatically detects the OS and browser version you have, so if your local run has a different environment from your servers, you'll have to SSH into them, install SeleniumBase, and call ``sbase get uc_driver`` in order to get the correct drivers for your servers. (And then run a test in ``uc_mode`` to patch it.) The modified driver is not enough though, and undetected-chromedriver includes other methods that are called automatically in order to help you avoid detection during tests.

**Comment by mdmintz** [comment]
And if that doesn't solve your issue, then this might: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/594

**Comment by mdmintz** [comment]
More improvements to UC Mode in ``4.12.5`` - https://github.com/seleniumbase/SeleniumBase/issues/1725#issuecomment-1416661834
