### ISSUE TITLE
How to fix seleniumbase chromedriver cmd prompt popup?

### ISSUE THREAD

**Issue by sunny9495-dev** [seleniumbase/SeleniumBase#1716]
Hi,

One of my client having the issue, i face the same too, how to fix the issue. Here is the video.

[https://share.getcloudapp.com/5zu2kZg2](https://share.getcloudapp.com/5zu2kZg2)

Any solution for the issue.

Thanks

**Comment by mdmintz** [comment]
It looks like you're using a 3rd party tool for running scripts. SeleniumBase is not affiliated with these 3rd party tools, so if there's a specific issue with them, we recommend filing issues in their respective repositories.

If you'd like to run SeleniumBase tests via GUI, you can use the built-in app. (See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/commander.md)

In order to help debug SeleniumBase issues, we need to know:

* The SeleniumBase version.
* The browser/version.
* The run command used to initiate a SeleniumBase script.
* The stack trace that resulted (if any).

If you're having an issue with running scripts directly, please include the above details when opening a ticket.
