### ISSUE TITLE
generate screenshot on fixture failure with function as scope level

### ISSUE THREAD

**Issue by nfk** [seleniumbase/SeleniumBase#1732]
When you use selenium base with fixture and function as scope level. Selenium base does not provide screenshot and debug info if a failure occurs at this level which is hard to debug on CI. Anywhere sb fixture is used we should have the same level of debug info on failure.

seleniumbase: `4.12.4`

Here a sample with a context fixture call `ctx`:
```python
import pytest

@pytest.fixture(scope="function")
def ctx(sb):
    sb.get("https://e.foundation")
    sb.wait_for_element_visible("//div[@class='unknown']", timeout=1)

def test_1(ctx, sb):
    pass

def test_2(sb):
    sb.get("https://e.foundation")
    sb.wait_for_element_visible("//div[@class='unknown']", timeout=1)
```

Selenium base generated screenshot only for the test case `test_2`:
```
tree latest_logs 
latest_logs
└── tests.test_issue.test_2
    ├── basic_test_info.txt
    ├── page_source.html
    └── screenshot.png

2 directories, 3 files
```

**Comment by mdmintz** [comment]
Your fixture is outside the scope of the test that calls it; that's why you see the following when you run it:

```bash
1 failed, 1 error
```

``sb`` is a fixture for tests, not stand-alone functions. If something fails during a test, then all the logging will be there as expected.

Presently, due to https://github.com/pytest-dev/pytest/issues/5044, you're going to get an "error", which ``pytest`` handles differently from failures. This limits how that situation can be handled.

However, you can put your code in a try/except block in your fixtures, and if something goes wrong, you can take the screenshot there. Just make sure that you prevent errors from happening in your function-scope fixtures to prevent pytest from marking those as errors.
