### ISSUE TITLE
How use proxy with undetectable?

### ISSUE THREAD

**Issue by Shpakoff** [seleniumbase/SeleniumBase#1768]
Browser is not proxied, can you help solve this problem. I need to use un with proxy. With my code:
driver = Driver(is_mobile=True,undetectable=True,agent=USER_AGENT,proxy=f"{PROXY_USER}:{PROXY_PASS}@{PROXY_HOST}:{PROXY_PORT}")

**Comment by mdmintz** [comment]
I think I know the issue you're having. It's related to https://stackoverflow.com/a/2709023/7058266
For most people, the ``proxy="user:pass@host:port"`` should work, but if using special characters, (Eg. Chinese, Japanese, Korean, Russian, etc.), then some characters can get garbled. This is because SeleniumBase was using ``latin1`` in a few places instead of ``utf-8``. The affected areas include UC Mode code. Sometimes Windows needs Latin1 instead of UTF-8, but I can make a change and see what happens. Which OS were you using?

**Comment by mdmintz** [comment]
@Shpakoff The port can't be 0000. Your proxy string is invalid. The proxy functionality is working for me on a valid proxy string.

**Comment by Shpakoff** [comment]
> @Shpakoff The port can't be 0000. Your proxy string is invalid. The proxy functionality is working for me on a valid proxy string.

of course there is another port) I will not throw off the data of my proxy.  This is just as an example, there the port was 31112

**Comment by Shpakoff** [comment]
the proxy itself is 100% working.  There problem is that when I turn on resolve undetectable , it stops proxying the browser.

**Comment by mdmintz** [comment]
Here's an example test you can try with the proxy:
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/proxy_test.py
This works for me for my proxy:
``pytest proxy_test.py --uc --proxy=USER:PASS@HOST:PORT``

**Comment by mdmintz** [comment]
Let me know if you have any issues with the above example with ``4.13.4`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.13.4

**Comment by Shpakoff** [comment]
> Let me know if you have any issues with the above example with `4.13.4` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.13.4

After the new patch, everything worked. You're really good) Thank you)
