### ISSUE TITLE
Integration UC with wire

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#1774]
Hi,
Thanks for this package. Integration uc with with soon?
Thanks

**Comment by mdmintz** [comment]
Hi @FranciscoPalomares, 
There's ``--uc`` mode, and there's ``--wire`` mode, but the two can't be used together due to unresolved issues with ``selenium-wire``: https://github.com/wkeeling/selenium-wire/search?q=undetected&type=issues

But the good news is that you don't need the wire integration anymore because SeleniumBase now has ``--uc-cdp`` mode, which can collect ALL the same data that ``--wire`` mode collected.

Here's an example that uses it: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py

**Comment by FranciscoPalomares** [comment]
Hi @mdmintz ,
Responses are not received.
Thanks

**Comment by mdmintz** [comment]
It's all received if you set the parameter to ``*`` here:

```python
self.driver.add_cdp_listener("*", lambda data: print(pformat(data)))
```

(From https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py)

**Comment by FranciscoPalomares** [comment]
Response body not captured with '*'
