### ISSUE TITLE
Error with Google Login "This browser or app may not be secure"

### ISSUE THREAD

**Issue by hyeoni369** [seleniumbase/SeleniumBase#1775]
When I try google login, "This browser or app may not be secure" message comes up.

`with SB(undetectable=True, proxy=proxy, user_data_dir=cache_folder_path) as sb_context:`

I've tried above code.

Normally works well. But sometimes that message comes up.

How can I be perfectly not detected?

**Comment by mdmintz** [comment]
``incognito`` mode also helps with ``uc`` mode while changing the proxy. See https://github.com/mdmintz/undetected-testing/actions/runs/4270055578/jobs/7433630301

That job was using: ``pytest -v -s --uc --incognito --headless2 --user-data-dir=my_data_dir``

Config: https://github.com/mdmintz/undetected-testing/blob/master/.github/workflows/python-package-2.yml

For more "perfection", don't set the ``user_data_dir`` at all so that the default one is used. Inconsistencies in the ``user_data_dir`` can lead to automation-detection.
