### ISSUE TITLE
Is it possible to debug SeleniumBase tests with VSCode?

### ISSUE THREAD

**Issue by cengizili** [seleniumbase/SeleniumBase#1821]
Hi, firstly thanks for creating such a beautiful framework. I want to debug my seleniumbase tests with VSCode to inspect the contents of my variables, is that possible?

**Comment by mdmintz** [comment]
Greetings. You can use standard ``pdb`` debugging within VS Code or any terminal.

Eg.  ``import pdb; pdb.set_trace()`` to put a breakpoint in your code.

Then you can walk through your tests line-by-line with ``n`` + ``Enter``. Step through methods with ``s`` + ``Enter``, and continue running the test with ``c`` + ``Enter``. To list defined variables, use ``dir()`` within the breakpoint.

I've written a complete debugging guide here: https://seleniumbase.com/the-ultimate-pytest-debugging-guide-2021/ (Includes a video tutorial.)

**Comment by cengizili** [comment]
Can I control breakingpoints with codes instead of pressing keys? I have a flask server and when there is a request I want to open a browser, do somethings and wait for the next request without closing the browser since the next request will do the same thing with different request content. Would something like below work if we put the corresponding code that resumes debugging to TODO line?

`class TestClass(FunctionalClass):
    import pdb; pdb.set_trace() # set a breakpoint and wait for the first request
    @app.route('/myroute', methods=['POST'])
    # TODO: some pdb code to continue debugging when there is a request
    request_json = request.get_json()
    target = request_json['target']
    username = request_json['username']
    def test_logic2(self):
        print(self.isSuccess(username="cengizhanili", target="babbaoogway"))
        import pdb; pdb.set_trace() # set a breakpoint again and wait for the next request
`

**Comment by mdmintz** [comment]
Full details about ``pdb`` can be found here: https://docs.python.org/3/library/pdb.html
In your case, instead of using breakpoints, you should just tell your script directly what you want the automation to do, which includes telling it what elements to wait for, etc.

But if you still need to use POST requests with Selenium, I did find a post about it here: https://stackoverflow.com/a/62142792/7058266
Example:
```python
response = self.driver.request('POST', 'url', data={"x": "y"})

jsrequest = '''var xhr = new XMLHttpRequest();
xhr.open('POST', '{{URL}}', false);
xhr.send(param1=value&param2=value2');
return xhr.response;'''

result = self.driver.execute_script(jsrequest)
```

That does however go off the topic of the original question, which is debugging SeleniumBase tests in VS Code, and for that, see the ``pdb`` instructions posted above.
