### ISSUE TITLE
Is it possible to disable element id selection in recording mode

### ISSUE THREAD

**Issue by wuwen5** [seleniumbase/SeleniumBase#1876]
![image](https://github.com/seleniumbase/SeleniumBase/assets/5037807/eb4f285e-c1c1-4a94-828a-6e8ba3e4f165)

Is it possible to disable element id selection in recording mode, because some front-end framework element ids are automatically generated and will change.

**Comment by mdmintz** [comment]
Yes. One way of doing that is by removing the ids from any element with an id (via the Python debugger command-line):

```python
self.remove_attributes("[id]", "id")
```

After you call that, the Recorder will no longer use ids when recording on that specific page (because elements on that page will no longer have an ``id`` attribute). If you navigate to a different page, call it again.

**Comment by mdmintz** [comment]
In ``4.15.3`` (https://github.com/seleniumbase/SeleniumBase/issues/1909), ids will be skipped by default if they contain a dash or an underscore followed by a digit. (Eg. ``-2``, ``_4``)
