### ISSUE TITLE
Please add mouse simulation function will be better with BOT

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#1877]
Please add mouse simulation function will be better with BOT

`driver.execute_cdp_cmd('Input.emulateTouchFromMouseEvent',` {"type": "mouseMoved", "x": 100, "y": 100, "button": "left"})`

https://github.com/kkoooqq/fakebrowser/blob/main/doc/fakebrowser-demo.gif

**Comment by thanhvodad** [comment]
I mean, let's add to the API, for example function selft.click it will mouse the mouse to the click point, and execute the click afterwards.

**Comment by mdmintz** [comment]
Given the regular changes to selenium's CDP code, (https://github.com/SeleniumHQ/selenium/blob/bc7e0c7341fdde78cdd80ce572002a7866fd1769/py/CHANGES -> Eg. ``Add CDP files for v113 and remove v110``), it seems better to keep that separate. Otherwise it might involve significant maintenance depending on the changes later. For this, it also gets more complicated because coordinates could change based on the screen width and/or browser window size.
