### ISSUE TITLE
Can Not open multiple browser via driver manager (via direct import) with deferent user_data_dir. But It was working.

### ISSUE THREAD

**Issue by anovob** [seleniumbase/SeleniumBase#1889]
How Can I open multiple browser via driver manager (via direct import) with deferent user_data_dir

I am using Tkinter to open browser. When I open first browser by clicking in tkinter button its open and running. But when I click to open second browser its not open. I also want to use deferent user_data_dir for all browser.

Note: I am using UC mode. It was working that option with seleniumbase. But it's stop working when chromedriver updated version to 113.  Its still working with undetected-chromedriver. But it can not bypass Cloudflare in headless mode.

Here Is my Code:

```
project_dir = pathlib.Path().absolute()

def start_open_browser():
    num = default_browser.get()
    num = int(num)
    event = threading.Event()
    thrSet = threading.Thread(target=start_application, args=(None, num))
    thrSet.daemon = True
    thrSet.start()
    event.set()


def start_driver(arg=None, i=0):
    user_data_dir = str(project_dir / 'userdatas' / f"userdata{i}")
    driver = Driver(user_data_dir=user_data_dir, uc=True)
    print(driver)
    driver.maximize_window()
    return driver


def start_application(arg=None, browser=0):
    driver = start_driver(arg, browser)
    while True:
        try:
            time.sleep(10)
            driver.get('https://www.youtube.com/watch?v=3xYXUeSmb-Y')
        except NoSuchWindowException:
            break
        except:
            continue
    driver.quit()
    return


if __name__ == "__main__":
    multiprocessing.freeze_support()

    root = Tk()

    # display section
    frame = LabelFrame(root, text="Start Application", font=('Helvetica bold', 12))
    frame.pack(fill="both", expand=False, padx=20, pady=5)
    browser_number = ['1', '2', '3', '4', '5', '6', '7']
    default_browser = StringVar()
    default_browser.set(browser_number[0])
    ent_browser = OptionMenu(frame, default_browser, *browser_number)
    ent_browser.pack(fill='both', expand=False, padx=10, pady=10, side=LEFT)
    btn_browser = Button(frame, text='Start Application', command=start_open_browser, height=1,
                         font=('Helvetica bold', 15))
    btn_browser.pack(fill='both', expand=True, padx=10, pady=11, side=LEFT)

    root.title(f"Testing")
    root.mainloop()
```
When I open first browser this is working fine. When I open other browser Chrome opens with "Data;" with selenium

I also print driver first time open uc_driver. second time open cromedriver
Here is the driver print value
1st: `<seleniumbase.undetected.Chrome (session="818e958ca40f0e419c3681f57b163957")>`
2nd: `<selenium.webdriver.chrome.webdriver.WebDriver (session="eb419ef2a305c5fbc7f337e42f99f379")>`

**Comment by mdmintz** [comment]
Hey there. Multithreading isn't easy. There's a full team of developers working on https://github.com/pytest-dev/pytest-xdist in order to make Python multithreading work well (with ``pytest``). That plugin, (which is included with SeleniumBase), is the only officially supported way of making multithreaded scripts work properly with SeleniumBase.

Usage example (for 4 threads):

```bash
pytest -n4
```

There's a lot of SeleniumBase code specifically built for compatibility with ``pytest-xdist`` to allow for handing multi-threaded tests properly. Given the complexity of multithreading, the ``pytest-xdist`` way will remain the only supported way for now.

If you still want to use a different way to handle multithreading SeleniumBase scripts, you are welcome to try on your own at your own pace & time.

--------

As for your other issue with setting the ``user_data_dir`` to multiple values within the same test run, there are numerous open issues with that from the ``undetected-chromedriver`` repo: https://github.com/search?q=repo%3Aultrafunkamsterdam%2Fundetected-chromedriver+user_data_dir&type=issues

SeleniumBase's **UC Mode** tries to use Undetected Chromedriver as much as possible while minimizing the built-in changes to it. SeleniumBase has fixed and improved on several issues with it, but some things are rooted deep, and are unlikely to change unless the Undetected-Chromedriver repo resolves some of those issues on their own.

The good news is that I recently heard that the maintainer of Undetected Chromedriver is rewriting the whole package (https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1270#issuecomment-1556371743).

<img width="1024" alt="New_UC_Coming" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/abfc39e0-6abd-4ad9-a324-081905d67b4e">

Once that is complete, Undetected Chromedriver users can be hopeful of getting fixes to important issues, such as the ``user_data_dir`` bug listed above.
