### ISSUE TITLE
uc will be detected if use the Muti-thread in windows 

### ISSUE THREAD

**Issue by ngantsung** [seleniumbase/SeleniumBase#1918]
if I only use the one thread that is normal will not be detected , but if I use Muti-thread that will be detected in Windows ,and this situation will only happen in windows , there is no problem in Mac .
Here is the website 'https://premier.hkticketing.com/'
![Screenshot 2023-06-21 at 7 27 20 PM](https://github.com/seleniumbase/SeleniumBase/assets/111569568/edfd9fcc-3736-4b33-885b-cd23719c6d9c)
![Screenshot 2023-06-21 at 7 27 12 PM](https://github.com/seleniumbase/SeleniumBase/assets/111569568/3174d33f-7918-4ac2-9e5c-a5beebcae454)

**Comment by mdmintz** [comment]
Hey there. Multithreading isn't easy. There's a full team of developers working on https://github.com/pytest-dev/pytest-xdist in order to make Python multithreading work well (with ``pytest``). That plugin, (which is included with SeleniumBase), is the only officially supported way of making multithreaded scripts work properly with SeleniumBase.

Example for UC Mode (using 4 threads) when using [a format that supports pytest](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md):

```bash
pytest --uc -n4 --uc-cdp --incognito
```

There's a lot of SeleniumBase code specifically built for compatibility with ``pytest-xdist`` to allow for handing multi-threaded tests properly. Given the complexity of multithreading, the ``pytest-xdist`` way will remain the only supported way for now.

If you still want to use a different way to handle multithreading SeleniumBase scripts, you are welcome to try on your own at your own pace & time.

**Comment by anovob** [comment]
How can use multi-threading if I want to use via driver manager (via direct import)

**Comment by anovob** [comment]
@ngantsung If you don't need headless mode then use `undetected chromedriver`. It's working for me with multi-threading.

**Comment by mdmintz** [comment]
Here's a tutorial for generic multiprocessing with Python: https://docs.python.org/3/library/multiprocessing.html

If you want a prebuilt multiprocessing solution for SeleniumBase, see: https://github.com/seleniumbase/SeleniumBase/issues/1918#issuecomment-1600696841

**Comment by anovob** [comment]
@mdmintz I followed generic multiprocessing for direct import uc mode. But first browser worked ok other browser detect bot. 
First browser run UC_DRIVER
But Second browser run CHROMEDRIVER

Please check without pytest I think you will find this issue. few version ago it was working fine.

**Comment by mdmintz** [comment]
@anovob You would need to implement your own locking system to prevent access to shared resources. Packages like https://pypi.org/project/fasteners/ can help you do that. The `pytest` plugin https://pypi.org/project/pytest-xdist/ already handles that correctly for SeleniumBase tests that run with `pytest -n=NUM`. Since that works, people who need multiple processes with SeleniumBase should use that.

**Comment by anovob** [comment]
> Upgrade to `4.17.12` (or newer) for the multithreading improvements: https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.17.12

Thanks For your update. Its working now.
