### ISSUE TITLE
How can I use MySQL with SeleniumBase?

### ISSUE THREAD

**Issue by xiaocf-git** [seleniumbase/SeleniumBase#1927]
Hello, I want to link mysql and query data for test data, how should I do it in seleniumbase? Could you give me some code examples, thank you

**Comment by mdmintz** [comment]
Instructions are here:
https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/mysql_installation.md

It's part of the video tutorial here: https://www.youtube.com/watch?v=n-sno20R9P0&t=456s

And although we've switched from Travis to GitHub Actions, there's a Travis deploy file that has been maintained because it showed actual steps for running with the MySQL DB: https://github.com/seleniumbase/SeleniumBase/blob/master/.travis.yml
