### ISSUE TITLE
After upgrading to 4.17.1 (from 4.13.9), the ElementNotVisibleException exception is not being caught

### ISSUE THREAD

**Issue by MrCB08** [seleniumbase/SeleniumBase#1988]
After deciding to upgrade to the latest version after quite some time, I noticed something odd where the `ElementNotVisibleException` exception is not being caught, which prevented the except statement from ever executing.
 
I decided to do some testing on it, changing it to `Exception` for now to make it reach the except block, and here's what I noticed:

In version 4.17.1:
- ``isinstance(e, ElementNotVisibleException)`` results to ``False``
- ``type(e)`` results to ``<class 'selenium.common.exceptions.ElementNotVisibleException'>``
- Selenium version: 4.11.2
![Selenium 4 11 2 Issue -Edited](https://github.com/seleniumbase/SeleniumBase/assets/56218268/43cb925d-8738-4a41-8936-eafcc2d6b754)

In version 4.13.9:
- ``isinstance(e, ElementNotVisibleException)`` results to ``True``
- ``type(e)`` also results to ``<class 'selenium.common.exceptions.ElementNotVisibleException'>``
- Selenium version: 4.8.2
![Selenium 4 8 2 Issue - Edited](https://github.com/seleniumbase/SeleniumBase/assets/56218268/e1160b5f-7656-44b8-afe9-a12830c803b3)

**Comment by mdmintz** [comment]
This is related to https://github.com/seleniumbase/SeleniumBase/issues/1903, where `selenium` started added a lot of extra info to messages such as `; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception`. This caused issues for people who were expecting the message to stay consistent, or for people who just wanted to see clean error messages without repetitive info added on.

This led to `seleniumbase` having its own `ElementNotVisibleException`.

OLD: `selenium.common.exceptions.ElementNotVisibleException`
NEW: `seleniumbase.common.exceptions.ElementNotVisibleException`

In your code, a better way would be to use: ``if self.is_element_visible(selector):`` to determine if a selector is visible. Or, if you still want to catch exceptions, use the newer one, or a generic `except Exception:` in your `try` blocks.

Note that `self.click(selector)` also has a `timeout` arg.
So instead of doing this:

```python
self.wait_for_element(selector, timeout=timeout)
self.click(selector)
```

You can do this instead:

```python
self.click(selector, timeout=timeout)
```

Here's an example of using `self.is_element_visible(selector)`:

```python
if self.is_element_visible(selector):
    self.click(selector)
else:
    # ... (Do something else)
```

(Note that `is_element_present()` and `is_element_visible()` are different... If the element is hidden, but still exists in the html, then `is_element_present()` will return True, but the element won't be clickable because it is not visible.)

Here's an example of importing the new exception:

```python
from seleniumbase.common.exceptions import ElementNotVisibleException
```
