### ISSUE TITLE
driver with non-static information

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2031]
some websites knows that I came before and I came again..
there is static and special variables in driver that detecting me
i changing the user-agent but still..(also ip)

i think that using webGL or some thing like that, that have special id for me

im using `with SB() as sb:`

**Comment by mdmintz** [comment]
It sound like you're trying to ask about **UC Mode**...

SeleniumBase **UC Mode** is used for bypassing bot-detection services. It's not the default mode, but it can be activated via `pytest` command-line options, eg: `pytest --uc`, or by passing `uc=True` as an arg for the [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) that are called directly with `python`.

### Here are some existing examples that use ``--uc`` mode:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py

### Here's a raw driver example:

```python
from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://nowsecure.nl/#relax")
time.sleep(6)
driver.quit()
```

--------

Although **UC Mode** gets you past the front door to a website looking like a human, some websites may continue to try to detect you. If you still need to get around that, try https://github.com/asweigart/pyautogui, which lets you control the mouse and keyboard, rather than performing actions with Selenium that could be detectable via bot-detection services.

**Comment by YOTYTeaM** [comment]
> It sound like you're trying to ask about **UC Mode**...
> 
> SeleniumBase **UC Mode** is used for bypassing bot-detection services. It's not the default mode, but it can be activated via `pytest` command-line options, eg: `pytest --uc`, or by passing `uc=True` as an arg for the [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) that are called directly with `python`.
> 
> ### Here are some existing examples that use `--uc` mode:
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py
> 
> ### Here's a raw driver example:
> ```python
> from seleniumbase import Driver
> import time
> 
> driver = Driver(uc=True)
> driver.get("https://nowsecure.nl/#relax")
> time.sleep(6)
> driver.quit()
> ```
> 
> Although **UC Mode** gets you past the front door to a website looking like a human, some websites may continue to try to detect you. If you still need to get around that, try https://github.com/asweigart/pyautogui, which lets you control the mouse and keyboard, rather than performing actions with Selenium that could be detectable via bot-detection services.

thank you but thats not i mean

i mean in first visit, it works
but in next visitation, website knows me

i find out, the website can detect me with WebGL
I don't think it's just that
But WebGL shows my graphics information

 https://pixelscan.net/ here you can see
It will be fixed by disabling gpu, but I don't know if it will be detectable or not

**Comment by mdmintz** [comment]
Have you tried:

```python
from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://pixelscan.net/")
time.sleep(15)
driver.quit()
```

<img width="1254" alt="Screenshot" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/0a4c7c66-36af-4bc6-8090-6520127cc412">
