### ISSUE TITLE
Reusing SeleniumBase instance

### ISSUE THREAD

**Issue by ton77v** [seleniumbase/SeleniumBase#2061]
I find SeleniumBase really handy for automating browser actions 👏

Unlike when you are testing, sometimes it's useful to share SB instance between your own methods. Is there a way to achieve this rather than doing it within the context manager "with" statement?

I've seen the '--reuse-session' command line argument, but is there a way to achieve this functionality when you don't use test runners? 

Using Driver helps, but Driver has no methods like 'is_element_visible', etc

**Comment by mdmintz** [comment]
The ``--reuse-session`` / ``--rs`` arg exists only for `pytest` tests because pytest knows what all the tests are in advance, therefore it can keep the browser open at the end of a test and hand off the driver to the next test to continue from there. Then pytest also knows when the last test has run, therefore it can close the browser at the end of that last test.

There's no concept of script order for pure `python` runs because there's no test organization, which is something that a test framework provides (such as SeleniumBase tests that are run with `pytest`).

See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md for a description of all 23 syntax formats. If you can't use one of the ``pytest`` formats, there are other ways of keeping the browser open after tests.

As for the raw `driver` missing methods, that comes directly from raw selenium. That's why the SeleniumBase API exists to add the much-needed functionality. I'm working on a way to back-port useful methods. In the meantime, there are helper methods to assist with raw driver formats.

--------

Full description of Reuse Session Mode:

For tests that use one of the ``pytest`` syntax formats, you can reuse the browser session by adding ``--reuse-session`` or ``--rs`` to your pytest run command. That will keep the same session open for all tests. If you want to close the session between different classes of tests, use ``--reuse-class-session`` or ``--rcs``.
