### ISSUE TITLE
UC mode not working on linux

### ISSUE THREAD

**Issue by DRVR1** [seleniumbase/SeleniumBase#2063]
Testing:

I tested seleniumbase UC mode in different contexts (didn`t work for linux)

versions:

Chromedriver is the default installed (and i hope patched) by seleniumbase
Google Chrome stable was downloaded to its last version 6/9/23 (dd/mm/yy) 
Chromium was downloaded to its last version 6/9/23 (dd/mm/yy) 
Also seleniumbase was updated to its last version 6/9/23 (dd/mm/yy) 

contexts:

Driver: Chromedriver
Browser: Google Chrome 
Platform: Windows
Headless: True or False
Ip: Home
Tested site: https://nowsecure.nl/
Undetectable: Yes

Driver: Chromedriver
Browser: Chromium
Platform: Linux (ubuntu 23.04)
Headless: True or False
Ip: Home
Tested site: https://nowsecure.nl/
Undetectable: NO

Driver: Chromedriver
Browser: Google Chrome Stable
Platform: Linux-Server
Headless: True
Ip: Google VPS
Tested site: https://nowsecure.nl/
Undetectable: NO

Driver: Chromedriver
Browser: Chromium
Platform: Linux-Server
Headless: True
Ip: Google VPS
Tested site: https://nowsecure.nl/
Undetectable: NO

Driver: Chromedriver
Browser: Google Chrome Stable
Platform: Linux (ubuntu 23.04)
Headless: True or False
Ip: Home
Tested site: https://nowsecure.nl/
Undetectable: NO

**Code:**

```
from seleniumbase import SB
from time import sleep

def checkText(sb,text: str) -> bool:
    try:
        sb.assert_text(text)
        return True
    except:
        return False

with SB(uc=True,headless=True) as sb:
    sb.open("https://nowsecure.nl/")
    print("sleeping")
    sleep(10)
    if(checkText(sb,"OH YEAH, you passed!") or checkText(sb,"passed")):
        print("passed!!")
    sb.save_screenshot("test_result")
    print("finished")
```

**Comment by mdmintz** [comment]
UC Mode works fine on Linux when using valid proxy settings:

<img width="600" alt="Screenshot 2023-09-06 at 5 36 57 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/25409a3e-b44d-4400-81f3-fbc8a03862ae">

<img width="600" alt="Screenshot 2023-09-06 at 5 35 43 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/d3c2490b-6ecf-4e0c-9c31-64f1e4e0faac">

As seen here: https://github.com/mdmintz/undetected-testing/actions/runs/15981106181

IP Addresses could get blocked for frequent traffic, but otherwise UC Mode on Linux works.

Tested with random proxies from http://free-proxy.cz/en/proxylist/country/all/https/ping/all
