### ISSUE TITLE
Selenium-wire with Undetected Webdriver in seleniumbase

### ISSUE THREAD

**Issue by Rhaniel0** [seleniumbase/SeleniumBase#2151]
To begin with, I apologize for the poor English...

I would like to know how to use proxy with seleniumbase with `uc=True`.

I tried the following:

`with SB(uc=True, proxy='http://my_token:js_render=true&antibot=true&premium_proxy=true&proxy_country=br@proxy.zenrows.com:8001') as sb:`

And I get the following: `net::ERR_TUNNEL_CONNECTION_FAILED`

When I use proxy in the ip:port style it works perfectly.

I researched a little, maybe I need selenium-wire... the question is if I can use SB with "uc" and "wire " marked as True at the same time or is there another way of doing this?

**Comment by mdmintz** [comment]
`proxy` must be in either `host:port` or `user:pass@host:port` format.

As for mixing `uc` mode with `wire` mode: That cannot be done. See https://github.com/seleniumbase/SeleniumBase/issues/1774#issuecomment-1444399269

Those two modes can't be used together due to unresolved issues with `selenium-wire`: https://github.com/wkeeling/selenium-wire/search?q=undetected&type=issues

If using `wire` mode, you can change the proxy with `sb.set_wire_proxy(string)` (where `string` is in either `host:port` or `user:pass@host:port` format).

**Comment by Rhaniel0** [comment]
Thanks, I was able to successfully connect to the proxy just by removing `http://` from the string

**Comment by pankajkalania** [comment]
@mdmintz , how to change proxy in uc=True mode without closing browser?

**Comment by SSujitX** [comment]
> @mdmintz , how to change proxy in uc=True mode without closing browser?

I don't think it is possible.
