### ISSUE TITLE
Some network traffic is not being captured

### ISSUE THREAD

**Issue by steinpigs** [seleniumbase/SeleniumBase#2162]
This is one of the example I found.

```
import time
from seleniumbase import Driver

def callback(data):
    url = data['params']['response']['url']
    print(url)

driver = Driver(uc=True, headed=True, uc_cdp_events=True)

driver.add_cdp_listener("Network.responseReceived", callback)

driver.get("https://checkout.stripe.dev/preview")

time.sleep(100)
```

**Comment by mdmintz** [comment]
Seems similar to https://github.com/seleniumbase/SeleniumBase/issues/2149 (See https://github.com/seleniumbase/SeleniumBase/issues/2149#issuecomment-1739099472 for details)... But now that I have a URL to work with, I think I now know how to properly handle this situation...

There's a good chance the `<iframe>` is causing the issue you saw. You can set the entire page to the content of the iframe in order to grab more info. Here's the method you need: `sb.set_content_to_frame("iframe")`. Here's an example of that:

```python
from seleniumbase import SB

def callback(data):
    url = data['params']['response']['url']
    print(url)

with SB(uc=True, headed=True, uc_cdp_events=True) as sb:
    sb.driver.add_cdp_listener("Network.responseReceived", callback)
    sb.driver.get("https://checkout.stripe.dev/preview")
    sb.sleep(3)
    sb.set_content_to_frame('iframe[title="Checkout Demo"]')
    sb.sleep(3)
```

By calling `sb.set_content_to_frame("iframe")`, you're able to now see the requests that were hidden within the `iframe`.

**Comment by steinpigs** [comment]
Thanks. Using this code set_content_to_frame("iframe") worked although it opens another tab.

**Comment by steinpigs** [comment]
Although set_content_to_frame("iframe") works when you can set the iframe, how about frames that cannot be set_content_to_frame(). how will you be able to get their network traffic. Will there be a fix/solution to get all the network automatically without using iframes?

**Comment by mdmintz** [comment]
As far as I've seen, this situation only happens with iframes; and, as far as I've seen, `set_content_to_frame("iframe")` works for all those iframes, (assuming you've used the correct selector when there is more than one iframe on a page).

--------

If there happened to be another scenario where no iframes were present and not all network traffic was captured, then it likely falls outside the scope of SeleniumBase, as seen following the trail:

https://github.com/seleniumbase/SeleniumBase/blob/eea244127cf26daac6ec28a3139382378071e0d5/seleniumbase/undetected/__init__.py#L373

makes a call to

https://github.com/seleniumbase/SeleniumBase/blob/eea244127cf26daac6ec28a3139382378071e0d5/seleniumbase/undetected/reactor.py#L20

using

https://github.com/seleniumbase/SeleniumBase/blob/eea244127cf26daac6ec28a3139382378071e0d5/seleniumbase/undetected/reactor.py#L62

however, `get_log()` has the problem, and that method comes from `selenium`, not `seleniumbase`. See the `selenium` source:

https://github.com/SeleniumHQ/selenium/blob/9a6947ea4fd685b5f997415565bc5dc875a71321/py/selenium/webdriver/remote/webdriver.py#L1013

Therefore, the issue is external to `seleniumbase`, and not something that can necessarily be fixed here. There's the workaround with `set_content_to_frame("iframe")` for capturing traffic inside iframes, but if that's not enough, then the work is likely external to seleniumbase.

**Comment by slvamegestic** [comment]
`from seleniumbase import SB

def callback(data):
    url = data['params']['response']['body']
    print(url)

with SB(uc=True, headed=True, uc_cdp_events=True) as sb:
    sb.driver.add_cdp_listener("Network.responseReceived", callback)
    sb.driver.get("https://checkout.stripe.dev/preview")
    sb.sleep(3)
    sb.set_content_to_frame('iframe[title="Checkout Demo"]')
    sb.sleep(3)`
    
    
    if i trying to get body of the response, it was getting null always, how to capture network responses in seleniumbase?

**Comment by mdmintz** [comment]
This will capture and print the data:

```python
from pprint import pformat
from seleniumbase import SB

with SB(uc=True, headed=True, uc_cdp_events=True) as sb:
    sb.driver.get("https://checkout.stripe.dev/preview")
    sb.sleep(3)
    url = sb.get_attribute('iframe[title="Checkout Demo"]', "src")
    sb.driver.get(url)
    sb.sleep(3)
    sb.driver.add_cdp_listener("Network.responseReceived", lambda data: print(pformat(data)))
    sb.driver.refresh()
    sb.sleep(3)
```
