### ISSUE TITLE
UC mode doesnt working

### ISSUE THREAD

**Issue by Marsango** [seleniumbase/SeleniumBase#2172]
When i installed the latest from seleniumbase at my laptop i found the following issue:
![image](https://github.com/seleniumbase/SeleniumBase/assets/75022038/aee84820-08bd-4098-b0da-eab480535ad5)
Other website:
![image](https://github.com/seleniumbase/SeleniumBase/assets/75022038/8d733c7b-0eda-4873-8ed0-2478a7adbc78)
The same code in another PC with older version doesnt have this issue 

This is my code for simple testing:
from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://nowsecure.nl")
time.sleep(20) ##waiting for screenshot

**Comment by mdmintz** [comment]
From your screenshot, it looks like you're using "Chrome for Testing", which gets detected because it's not regular Chrome. Either regular Chrome wasn't found on your machine, or it's not in the usual location. Raw `selenium` automatically downloads "Chrome for Testing" if regular Chrome isn't found on your machine.

Try getting regular Chrome and running your script again. You'll know it worked if you no longer see "Chrome for Testing" in the notification area.

**Comment by Marsango** [comment]
> From your screenshot, it looks like you're using "Chrome for Testing", which gets detected because it's not regular Chrome. Either regular Chrome wasn't found on your machine, or it's not in the usual location. Raw `selenium` automatically downloads "Chrome for Testing" if regular Chrome isn't found on your machine.
> 
> Try getting regular Chrome and running your script again. You'll know it worked if you no longer see "Chrome for Testing" in the notification area.

Thanks! The issue has been solved when i just installed google chrome lol
