### ISSUE TITLE
Chrome starts in Mobile Mode, but should not.

### ISSUE THREAD

**Issue by MacMarde** [seleniumbase/SeleniumBase#2190]
Hi I am just trying to use the new release of SB . I start chrome just like this:

`chrome_obj = Driver(uc=True)`

The first tab of my chrome always looks like the mobile version and all other tabs I do open look normal. See screenshot:

![UC-1](https://github.com/seleniumbase/SeleniumBase/assets/50266741/31292a74-f520-43f2-aebe-0426dc295366)
![UC-2](https://github.com/seleniumbase/SeleniumBase/assets/50266741/011730a1-a95d-49f9-ae33-c9e80bb88629)

Also all tabs (including first tab) have a mobile user agent:

![UC-3](https://github.com/seleniumbase/SeleniumBase/assets/50266741/26aab17a-fb8c-4aa5-ba25-1a1d5368f248)

I am using these versions:
Chrome: 118.0.5993.71 (latest)
webdriver: has been downloaded automatically
SeleniumBase: 4.20.2 (latest)
Python: 3.7.4

So it seems to be messed up now. Same code was working properly 2 days ago, before the SB version with mobile support for UC.
Please help me. I really want to use the new features of SB.

**Comment by MacMarde** [comment]
This also happens with uc=False:

`chrome_obj = Driver()`

**Comment by mdmintz** [comment]
It's working normally for me:

```python
from seleniumbase import Driver

driver = Driver(uc=True)
try:
    driver.get("https://browserleaks.com")
    import pdb; pdb.set_trace()
finally:
    driver.quit()
```

<img width="1275" alt="Screenshot 2023-10-14 at 10 17 37 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/80384f54-f4ef-4644-8d28-ac29a076c13c">

Perhaps you've made modifications to the code, or you added `--mobile` as a command-line option? Adding command-line options will affect your tests. You'll also have that if using `pytest` and you have a `pytest.ini` file with a command-line option.

The mobile setting is off by default. Here it is in the `Driver()` manager:

https://github.com/seleniumbase/SeleniumBase/blob/ba7f21a3e93e4fd742d29a107a9d84814207c553/seleniumbase/plugins/driver_manager.py#L115

Do some debugging on that file for your local clone. Use this:

```python
import pdb; pdb.set_trace()
```

And you'll be able to track it down. I'm unable to reproduce the issue here.

You can also verify your version from within a Python script:

```python
from seleniumbase import __version__
print(__version__)
```

**Comment by MacMarde** [comment]
> Perhaps you've made modifications to the code, or you added `--mobile` as a command-line option?

Yes you are right. I was not aware that it will influence other libraries like SB too.
Thank you so much.
