### ISSUE TITLE
Handling crashing in loading extensions

### ISSUE THREAD

**Issue by mIgLLL** [seleniumbase/SeleniumBase#2195]
I need to load four extensions and use headless mode to crawl on a website. But in this multi-thread task, selenium happens to crash on loading the extensions or fail to use headless mode. But seleniumbase still working on that selenium, can seleniumbase provide an option that close those selenium that do not load extensions properly?

ps: one of the extension is proxy extension, if this doesn't work, it may expose my true ip and block me out.

**Comment by mdmintz** [comment]
If you want to make sure that a Chrome extension is installed, navigate to `chrome://extensions/` and check there. (Note that the page contains Shadow DOM, however [SeleniumBase can handle Shadow DOM](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/shadow_dom.md).)

SeleniumBase has a `--proxy` command-line option for `pytest` runs. (Eg: `pytest --proxy=user:pass@ip:port` / `--proxy=ip:port`.) This option uses the built-in Chrome extension to change proxy settings.

Also note that you should use `--headless2` if you need headless mode while using Chrome extensions. It should get activated by default if needed, but you can use that option to force using it. The old headless mode does not support extensions, but the new one does support it.

If using multithreading, make sure you're using `pytest` for that. (Eg. `pytest -n8` for 8 threads). This prevents issues that can happen when using other threading libraries with SeleniumBase. (pytest multitheading uses the `pytest-xdist` plugin)

If you're trying to avoid chromedriver detection, use UC Mode (`--uc`).

If using UC Mode, you need to unzip your custom Chrome extensions (if in `.zip`/`.crx` format) into directories first, and use `--extension-dir=EXTENSION_DIR` in order to activate them. (If not using UC Mode, then `.zip`/`.crx` is fine: `--extension_zip=EXTENSION_ZIP`.) `EXTENSION_DIR` and `EXTENSION_ZIP` accepts a comma-separated list for multiple extensions.
