### ISSUE TITLE
How to use fake_useragent with pytest?

### ISSUE THREAD

**Issue by mIgLLL** [seleniumbase/SeleniumBase#2197]
I need to change the user agent for each link since the website is truly good at anti-crawling.

How can I use the fake_useragent (which can provide me a random useragent before I open the link) with the pytest?

**Comment by mIgLLL** [comment]
I tried a code as follows and get a bug "E       self.execute_cdp_cmd('Network.setUserAgentOverride', {'userAgent': user_agent},)
E   TabError: inconsistent use of tabs and spaces in indentation"


    def test_crawl(self):
        
            	self.open("data:,")

            	while ("Windows" not in user_agent):
                    # Get a random Chrome user agent
                    user_agent = ua.random

                self.execute_cdp_cmd('Network.setUserAgentOverride', {'userAgent': user_agent},)
                new_user_agent = self.get_user_agent()
                print('\nOverrided User Agent = "%s"' % new_user_agent)

                # Open the link
				time.sleep(1)
                self.open(link)

                # Get the page source
                page_source = self.driver.page_source

                # Store the page source into MongoDB
                self.collection.insert_one({'url': link, 'page_source': page_source})

            except Exception as e:
                print(f"Failed to process link {link}: {str(e)}")

    def tearDown(self):
        # Close MongoDB connection
        self.client.close()
        super().tearDown()

**Comment by mdmintz** [comment]
Your code is incomplete, and improperly indented. Use 4 spaces instead of tabs for all indentations. Make sure you call your `execute_cdp_cmd('Network.setUserAgentOverride'` command before you open the URL. In your code, you used `link` before you defined it. To start your pytest tests with a user agent, use `pytest --agent=USER_AGENT_STRING`.

See [SeleniumBase/examples/user_agent_test.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/user_agent_test.py) for an example test that changes the user agent.

If you're trying to avoid selenium-detection, use UC Mode: `pytest --uc`
