### ISSUE TITLE
Controlling page load time in the "uc_open_with_reconnect" method

### ISSUE THREAD

**Issue by CatalinaCharlotte** [seleniumbase/SeleniumBase#2207]
Hello, I'd like to inquire about how to enforce a specific page loading time in the following code scenario.
The two lines of code that are commented out in the script represent methods I've tried before, but they seem to be less effective.

```
browser = Driver(headless=True, uc=True)
# browser.set_page_load_timeout(60)
browser.uc_open_with_reconnect('https://mjai.ekyu.moe', reconnect_time=7)
# browser.implicitly_wait(30)
```

**Comment by mdmintz** [comment]
The method `uc_open_with_reconnect()` disconnects chromedriver from Chrome during the page load process. That's how it's able to remain undetected. No selenium commands will work while disconnected. Standard settings won't be in effect either, because then a website with anti-bot services would be able to detect that.

Also, don't use `implicitly_wait` with seleniumbase, as that is likely to conflict with the standard waits.

**Comment by CatalinaCharlotte** [comment]
Thank you for your response. I'd like to understand the mechanism behind the `reconnect_time` in `uc_open_with_reconnect()` - does the `reconnect_time` value determine the reconnection timing for ChromeDriver, or is it based on the completion of the entire page load?

**Comment by mdmintz** [comment]
The `reconnect_time` is the amount of time (in seconds) that chromedriver and Chrome can't communicate with each other. chromedriver can't issue commands to Chrome, but it also means that websites can't detect chromedriver either. During the `reconnect_time`, a website can load normally. Once the `reconnect_time` has passed, chromedriver can issue commands to Chrome, but it also means that a website can detect chromedriver if it's looking for it.
