### ISSUE TITLE
Browser without selenium base passes Cloudfare automatically without clicking

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#2228]
Hi,
Browser without seleniumbase passes Cloudfare automatically without clicking
With seleniumbase not
Try with nonsecure.nl

Thanks

**Comment by mdmintz** [comment]
Hey, you've been spamming my inbox non-stop with multiple invalid and/or duplicate tickets.
Here are your tickets since last month: 

<img width="1160" alt="Screenshot 2023-10-31 at 2 51 06 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/b249b8a1-9ac8-4343-95ad-1641b04c14c6">

You're going to be blocked this time for it.

But first, remember that:
1. UC Mode must be switched on (`--uc` / `uc=True`) for it to work. (It's not enabled by default.)
2. Multithreading requires `pytest` (Eg. `pytest -n4`, which uses `pytest-xdist`).
3. `pyinstaller` is a separate repo with known bugs. It's usable with SeleniumBase when you configure it properly.
