### ISSUE TITLE
Geolocation allowing with execute_cdp_cmd and uc_open_with_reconnect

### ISSUE THREAD

**Issue by Allmight3** [seleniumbase/SeleniumBase#2240]
Hello.

My code is like this:

`from seleniumbase import Driver`
`driver = Driver(uc=True, headed=True, proxy=sb_proxy)`

On the webpage, it asks to enable location sharing which is turned off in the browser. So my solution was to use this:

`driver.execute_cdp_cmd(
"Browser.grantPermissions",
{
	"origin": f"{geo_url}",
	"permissions": ["geolocation"],
},
)
driver.execute_cdp_cmd(
"Emulation.setGeolocationOverride",
{
	"latitude": float(geo_lat),
	"longitude": float(geo_long),
	"accuracy": 100,
},
)`

That works if I follow it up with `driver.refresh()`, however cloudflare is on the same page and it requires uc_open_with_reconnect in order to bypass it. My code for that is:

`driver.uc_open_with_reconnect(url, reconnect_time=20)`

Sometimes cloudflare doesn't give a persistent cookie, so I am in need of a solution to use both. I'm unable to pass the geolocation request because `driver.refresh()` which works to bypass the geolocation doesn't work to bypass cloudflare. And the `uc_open_with_reconnect()` works to bypass cloudflare but doesn't seem to carry over the `execute_cdp_cmd` to bypass the geolocation.

So, I am stuck in a loop and unable to satisfy both.

Is there a workaround? Or some way I can enable the location sharing on the browser from the start of the driver, making `execute_cdp_cmd` unnecessary?

Thank you for your help.

**Comment by mdmintz** [comment]
There are a few possible solutions. I don't have the URL, so I can't guess which one will work best for you.

1. If you can change the GeoLocation after Bypassing Cloudflare, then do that. [SeleniumBase/examples/uc_cdp_events.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py) is an example of a script that calls a CDP command after bypassing detection.

2. Use a Chrome extension so that you can set the GeoLocation that way, while still using UC Mode via the regular means. After a quick search, I found that https://chrome.google.com/webstore/detail/change-geolocation-locati/lejoknkbcogjceoniealiipllomkpioe lets you change your GeoLocation via extension.

3. Use the CDP commands to change your GeoLocation (like in [SeleniumBase/examples/test_geolocation.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_geolocation.py)), but then use `driver.uc_open(url)` so that you open the URL in the same page, rather than in a new tab. (It might not be enough to avoid detection though.)
