### ISSUE TITLE
Excessive Memory Consumption and Freezing Issue with --headless Option on M2 Device

### ISSUE THREAD

**Issue by LiPingYen** [seleniumbase/SeleniumBase#2300]
I have encountered a similar issue in #1916. When running on the M2 device with the `--headless` option, Google Chrome Helper (GPU) gradually consumes more and more memory, eventually causing the computer to freeze. Through testing, I've observed that this behavior persists regardless of whether the `--uc` is enabled or if multiple threads(`-n2`) are being used. If `--headless` is not used, the memory usage of Google Chrome Helper (GPU) remains stable and relatively low.

1. with `--headless`
```
pytest test.py -n2 --dashboard --html=report.html --rs --crumbs --headless —uc 
```
<img width="952" alt="Screenshot 2023-11-19 at 10 39 31 AM copy" src="https://github.com/seleniumbase/SeleniumBase/assets/47491041/a30a49ae-1228-476e-bdae-7c40d02e09b4">

2. without `--headless`
```
pytest test.py -n2 --dashboard --html=report.html --rs --crumbs --uc 
```
<img width="948" alt="Screenshot 2023-11-19 at 10 56 11 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/47491041/88ef412f-74ec-4786-b836-b298e4717f31">

**Comment by mdmintz** [comment]
Maybe related to https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1445
Maybe related to https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1362
Maybe related to https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1270

I ran over 1000 tests in UC Headless mode on an M2 Mac, and my machine didn't reach memory usage that high. Maybe yours is a special case, or maybe you ran a lot more tests than I did. If it happens due to running a lot more than 1000 tests on an M2 Mac, then maybe you should consider adding a step where all Chrome processes get terminated after a fixed number of tests (eg. every 5000 tests, or something like that).

**Comment by OpsecGuy** [comment]
Just a reminder for everyone (Of course it might not be the case here)

driver.close() is completely different from driver.quit()
I see many people misunderstand that.

driver.close() -> Closes currently active tab, if you use only 1 tab and you call .close(), a Chrome process will be still active.
driver.quit() -> Quits Chrome process and doesn't leave any processes in the background.

**Comment by LiPingYen** [comment]
Hi @mdmintz, after conducting several tests, I've discovered that using the `--rs` option in headless mode leads to an increasing memory occupation by Google Chrome Helper (GPU). It seems that reusing the browser session for all tests (triggered by `--rs`) in headless mode is causing the mentioned issue, while there are no issues in non-headless mode. If someone encounters the same issue, they can consider removing the `--rs` option.

**Comment by gottogethelp** [comment]
Just a quick note to say that I'm getting excessive memory consumption on an M1 Mac in headless and I don't have `--rs`enabled. Quite often see over 10Gb and sometimes much higher such that my machine crashes!
