### ISSUE TITLE
Cannot make it run "--headed" inside a virtual display

### ISSUE THREAD

**Issue by lolren** [seleniumbase/SeleniumBase#2352]
I cannot make it run  headed inside pyvirtualdisplay. it always run on my main diplay. Running it headless get`s detected by the server. Thank you

**Comment by mdmintz** [comment]
If you're using the `Driver()` format, then use https://github.com/mdmintz/sbVirtualDisplay for Xvfb activation:

```python
from sbvirtualdisplay import Display
from seleniumbase import Driver

display = Display(visible=0, size=(1440, 1880))
display.start()

driver = Driver(uc=True, headless=True)
driver.uc_open_with_reconnect("https://pixelscan.net/", reconnect_time=10)
# ...
driver.quit()

display.stop()
```

`headless` mode is also the default mode on Linux. Use `--headed`/`headed=True` to override.

Most [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) activate Xvfb by default on Linux systems, but not the `Driver()` format since it doesn't have all the `BaseCase` methods that most formats have. I would need to see more code to help better, as I cannot guess what you did.
