### ISSUE TITLE
colab driver not working

### ISSUE THREAD

**Issue by Msjeongs** [seleniumbase/SeleniumBase#2360]
!pip install -U seleniumbase 

!apt-get update
!pip install selenium
!pip install undetected-chromedriver
!apt-get install chromium-browser chromium-chromedriver
!apt-get upgrade

from seleniumbase import Driver
import time

driver = Driver(uc=True, incognito=True , headless=True)
driver.get("https://nowsecure.nl/#relax")
time.sleep(8)
html = driver.page_source()
driver.quit()

I ran the code above and nothing happened. Can you help me? It runs for 10 minutes and automatically shuts down without returning anything.

**Comment by mdmintz** [comment]
Raw Chromium likely won't work (or will get you detected). Get the regular Chrome browser and use that instead.

You don't want a chromium driver. SeleniumBase will get the regular chromedriver for you, and then modify that as needed.

`seleniumbase` already has it's own modified version of `undetected-chromedriver`. You shouldn't be using the original `undetected-chromedriver` (don't install it directly). That might overwrite something.

Use the `SB()` context manager format instead of the `Driver()` format so that it takes care of the virtual display for you. Otherwise you need to wrap your code with https://github.com/mdmintz/sbVirtualDisplay to make things work. Try `headed=True` instead of doing anything with headless so that you override the default headless mode on Linux. With the virtual display, you won't need headless mode, which is more likely to be detected.

Try this script:

```python
from seleniumbase import SB

with SB(uc=True, headed=True, test=True) as sb:
    sb.driver.uc_open_with_tab("https://nowsecure.nl/#relax")
    sb.sleep(1.2)
    if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
        sb.get_new_driver(undetectable=True)
        sb.driver.uc_open_with_reconnect(
            "https://nowsecure.nl/#relax", reconnect_time=3
        )
        sb.sleep(1.2)
    if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
        if sb.is_element_visible('iframe[src*="challenge"]'):
            with sb.frame_switch('iframe[src*="challenge"]'):
                sb.click("span.mark")
                sb.sleep(2)
    sb.activate_demo_mode()
    sb.assert_text("OH YEAH, you passed!", "h1", timeout=3)
    html = sb.driver.page_source
    sb._print(html)
```

**Comment by mdmintz** [comment]
Someone from the [SeleniumBase Discord server](https://discord.gg/EdhQTn3EyE) got it working on Google Colab with:

```python
from seleniumbase import SB
import subprocess
import nest_asyncio
nest_asyncio.apply()

# Start an Xvfb session
subprocess.run(['xvfb-run', '-a'])

from seleniumbase import SB

with SB(uc=True, test=True, headed=True, locale_code="en") as sb:
    sb.activate_cdp_mode(URL)
    # ...
```
