### ISSUE TITLE
DataDome Detection

### ISSUE THREAD

**Issue by riley-ball** [seleniumbase/SeleniumBase#2383]
![image](https://github.com/seleniumbase/SeleniumBase/assets/42449953/4bf6aaf5-acdd-42e8-8294-e4b2fe9cf580)

I'm trying to simply login to soundcloud.com which seems to use DataDome as its means of detecting bots. However, I can only seem to login when I spin up a browser using:

from seleniumbase import BaseCase

class SoundCloudTests(BaseCase):
    def test_1_open_soundcloud(self):
        self.open("https://soundcloud.com")
        # Perform any initial setup, like bypassing captchas
        input("Press Enter in the console after logging in...")  # Wait for manual interaction

    def test_2_post_login_actions(self):
        # This test will run in the same session after you've manually logged in
        # Perform any actions that require being logged in
        pass

And then creating a NEW tab (with the driver not attached) which allows me to login without being detected. Every library I have used seems to have this issue that having the driver attached to the current tab breaks the anti-detection. Any potential workarounds or solutions would be greatly appreciated! 

(Even ways to potentially unattach from the current session to allow a user to manually login and then re-attach afterwards would work)

**Comment by mdmintz** [comment]
If you're looking to do some manual activities in the browser while remaining undetected in UC Mode, then upgrade to `seleniumbase` `4.22.2` so that you can use `"breakpoint"` as an option for `reconnect_time` (instead of passing in a numeric value):

```python
driver.uc_open_with_reconnect("https://nowsecure.nl/#relax", reconnect_time="breakpoint")
driver.uc_open_with_reconnect("https://nowsecure.nl/#relax", "breakpoint")

# Other methods for advanced use:

driver.reconnect(timeout="breakpoint")
driver.reconnect("breakpoint")
```

(See https://github.com/seleniumbase/SeleniumBase/issues/2384)

Remember: The driver must remain disconnected from the browser in order for you to evade detection.)
