### ISSUE TITLE
SB with Stealth not pass iphey.com , pixelscan.net 

### ISSUE THREAD

**Issue by pythondeveloperz** [seleniumbase/SeleniumBase#2406]
hello please i try to use SB with seleniumstealth but not pass iphey.com , pixelscan.net 

this is my code 👍 

```

> from seleniumbase import Driver
> from selenium_stealth import stealth
> 
> driver = Driver(uc=True,mobile=True)
> 
> stealth(
>     driver,
>     languages=["en-US", "en"],
>     vendor="Google Inc.",
>     platform="Android",
>     webgl_vendor="Google Inc. (Imagination Technologies)",
>     renderer="ANGLE (Imagination Technologies,PowerVR Rogue GE8320, OpenGL ES 3.2)",
>     fix_hairline=True,
> )
> driver.get("https://iphey.com")
> 
> 
> #driver.get("https://browserleaks.com/webrtc")
> driver.sleep(10000)
> driver.quit()

```

**Comment by mdmintz** [comment]
For starters, you can't combine SB `mobile` mode with `selenium-stealth` because `selenium-stealth` overrides `mobile` mode settings. For bypassing automation detection, choose between:
* **UC Mode** + `selenium-stealth`
* **UC Mode** + **Mobile Mode**
* **UC Mode** alone

If your goal is to pass the unmasked-fingerprint test and the no-automation-framework-detected test, then use:

```python
from seleniumbase import Driver

driver = Driver(uc=True)
driver.uc_open_with_reconnect("https://pixelscan.net", "breakpoint")
driver.quit()
```

<img width="1350" alt="Screenshot 2024-01-02 at 10 32 53 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/2dd0ed1f-7fae-47ce-9c19-6e2c757069fb">

----

Combining `selenium-stealth` with **UC Mode** will make it such that they still can't detect that you're using an automation framework, but they may still be able to see that you're masking your fingerprint.

If you use `selenium-stealth` with **UC Mode**, you can still bypass Cloudflare:

```python
from seleniumbase import Driver
from selenium_stealth import stealth

driver = Driver(uc=True)
stealth(
    driver,
    languages=["en-US", "en"],
    vendor="Google Inc.",
    platform="Android",
    webgl_vendor="Google Inc. (Imagination Technologies)",
    renderer="ANGLE (Imagination Technologies,PowerVR Rogue GE8320, OpenGL ES 3.2)",
    fix_hairline=True,
)
driver.uc_open_with_reconnect("https://nowsecure.nl/#relax", "breakpoint")
driver.quit()
```
----

Or you can use **UC Mode** with **Mobile Mode**:

(Use with `driver.get()` instead of `driver.uc_open_with_reconnect()`)

```python
from seleniumbase import Driver

driver = Driver(uc=True, mobile=True)
driver.get("https://nowsecure.nl/#relax")
driver.sleep(6)
driver.quit()
```

<img width="980" alt="Screenshot 2024-01-02 at 10 50 58 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/c4bb6a7d-d195-43c9-aa27-d26e7f66846c">

----

But if you just need to get past the Turnstile, here's the simplest, most reliable way:

```python
from seleniumbase import Driver

driver = Driver(uc=True)
driver.uc_open_with_reconnect("https://nowsecure.nl/#relax", "breakpoint")
driver.quit()
```

<img width="1175" alt="Screenshot 2024-01-02 at 10 59 07 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/5a519d60-651b-4c3e-8bfb-373486923bb0">

**Comment by pythondeveloperz** [comment]
> ```python
> "https://nowsecure.nl/#relax"
> ```

when i use UC mode + Mobile it didnt pass as i use UC mode only i upload you screenshots appear the result

![fingerprint masking](https://github.com/seleniumbase/SeleniumBase/assets/152682481/66bf66a8-d5f1-4e76-9c5c-01832a66187c)
![antidetect browser](https://github.com/seleniumbase/SeleniumBase/assets/152682481/f3fb2e7d-22e0-47ac-89e5-ada7b3a2a311)

**Comment by pythondeveloperz** [comment]
> `from selenium_profiles import webdriver
> from selenium_profiles.profiles import profiles
> 
> profile = profiles.Android()
> 
> driver = webdriver.Chrome(profile, uc_driver=True, seleniumwire_options=True) # or pass seleniumwire-options
> # checkout headers
> driver.get("https://pixelscan.net")
> input("Press ENTER to quit..")
> driver.quit()
> exit()`

https://github.com/kaliiiiiiiiii/Selenium-Profiles

when i use this package for mobile emulation it passes the point of masking fingerprint is it possible to use this package with Seleniumbase instead of Seleniumwire ?

**Comment by mdmintz** [comment]
All that matters is: "No automation framework detected".
That's the whole point of UC Mode: To appear human.

A website will know you're masking your fingerprint if you use mobile mode, but they still won't detect your automation framework because you also have UC Mode:

<img width="536" alt="Screenshot 2024-01-02 at 11 49 11 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/7ab1ec78-ce82-49d6-a125-683a95039a33">

----

If your goal is to pass the unmasked-fingerprint test and the no-automation-framework-detected test, then use this:

```python
from seleniumbase import Driver

driver = Driver(uc=True)
driver.uc_open_with_reconnect("https://pixelscan.net", "breakpoint")
driver.quit()
```

<img width="1350" alt="Screenshot 2024-01-02 at 10 32 53 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/2dd0ed1f-7fae-47ce-9c19-6e2c757069fb">

That means not using mobile mode. Just use regular UC Mode.

**Comment by pythondeveloperz** [comment]
> > `from selenium_profiles import webdriver
> > from selenium_profiles.profiles import profiles
> > profile = profiles.Android()
> > driver = webdriver.Chrome(profile, uc_driver=True, seleniumwire_options=True) # or pass seleniumwire-options
> > # checkout headers
> > driver.get("https://pixelscan.net")
> > input("Press ENTER to quit..")
> > driver.quit()
> > exit()`
> 
> https://github.com/kaliiiiiiiiii/Selenium-Profiles
> 
> when i use this package for mobile emulation it passes the point of masking fingerprint is it possible to use this package with Seleniumbase instead of Seleniumwire ?

what about to combine this package with SB?

**Comment by mdmintz** [comment]
It sounds like you should ask the maintainer of selenium-profiles for combining their package with seleniumbase. It should be easy for them to do it if they swap out the selenium-wire driver with the seleniumbase driver.

**Comment by Tongcheng** [comment]
Running in colab, with UC=True, without mobile, also seems to have "pixelscan.net" saying "I'm masking the fingerprint". Does this mean pixelscan's hardware fingerprint can detect if you're in a docker (Colab is in docker)?

`
with SB(uc=True, xvfb=True, proxy="<proxy>") as sb:
    sb.driver.uc_open_with_reconnect("https://pixelscan.net", 30)
    sb.driver.save_screenshot("screenshot.png")`

**Comment by mdmintz** [comment]
@Tongcheng Possibly due to Colab or Docker or the proxy used. Regular SeleniumBase UC Mode works fine on that page.

**Comment by Tongcheng** [comment]
Thanks @mdmintz for the reply! I actually started a fresh EC2/ubuntu image, installed SeleniumBase without docker, but it seems PixelScan reports hardware fingerprint masking detected:

![image](https://github.com/seleniumbase/SeleniumBase/assets/6565047/0539c485-1194-4883-9703-3234618db11e)

Do you know if it's due to Linux?

**Comment by mdmintz** [comment]
@Tongcheng It thinks you're spoofing your location. SeleniumBase UC Mode doesn't change your location, so you might be doing something separately that's causing your issue, such as using a bad proxy.
