### ISSUE TITLE
Dashboard and report not reflecting failure correctly with pytest-check

### ISSUE THREAD

**Issue by listerplus** [seleniumbase/SeleniumBase#2442]
I use [pytest-check](https://pypi.org/project/pytest-check/) for times that my test function checks more than one thing and want to proceed with the other checks if one of them fail.

When a test fails with pytest-check:
(a) for dashboard - chart shows Passed, table shows Passed
(b) for report - chart shows Passed, table shows Failed

```
import pytest
from seleniumbase import BaseCase
import pytest_check
BaseCase.main(__name__, __file__)

class FailingTests(BaseCase):
    @pytest.mark.expected_failure
    def test_find_army_of_robots_on_xkcd_desert_island(self):
        self.open("https://xkcd.com/731/")
        print("\n(This test should fail 1)")
        count = 0
        # self.assert_equal(count, 1)
        pytest_check.equal(count, 1)
        print("\n(This test should fail 2)")
        # self.assert_equal(count, 2)
        pytest_check.equal(count, 2)
```

Test info:
```
================================= FAILURES ==================================
________ FailingTests.test_find_army_of_robots_on_xkcd_desert_island ________
FAILURE: check 0 == 1
test_fail.py:13 in test_find_army_of_robots_on_xkcd_desert_island() -> pytest_check.equal(count, 1)

FAILURE: check 0 == 2
------------------------------------------------------------
Failed Checks: 2
----------------------------------------------------------------------- generated html file: file://C: ...
```

**Comment by mdmintz** [comment]
SeleniumBase comes with its own system for non-terminating checks called **deferred asserts**. From the [README](https://github.com/seleniumbase/SeleniumBase/blob/master/README.md):

<h3>🔵 How to use deferred asserts:</h3>

<p>Let's say you want to verify multiple different elements on a web page in a single test, but you don't want the test to fail until you verified several elements at once so that you don't have to rerun the test to find more missing elements on the same page. That's where deferred asserts come in. Here's an example:</p>

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class DeferredAssertTests(BaseCase):
    def test_deferred_asserts(self):
        self.open("https://xkcd.com/993/")
        self.wait_for_element("#comic")
        self.deferred_assert_element('img[alt="Brand Identity"]')
        self.deferred_assert_element('img[alt="Rocket Ship"]')  # Will Fail
        self.deferred_assert_element("#comicmap")
        self.deferred_assert_text("Fake Item", "ul.comicNav")  # Will Fail
        self.deferred_assert_text("Random", "ul.comicNav")
        self.deferred_assert_element('a[name="Super Fake !!!"]')  # Will Fail
        self.deferred_assert_exact_text("Brand Identity", "#ctitle")
        self.deferred_assert_exact_text("Fake Food", "#comic")  # Will Fail
        self.process_deferred_asserts()
```

<code translate="no">deferred_assert_element()</code> and <code translate="no">deferred_assert_text()</code> will save any exceptions that would be raised.
To flush out all the failed deferred asserts into a single exception, make sure to call <code translate="no">self.process_deferred_asserts()</code> at the end of your test method. If your test hits multiple pages, you can call <code translate="no">self.process_deferred_asserts()</code> before navigating to a new page so that the screenshot from your log files matches the URL where the deferred asserts were made.

Here's the output from running the example above:

```
***** DEFERRED ASSERTION FAILURES:
TEST: examples.test_deferred_asserts.DeferredAssertTests.test_deferred_asserts

DEFERRED ASSERT #2: (https://xkcd.com/993/) 
Element {img[alt="Rocket Ship"]} was not present after 0.6 seconds!

DEFERRED ASSERT #4: (https://xkcd.com/993/) 
Expected text substring {Fake Item} for {ul.comicNav} was not visible after 0.6 seconds!
(Actual string found was {|< < Prev Random Next > >|})

DEFERRED ASSERT #6: (https://xkcd.com/993/) 
Element {a[name="Super Fake !!!"]} was not present after 0.6 seconds!

DEFERRED ASSERT #8: (https://xkcd.com/993/) 
Expected exact text {Fake Food} for {#comic} was not visible after 0.6 seconds!
```

Here's a full list of methods related to SeleniumBase **deferred asserts**:

```python
self.deferred_assert_element(selector, by="css selector", timeout=None, fs=False)
self.deferred_assert_element_present(selector, by="css selector", timeout=None, fs=False)
self.deferred_assert_text(text, selector="html", by="css selector", timeout=None, fs=False)
self.deferred_assert_exact_text(
    text, selector="html", by="css selector", timeout=None, fs=False)
self.deferred_assert_non_empty_text(
    selector="html", by="css selector", timeout=None, fs=False)
self.deferred_check_window(
    name="default", level=0, baseline=False, check_domain=True, full_diff=False, fs=False)
self.process_deferred_asserts(print_only=False)
```

(The `fs` arg in those methods is the option to take a failure screenshot for those deferred asserts that fail.)

Given the superiority of SeleniumBase deferred asserts to pytest-check for browser automated testing, use the built-in **deferred assert** system instead.
