### ISSUE TITLE
Change parameter order for text related methods like assert_text

### ISSUE THREAD

**Issue by kvabapo** [seleniumbase/SeleniumBase#245]
Hello, I would like to request a more intuitive and standard way in ordering of parameters.

Problem: I was assuming that update_text and assert_text order of parameters were the same. Apparently not.

```
self.update_text(LoginPage.password, "password") # locator goes first then text
self.assert_text("Log In", LoginPage.login_button)  # text goes first then locator
```

Suggestion:
Make it a standard that locator goes first then the text or other parameters. I checked `base_case.py` and most methods follow the locator first.

**Comment by mdmintz** [comment]
Hi @kvabapo , backwards compatibility would drop to zero if I change that order now, but what I can do is make the second parameter optional in methods such as self.assert_text(text, selector) so that the selector defaults to "html" and therefore the assert would be simplified to checking the whole page. Eg:
``self.assert_text("Look for this text anywhere on the page!")``
as opposed to
``self.assert_text("Look for this text anywhere on the page!", "html")``

At least then the order serves a good purpose for those methods so that optional parameters come after required ones and don't have to be specified.

I'm currently working on https://github.com/seleniumbase/SeleniumBase/issues/244 , but I can get on this soon.

**Comment by mdmintz** [comment]
A new release is out: https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.17.6 (From pull request https://github.com/seleniumbase/SeleniumBase/pull/248)
This does not change parameter order (to preserve backwards compatibility), but it does make the selector optional for text-search methods (with it defaulting to "html") , which allows for some simplification of code. It might not avoid all confusion, but I consider it a fair compromise.

``self.assert_text(TEXT)`` can be used in place of ``self.assert_text(TEXT, "html")``
``self.is_text_visible(TEXT)`` can be used in place of ``self.is_text_visible(TEXT, "html")``
``self.wait_for_text(TEXT)`` can be used in place of ``self.wait_for_text(TEXT, "html")``

This simplification could not be possible if the selector was the first argument of the method.

Updating text and other selector-first methods remain unchanged, such as: ``self.update_text(SELECTOR, TEXT)``
