### ISSUE TITLE
error in base_case.py  when i build one of examples to exe 

### ISSUE THREAD

**Issue by Marwan0** [seleniumbase/SeleniumBase#2455]
when i build this code 
`from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class MyTestClass(BaseCase):
    def test_demo_site(self):
        self.open("https://seleniumbase.io/demo_page")
        self.type("#myTextInput", "This is Automated")
        self.click("#myButton")
        self.assert_element("tbody#tbodyId")
        self.assert_text("Automation Practice", "h3")
        self.click_link("SeleniumBase Demo Page")
        self.assert_exact_text("Demo Page", "h1")
        self.assert_no_js_errors()`

it give me this error 

Traceback (most recent call last):
  File "test.py", line 2, in <module>
  File "seleniumbase\fixtures\base_case.py", line 210, in main
  File "subprocess.py", line 347, in call
  File "subprocess.py", line 1204, in wait
  File "subprocess.py", line 1485, in _wait

I totally lost here, I have no idea what should be done

**Comment by mdmintz** [comment]
I ran the following script with `pytest` and it worked:

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class MyTestClass(BaseCase):
    def test_demo_site(self):
        self.open("https://seleniumbase.io/demo_page")
        self.type("#myTextInput", "This is Automated")
        self.click("#myButton")
        self.assert_element("tbody#tbodyId")
        self.assert_text("Automation Practice", "h3")
        self.click_link("SeleniumBase Demo Page")
        self.assert_exact_text("Demo Page", "h1")
        self.assert_no_js_errors()
```

If you're trying to convert a script to an executable file, then follow [PyInstaller](https://github.com/pyinstaller/pyinstaller) instructions.

For convenience, you may want to use one of the [SeleniumBase Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) that can be run with pure ``python``, instead of ``pytest``. For that, use the `SB()` format, which can use standard SeleniumBase APIs. ([See here for details on that format.](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_21))
