### ISSUE TITLE
UC Mode detected by Amazon but not not the second tab

### ISSUE THREAD

**Issue by carolhng** [seleniumbase/SeleniumBase#2474]
Hi, 
I am new user for Seleniumbase.
I tried out the code below:

from seleniumbase import  SB
with SB(uc=True) as sb:
    sb.driver.uc_open_with_reconnect("https://amazon.com", 5)       <-- Amazon displayed captcha

Then I tried this code:

from seleniumbase import  SB
import time

AMAZON = "https://www.amazon.com/dp/B0BDSM76W4"
with SB(uc=True) as sb:
    sb.driver.uc_open_with_tab(AMAZON)        <-- Amazon displayed captcha
    sb.driver.uc_open_with_tab(AMAZON)         <-- Success! No captcha
    time.sleep(10)

Why the second tab able to bypass bot detection?
Thank you

**Comment by mdmintz** [comment]
I'll explain why the following works on the second open:

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.driver.uc_open_with_tab("https://amazon.com")
    sb.driver.uc_open_with_tab("https://amazon.com")
    breakpoint()
```

It's because on the first one, the web browser has no history (empty `user_data_dir`, etc). Amazon has a special layer of security that **assumes** that **you might** be a bot if your web browser has never visited Amazon before. (They didn't actually detect Selenium when it first opened the URL.) That's why after you come back again (a few seconds) later, they stop making that assumption and then assume that **you might** be a human (because if you are, they don't want to lose a new potential customer). It's not much of a security layer... only the bots that give up too quickly will miss out!

**Comment by carolhng** [comment]
Thank you!
