### ISSUE TITLE
BUG: It will lunch 2 extra drivers  when the last time driver didn't quit or still has website existing 

### ISSUE THREAD

**Issue by dh12306** [seleniumbase/SeleniumBase#2485]
bug illustrates：
first, I used pycharm to kill the process ,but the driver still existed, and the website didn't close, as you see the Number 1 ,
then, I lunched again, so this time, there were 3 driver lunched ,2 were blank, the Number2 and Number 3,
![QQ截图20240212204032](https://github.com/seleniumbase/SeleniumBase/assets/20471681/08a45090-5ed7-4b74-a352-ff9615a65fcc)

lunch code is here , :
```
with SB(proxy=proxy,user_data_dir='xxx',extension_dir='xxx') as sb:
    try:
        sb.driver.get('google.com')
        time.sleep(1000)
    except:
        sb.quit()
```
so I traced the source code:
the first driver is lunched in browser_luncher.py, in line 3548, it failed,
the error is :
```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
```

so, is that to say，I cant lunch multi driver using one local_driver_path ？
can I set  the driver_path  param when using sb manger   ？ so I can lunch multi driver that are Not affecting each other 
can you help me ,thank you very much @mdmintz

**Comment by mdmintz** [comment]
This is line 3548 of `browser_launcher.py` currently:

https://github.com/seleniumbase/SeleniumBase/blob/e7ca0644be7e75ca039b89581acf475141fd0259/seleniumbase/core/browser_launcher.py#L3548

...which comes after: `except Exception as e:`.
So you might be using an old version of `seleniumbase`.

Also, in your example you had:

```python
sb.driver.get('google.com')
```

That would never work because `driver.get(URL)` expects a complete URL with the protocol, such as `https://google.com`.

You would have to do either:

```python
sb.driver.get("https://google.com")
# OR
sb.open("google.com")  # sb.open() allows a simplified URL
```

Also from your code, you have `sb.quit()`. There's no such method. There's an `sb.driver.quit()`, but you shouldn't need to use it anyway because the `driver` is quit automatically at the end of the `"with SB() as sb"` code block.

And it sounds like you mentioned something about launching multiple drivers at the same time. Multithreading is only supported via `pytest-xdist` (https://github.com/seleniumbase/SeleniumBase/issues/2006#issuecomment-1679789785), so you would need to switch to a format that supports that (using `seleniumbase.BaseCase` instead of `SB()`).

I tested `SB()` with `proxy`, `user_data_dir`, and `extension_dir` args at the same time without issue. Make sure you are using a valid proxy string, a valid user_data_dir, and a valid extension.

**Comment by dh12306** [comment]
> format

so nice of you,I will try more with BaseCase~~
