### ISSUE TITLE
Help - UC DevTools Detection and Brave Browser Usage

### ISSUE THREAD

**Issue by Jamal135** [seleniumbase/SeleniumBase#2491]
Default uc mode usage of seleniumbase fails Chrome DevTools Protocol Detection (CDP) through this detection test website: https://www.browserscan.net/en/bot-detection

Here is the relevant code used:

```python
from seleniumbase import Driver

driver = Driver(uc=True)
try:
    driver.get('https://www.browserscan.net/en/bot-detection')
    driver.sleep(500000)
finally:
    driver.quit()
```

Is there anyway to avoid this detection? 

Additionally, what would be the best way to specify the use of Brave? Driver accepts a binary path, though I don't want to specify the existing unclean binary I have - as this causes UC mode to fail to avoid cloudflare detection.

Would appreciate any advice on either of these issues. Have not found anything helpful in documentation (may have missed it).

**Comment by mdmintz** [comment]
This script works fine: (Replace `"breakpoint"` with a number of seconds when done debugging. The default `reconnect_time` might not have been high enough in your case.)

```python
from seleniumbase import Driver

driver = Driver(uc=True)
try:
    driver.uc_open_with_reconnect("https://www.browserscan.net/en/bot-detection", "breakpoint")
finally:
    driver.quit()
```

<img width="874" alt="Screenshot 2024-02-13 at 12 30 48 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/30577678-a222-4c93-8525-433c8da04ef2">

----

Also works on Brave if you specify the `binary_location`: (The one I used is specific to macOS default installation):

```python
from seleniumbase import Driver

driver = Driver(uc=True, binary_location="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser")
try:
    driver.uc_open_with_reconnect("https://www.browserscan.net/en/bot-detection", "breakpoint")
finally:
    driver.quit()
```

<img width="872" alt="Screenshot 2024-02-13 at 12 38 48 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/92c1f7f3-197c-415c-8ba4-33913b274e4b">

-----

With Brave, some websites will flag you just from using a Chromium browser that isn't Chrome or Edge, even if they can't detect that you're using an automation framework:

```python
from seleniumbase import Driver

driver = Driver(uc=True, binary_location="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser")
try:
    driver.uc_open_with_reconnect("https://pixelscan.net", "breakpoint")
finally:
    driver.quit()
```

<img width="1175" alt="Screenshot 2024-02-13 at 12 15 11 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/55aa28ff-6b63-423b-b08b-bf1abafc37c4">

There, they didn't detect Selenium, but since you were using Brave, they'll mention that your fingerprint might be masked. The same information appears if you manually visit that site using Brave.

**Comment by Jamal135** [comment]
Thank you very much @mdmintz hadn't seen the documentation around the usage of ``uc_open_with_reconnect`` so I will make sure to read into that further. Cheers.

**Comment by shupming** [comment]
How to achieve this using puppeteersharp or playwright?

**Comment by shupming** [comment]
![image](https://github.com/seleniumbase/SeleniumBase/assets/17714145/797ccc91-d582-4627-8a54-c67cda19f6b2)
![Uploading BB334541-4D53-49cd-908F-6FC69DDA37FC.png…]()

**Comment by mdmintz** [comment]
Here's an updated example for Brave with CDP Mode on macOS:

```python
from seleniumbase import SB

with SB(uc=True, binary_location="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser") as sb:
    url = "https://demo.fingerprint.com/playground"
    sb.activate_cdp_mode(url)
    sb.sleep(1)
    sb.cdp.highlight('a[href*="browser-bot-detection"]')
    bot_row_selector = 'table:contains("Bot") tr:nth-of-type(3)'
    print(sb.cdp.get_text(bot_row_selector))
    sb.cdp.assert_text("Bot Not detected", bot_row_selector)
    sb.cdp.highlight(bot_row_selector)
    sb.sleep(2)
```
