### ISSUE TITLE
how to init it from regular code

### ISSUE THREAD

**Issue by magneto2010** [seleniumbase/SeleniumBase#2506]
Hey I am new in python, i would glad you can help me to handle  seleniumbase in my project. Please read code from bottom to top. p.s. did not work well "tag code" for me so i placed screenshot, all imports done it is just example and sorry if i did it in a wrong place

![Screenshot 2024-02-17 at 3 31 09 PM](https://github.com/seleniumbase/SeleniumBase/assets/23360822/b54dbc9e-1931-444b-9270-7ce052c20058)

But it does not run well, I google and found same mistake https://github.com/seleniumbase/SeleniumBase/issues/814 but it is a little hard for me, because I have no classes in my code and I am not handle well class usage yet.  I would glad you can help me run seleniumbase-part in my code.

**Comment by mdmintz** [comment]
Study [SeleniumBase/help_docs/syntax_formats.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) - The syntax formats that use `BaseCase` or the `sb` `pytest` fixture are meant to be run with `pytest`, not `python` directly.

If you're looking to run scripts directly with `python`, use the `SB()` manager or the `Driver()` manager. Examples:

```python
from seleniumbase import SB

with SB() as sb:
    sb.open("https://seleniumbase.io/simple/login")
    sb.type("#username", "demo_user")
    sb.type("#password", "secret_pass")
    sb.click('a:contains("Sign in")')
    sb.assert_exact_text("Welcome!", "h1")
    sb.assert_element("img#image1")
    sb.highlight("#image1")
    sb.click_link("Sign out")
    sb.assert_text("signed out", "#top_message")
```

```python
from seleniumbase import Driver

driver = Driver()
try:
    driver.open("https://seleniumbase.github.io/demo_page")
    driver.highlight("h2")
    driver.type("#myTextInput", "Automation")
    driver.click("#checkBox1")
    driver.highlight("img", loops=6)
finally:
    driver.quit()
```

Here's a simple script to print all links from https://seleniumbase.io/:

```python
from seleniumbase import SB

def get_links_from_page(url):
    with SB() as sb:
        sb.open(url)
        return sb.get_unique_links()

links = get_links_from_page("https://seleniumbase.io/")
for link in links:
    print(link)
```

`SB()` takes a lot of options:
https://github.com/seleniumbase/SeleniumBase/blob/8cc37157809488b3b2c07f99436b9fda332c7e5e/seleniumbase/plugins/sb_manager.py#L30

If you just need to grab links and you don't need the full page to finish loading, try this: (Add `sjw=True, pls="none"` as options, which makes the script run faster because it doesn't wait for all page resources to be fully loaded before extracting the links.)

```python
from seleniumbase import SB

def get_links_from_page(url):
    with SB(sjw=True, pls="none") as sb:
        sb.open(url)
        return sb.get_unique_links()

links = get_links_from_page("https://seleniumbase.io/")
for link in links:
    print(link)
```

**Comment by magneto2010** [comment]
@mdmintz 
hey, how to deal with "get_current_link" and sb ?
I get <bound method BaseCase.get_current_url of <seleniumbase.fixtures.base_case.BaseCase testMethod=runTest>>
and I can not understand what does it mean. 
Is there a way to get url?
Thank you for your time.

**Comment by mdmintz** [comment]
I think you mean the`driver` variable: `driver.current_url`.

There's no such method: `get_current_link()` in SeleniumBase. (There is `self.get_current_url()` though.)

See the method summary: [help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md)
