### ISSUE TITLE
cant download files

### ISSUE THREAD

**Issue by imendars** [seleniumbase/SeleniumBase#2521]
Hi!

I cant download files anymore.
My SeleniumBase:
`driver = Driver( browser='chrome', headless2=False, incognito=True, agent=userAgent, do_not_track=True, uc=True, undetectable=True)`
I used to download with `driver.open(file_url)` , where i instantly give file url, but now that opens download location window where i have to click.
Now i try to use example, but i get error message from WebDriver
`driver.open(website)`
`driver.download_file(file_url, None)`
**WebDriverException: Message: You must enable downloads in order to work with downloadable files.**

Perhaps you can suggest what file to override so that i can force WebDriver to enable downloads? Or if i request download link instantly - how to force browser **not** to display download location?

**Comment by mdmintz** [comment]
There's a nice example of downloading files here: [examples/test_download_files.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_download_files.py)

You can also download a file directly via the URL: (`BaseCase` format using `self`, or using the `SB()`/`sb` format)

```python
self.download_file(url)
```

(Note that `driver.download_file` is different from `self.download_file` / `sb.download_file`)

It may be a good time to review the formats: [help_docs/syntax_formats.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) (because the raw `driver` format doesn't have all the methods of regular SeleniumBase).

If you run into any other issues, use the `SB()` format with UC Mode: (It can do more than the raw `Driver()` format.)

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.driver.uc_open_with_tab(URL)
    # ...
```
