### ISSUE TITLE
How to turn off a tab from opening as a new tab?

### ISSUE THREAD

**Issue by zxczxcdev** [seleniumbase/SeleniumBase#2564]
How to turn off a tab from opening as a new tab. For example, I have 2 tabs, when I press a button, a new tab will be displayed as a discord link. So how to turn off this tab?

Thanks admin

**Comment by mdmintz** [comment]
It sounds like you're talking about clicking on links that have `target="_blank"` in them.
(Only a guess, because you didn't provide any code).

Clicking on a link that has ``target="_blank"`` will open the link in a new tab. More info: https://www.w3schools.com/tags/att_a_target.asp

SeleniumBase gives you the ability to change the existing attributes of elements.
For example, the following line of code changes the `target` attribute of the given element:

```python
self.set_attribute('a[href="https://www.w3schools.com"]', "target", "_self")
```

Now, if that link is clicked, it will open the link the the current tab, rather than in a new one.

Next time, add code and debugging details to your questions if you want better answers.
