### ISSUE TITLE
How to change fonts in Seleniumbase Presenter?

### ISSUE THREAD

**Issue by asibhossen897** [seleniumbase/SeleniumBase#2769]
Hello there!
@mdmintz 
I'm trying to create some presentation that is in Bengali, but the Serif theme is not changing the Bengali font.
Is there any way to change the font to my preference?
Here is the code.

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class MyTestClass(BaseCase):
    def welcome_presentation(self):
        self.create_presentation(theme="serif", transition="fade")
        self.add_slide(
            "<h2>Python Essentials:</h2>\n"
            "<h3>Fundamentals and Practical Projects for Beginners</h3>\n"
            "<br /><hr /><br />\n"
            "<hd>Presented by <b>Asib Hossen</b></h4>\n"
            "<h4>Incieto Institute - 2024</h4>\n"
        )
        self.add_slide(
            "<h3>Assalamu'alaikum!</h3>\n"
            "<h3>Welcome to Incieto Institute!</h3>\n"
            "<h3>মডিউল ০ তে সবাইকে স্বাগতম!</h3>\n"
        )
        self.begin_presentation(filename="essentials.html")
```

**Comment by mdmintz** [comment]
Hello, the JS framework used for the presentations is Reveal.js - https://github.com/hakimel/reveal.js (specifically version 3.8.0: https://github.com/hakimel/reveal.js/releases/tag/3.8.0). The SeleniumBase Python code generates the Reveal.js code at runtime. If certain themes do not change the font for some languages, then it is out of SeleniumBase's control because all that is defined from within the Reveal.js library.

You can try the different themes and see if that helps:
"serif" (default), "sky", "white", "black", "simple", "league", "moon", "night", "beige", "blood", and "solarized".

**Comment by asibhossen897** [comment]
Thanks for the reply.
I'm also having some issue in my Ubuntu 24.04 LTS when trying to use Seleniumbase.
Even if I'm using --headed along with the command.

**Comment by mdmintz** [comment]
Use headless mode (`--headless`) to not see the browser window.
Make sure you specify a Python filename when saving the presentation.

**Comment by asibhossen897** [comment]
Ok, I'll try.
