### ISSUE TITLE
Disable download directory prompt when using selenium base

### ISSUE THREAD

**Issue by kiljag** [seleniumbase/SeleniumBase#2894]
Hi, 
I am trying to automate a download process using seleniumbase. I am able to automate all the steps till clicking the download button, but the chrome instance that got spawned is asking for download directory confirmation. I am on a mac and using latest chrome version and doing this non-headless mode. Is there a way to disable this prompt?

Here are the SB parameters.
`
with SB(uc=True, slow=True, incognito=True, headed=True) as sb:
`

Although, I can disable this in selenium by setting `download.prompt_for_download=False` in chrome options. Is there a way to do similar thing in selenium base.
Thank you.

**Comment by mdmintz** [comment]
It was already being set: https://github.com/seleniumbase/SeleniumBase/blob/1c526f1c02a9c7f4ec538d1600829acff44aa05e/seleniumbase/core/browser_launcher.py#L1037

And I also tried the `DownloadBubble` switches:
https://github.com/seleniumbase/SeleniumBase/blob/1c526f1c02a9c7f4ec538d1600829acff44aa05e/seleniumbase/core/browser_launcher.py#L1373-L1374

<b>The real issue is due to an external Chromium bug with incognito mode:</b> https://issues.chromium.org/issues/42323647

Lots of regular Chromium users have encountered it:

* https://issues.chromium.org/issues/324301023
* https://support.google.com/chrome/thread/238034785
* https://github.com/webdriverio/webdriverio/discussions/12191
* https://github.com/SeleniumHQ/selenium/issues/13104
* https://bugs.chromium.org/p/chromedriver/issues/detail?id=4619&no_tracker_redirect=1

The easiest way to bypass this issue is to avoid using incognito mode when you need to download files via clicking on links.

**Comment by SpicyCatGames** [comment]
@mdmintz unfortunately, this issue is present for me with selenium-base 4.33.2 even with incognito = False. Chrome 128.0.6613.85 64bit
