### ISSUE TITLE
where is the sb_config.js_checking_on?

### ISSUE THREAD

**Issue by adadale** [seleniumbase/SeleniumBase#294]
I checked the config folder，but i can't find the attributes like js_checking_on,ad_block_on.where are they?And amazingly,i focus on them in setUp method in base_case of the folder of fixture,it tells ”can't find declaration to go to ". But i can use them in programming.Thanks
        
            self.js_checking_on = sb_config.js_checking_on
            self.ad_block_on = sb_config.ad_block_on
            self.verify_delay = sb_config.verify_delay
            self.save_screenshot_after_test = sb_config.save_screenshot
            self.timeout_multiplier = sb_config.timeout_multiplier
            self.use_grid = False

**Comment by mdmintz** [comment]
@adadale "js_checking_on" is an internal switch to seleniumbase. It will tell tests to check for javascript errors when running tests if you add ``--check_js``. Example:
```
pytest my_first_test.py --check_js
```
(There are no javascript errors on that website, so it won't catch anything there, but if you run a test on a website page that has javascript errors on the page, it will fail the test.)

If you're interested in using the command line arguments, look inside https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/pytest_plugin.py instead of base_case.py . It will have the arguments that you're looking for. Some variables in base_case are for internal use to that file.

**Comment by adadale** [comment]
Thank you very much!!!❤️❤️
