### ISSUE TITLE
Detect cloudflare using its own method of bypassing

### ISSUE THREAD

**Issue by leo562** [seleniumbase/SeleniumBase#2946]
Hi, I apologize if I use my own method and not the built-in sb.uc_gui_click_captcha() . I have cloudflare detecting SeleniumBase if I use my own image crawling method! What could this be related to? . Code - 

-----------------------------------------------

``` import time
import pyautogui
import asyncio
from seleniumbase import SB


screenshot_path = 'click.png'

ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"

async def search_and_click():
    
    while True:
        try:
            location = pyautogui.locateOnScreen(screenshot_path, confidence=0.8)  
            if location:
                center = pyautogui.center(location)
                print(f"Found at: x={center.x}, y={center.y}")  
                
                
                pyautogui.moveTo(center.x, center.y, duration=1)  
                
                
                pyautogui.click()
                
                break  # Остановить цикл после успешного клика
        except pyautogui.ImageNotFoundException:
            pass
        await asyncio.sleep(1)  

def check_title_and_handle_captcha(sb):
    title = sb.driver.title
    print(f"Title: {title}")
    if "Just a moment" in title or "Один момент" in title:
        asyncio.run(search_and_click())  
        time.sleep(10)  
        check_title_and_handle_captcha(sb)  

with SB(uc=True, test=True) as sb:
    url = "https://nopecha.com/demo/cloudflare"
    sb.uc_open_with_reconnect(url, reconnect_time=9)
    
    time.sleep(3)  
    check_title_and_handle_captcha(sb)  

    sb.post_message("SeleniumBase wasn't detected", duration=3)
    
    
    cookies = sb.driver.get_cookies()
    cf_clearance_cookie = next((cookie for cookie in cookies if cookie['name'] == 'cf_clearance'), None)
    if cf_clearance_cookie:
        print(f"Cookie: cf_clearance={cf_clearance_cookie['value']}")
    else:
        print("cf_clearance cookie not found")
```
------------------------

here is a png - 
![click](https://github.com/user-attachments/assets/81fc84c8-deae-46f9-b38c-9aaec2064481)
.

**Thank you very much for your hard work!**

**Comment by mdmintz** [comment]
From the [UC Mode Documentation](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md):

👤 <b>What makes UC Mode work?</b>

Here are the 3 primary things that <b translate="no">UC Mode</b> does to make bots appear human:

<ul>
<li>Modifies <b><code translate="no">chromedriver</code></b> to rename <b translate="no">Chrome DevTools Console</b> variables.</li>
<li>Launches <b translate="no">Chrome</b> browsers before attaching <b><code translate="no">chromedriver</code></b> to them.</li>
<li>Disconnects <b><code translate="no">chromedriver</code></b> from <b translate="no">Chrome</b> during stealthy actions.</li>
</ul>

----

Your method did not disconnect <b><code translate="no">chromedriver</code></b> from <b translate="no">Chrome</b>.
That's one of the things that UC Mode methods do to avoid detection.

You can also call `sb.uc_open_with_disconnect(url)` so that the driver is disconnected in advance.
