### ISSUE TITLE
SB methods don't work with SeleniumGrid

### ISSUE THREAD

**Issue by ivanovevgeny** [seleniumbase/SeleniumBase#2970]
I ran selenium hub and 2 nodes locally regarding to [documentation](https://seleniumbase.io/seleniumbase/utilities/selenium_grid/ReadMe/) 

![image](https://github.com/user-attachments/assets/cc0c4ee0-b15d-4c8d-a96f-34780492a789)

Then tried the following code:

```
from seleniumbase import SB

url = "https://www.ozon.ru"
with SB(
        uc=True, 
        headless=False, 
        servername="127.0.0.1",
        port=4444
) as sb:
    sb.uc_open_with_reconnect(url, 3)
    sb.sleep(5)
```
and got an error: `'BaseCase' object has no attribute 'uc_open_with_reconnect'`
![image](https://github.com/user-attachments/assets/f57fa4b5-e986-4573-aaad-3b3a42fdbc7e)

If i run the code above without `servername` param, my app works fine.

Tried to use `Driver` and `get` method and it worked fine, but didn't wait for checking browser.

SB doesn't working with seleniumGrid or i misunderstand something?

Thank you in advance for your help.

**Comment by mdmintz** [comment]
As mentioned in https://github.com/seleniumbase/SeleniumBase/issues/2675#issuecomment-2047434434, "UC Mode is not compatible with the Grid".

There's lots of documentation on using SeleniumBase with a Selenium Grid ([SeleniumBase/seleniumbase/utilities/selenium_grid/ReadMe.md](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/utilities/selenium_grid/ReadMe.md) and [SeleniumBase/examples/capabilities](https://github.com/seleniumbase/SeleniumBase/tree/master/examples/capabilities))
but **you can't use UC Mode with the Grid**.

The original undetected-chromedriver doesn't support the Grid either:
https://github.com/search?q=repo%3Aultrafunkamsterdam%2Fundetected-chromedriver+grid&type=issues

Selenium Grid is a problem for UC Mode because while the Grid controls chromedriver, the Grid does not have the root control that is needed. UC Mode requires raw control for modifying a local chromedriver (renamed to uc_driver), as well as for disconnecting the driver from Chrome, and reconnecting to it a short time later. It's also not possible to control `pyautogui` remotely from the Grid. (Note that `pyautogui` is required for multiple UC Mode actions.)
