### ISSUE TITLE
Unable to click the CF captcha with uc_gui on cloudflare.com/login

### ISSUE THREAD

**Issue by D0kerj0int** [seleniumbase/SeleniumBase#3084]
I'm unable to click the cf captcha with uc_gui_handle_captcha() or uc_gui_click_captcha() on their login page. It goes undetected and passes with manual click, everything else works perfect. I've tried the steam and other similar examples which work fine also. 

Using SB > 4.30.1 

Are you able to pass the captcha on that url ? Appreciate your work! 

from seleniumbase import SB

def test_cloudflare_login():
    with SB(uc=True, incognito=True) as sb:
        url = "https://www.cloudflare.com/login"
        sb.uc_open_with_reconnect(url, 12)
        sb.sleep(4)
        sb.uc_gui_handle_captcha()
        sb.sleep(10)

**Comment by nicq10** [comment]
having the same issue

**Comment by mdmintz** [comment]
@D0kerj0int It looks like the CF CAPTCHA on cloudflare.com/login is different than the one they give to customers. It might be a beta version that will possibly be rolled out to customers soon. I'll prepare an update so that I can preemptively make UC Mode work for the rollout (and also work on the beta version they're using themselves).

@nicq10 That `uc_gui_click_captcha()` method is essential to use now. It was the highlight of of my 3rd "Undetectable Automation" video on YouTube: https://www.youtube.com/watch?v=-EpZlhGWo9k

**Comment by mdmintz** [comment]
This was resolved in `4.30.2` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.30.2

**Comment by D0kerj0int** [comment]
Hey @mdmintz, are you still able to pass the login with the new cf_test? I updated to 4.30.2 and the test won't pass for me with gui_click or gui_handle, visiting https://seleniumbase.io/apps/turnstile passes fine. I'm on mac but can try windows later on. Thanks man you rock!

**Comment by D0kerj0int** [comment]
Anyone able to pass this test? https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_cf.py

**Comment by mdmintz** [comment]
Both tests in there are working for me. For slow internet connections, make sure to increase the `reconnect_time`. If the `reconnect_time` is less than the time it takes for the page to finish loading, you'll be detected.
