### ISSUE TITLE
Timed out and Disconnected Error only on Mac OS (sometimes)

### ISSUE THREAD

**Issue by thomvas** [seleniumbase/SeleniumBase#3119]
Hi,

my code is this:

```
from seleniumbase import Driver

driver = Driver(uc=True, block_images=True, headless2=True, agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36", chromium_arg="--disable-extensions, --disable-search-engine-choice-screen, --disable-dev-shm-usage")

url = "https://www.amazon.com/"

driver.uc_open(url)
```

On Linux and Windows no problems, but on Mac OS **only sometimes**, not always, I get these errors:

1) Message: disconnected: not connected to DevTools

2) Timed out receiving message from renderer: 300.000

How can i solve this? Thanks

**P.S. I starred this repository, it's amazing!** :)

![error1](https://github.com/user-attachments/assets/b325d6c0-61e4-4ce6-929b-e942210ef490)
![error2](https://github.com/user-attachments/assets/01559a5f-9907-4103-b7f9-7c07b7fa868b)

**Comment by mdmintz** [comment]
Hello. It looks like you're calling `chromium_arg` with args that are already being set:

https://github.com/seleniumbase/SeleniumBase/blob/5212bdb755cf88b7f18980a03425ea725d9f693c/seleniumbase/core/browser_launcher.py#L1813

https://github.com/seleniumbase/SeleniumBase/blob/5212bdb755cf88b7f18980a03425ea725d9f693c/seleniumbase/core/browser_launcher.py#L1863

(Setting the same arg multiple times can lead to issues.)

Using `--disable-extensions` in `chromium_arg` breaks SeleniumBase features, so you probably don't want to use that.

Ever since UC Mode started depending on `PyAutoGUI` for CAPTCHA clicks, combining Headless Mode with UC Mode has been unsupported. You also don't need Headless Mode on Linux anymore because `SB(uc=True, xvfb=True)` comes with a special virtual display. Even if using the `Driver()` format, you can create your own virtual display. Eg.

```python
from sbvirtualdisplay import Display
from seleniumbase import Driver
import os

display = Display(visible=True, size=(1366, 768), backend="xvfb", use_xauth=True)
display.start()
os.environ["DISPLAY"] = f":{display.display}"

driver = Driver(uc=True, headed=True)
# ...
driver.quit()

display.stop()
```

Also, UC Mode gives you an optimal User Agent by default, which means you probably don't want to change it unless the goal is to be detected. Change it at your own risk if you know what you're doing.

Using `block_images=True` will make you detectable (https://github.com/seleniumbase/SeleniumBase/discussions/2198#discussioncomment-7320782), so you shouldn't be using it with UC Mode. Also, that just sets `prefs["profile.managed_default_content_settings.images"] = 2`. There are definitely issues with it, but the code is not part of SeleniumBase, so I can't do anything about it if it causes issues. (All SeleniumBase does is enable that switch via `profile.managed_default_content_settings.images`.)

Hope that helps!

**Comment by thomvas** [comment]
Thanks, i corrected and tested the code:

```
from seleniumbase import Driver

driver = Driver(uc=True, block_images=True, headless2=True, agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36")

url = "https://www.amazon.com/"

driver.uc_open(url)
```

Only on Mac I still get the error randomly. The problem is only on Mac (No windows, No Linux), i captured a screenshot of the headless driver and show this error, after "Message: disconnected: not connected to DevTools" on terminal.

![driver error1](https://github.com/user-attachments/assets/2461d30a-eace-472b-b50b-6e2e442083ed)


Maybe there are some tests that i can do for resolve it? Maybe some improve to my code for mac system?

Thanks!

**Comment by mdmintz** [comment]
It looks like you're still:
* Blocking images with `block_images=True`. (This can lead to issues and shouldn't be used with UC Mode)
* Using Headless with UC Mode (Not supported if you want to remain undetected)
* Changing the Default User Agent (This can make you detectable. The default one is good.)
