### ISSUE TITLE
UC, Headless Not Able to Bypass Cloudfare in Linux Server

### ISSUE THREAD

**Issue by SanketBaraiya** [seleniumbase/SeleniumBase#3181]
Hii team, the below piece of code works perfectly on windows but it is not working in Ubuntu Linux Server:
```
from seleniumbase import Driver
from bs4 import BeautifulSoup

driver = Driver(uc=True, headless=True)
driver.get("https://uk.newonnetflix.info/")
driver.sleep(25)

soup = BeautifulSoup(driver.page_source, 'html.parser')

driver.close()
```

I would really appreciate some help on this.

Thanks

**Comment by mdmintz** [comment]
On Linux, use `with SB(uc=True, xvfb=True) as sb:` instead of using headless mode or the `Driver()` format.

```python
from seleniumbase import SB

with SB(uc=True, xvfb=True) as sb:
    sb.activate_cdp_mode(url)
    sb.solve_captcha()
```

(Use `sb.driver` to access the `driver` after calling `sb.connect()` to reconnect the `driver`.)

UC Mode is detectable in regular Headless Mode, and special methods that use `PyAutoGUI` won't work at all in Headless Mode. (Also, the `Driver()` format doesn't include the `xvfb` option.)

Xvfb is a special virtual display for Linux machines, which lets you run a regular headed browser on a machine that does not have a GUI interface.

**Comment by SanketBaraiya** [comment]
Hi @mdmintz,

The xfvb=True was giving as error saying unexpected argument in driver:
![image](https://github.com/user-attachments/assets/841bf09f-f8aa-4532-8ef7-4bf7ef286aed)



I upgraded to GUI Ubuntu this my code now:
```
from seleniumbase import Driver
from bs4 import BeautifulSoup

driver = Driver(uc=True)
driver.get("https://uk.newonnetflix.info/")
driver.sleep(25)

soup = BeautifulSoup(driver.page_source, 'html.parser')

driver.close()
```
And still it is not able to perform as it does in windows it stucks here:

![image](https://github.com/user-attachments/assets/93d07a49-d488-49d5-83f5-dbd24f682f6a)

**Comment by SanketBaraiya** [comment]
Hii @mdmintz ,

I tried your recommended code but still I am not able to execute the code, Also FYI I upgraded to GUI version and i am using the below code now:
```
from seleniumbase import SB

with SB(uc=True) as sb:
    url="https://uk.newonnetflix.info/"
    sb.uc_open_with_reconnect(url)
    sb.uc_gui_click_captcha()

print("Done")
```
This is what happening it is stuck here:
![image](https://github.com/user-attachments/assets/336746a0-35c9-484a-bd96-f51a0033dbe6)

**Comment by mdmintz** [comment]
For Linux machines that have a GUI, use `headed=True` so that it spins up a headed browser.
