### ISSUE TITLE
Is there any possibility of decoupling from unittest.testcase?

### ISSUE THREAD

**Issue by symonk** [seleniumbase/SeleniumBase#337]
As I am sure you know, extending from unittest.testcase renders a lot of pytest functionality unusable,  primarily pytest parameterized (you can get around this with another plugin) however you cannot utilize fixtures properly when using seleniumbase and classes for tests. 

- How much work would be involved in decoupling?
- Is it even remotely viable?

unless you know of any way to use fixtures when having a pytest runner and actually yielding/returning values from them ?

**Comment by mdmintz** [comment]
Hi @symonk There are workarounds for any limitations I’ve seen, such as with using “parameterized” https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py  . I’ve created several examples demonstrating these workarounds. Most pytest functionality should still work normally. You can also pass custom arguments on the command line. SeleniumBase’s BaseCase inherits all of unittest’s TestCase. It is tightly linked, and cannot be removed without destroying most of the SeleniumBase code. It would also break backwards compatibility, which must be maintained because SeleniumBase has many users expecting all their scripts to continue working after every upgrade. If you can explain your difficulties with fixtures, I can help you find a workaround.

**Comment by symonk** [comment]
yeah I understand, however the biggest limitation is the inability to use fixtures in test methods that aren't autouse and that yield/return a value, its simply not possible?

**Comment by mdmintz** [comment]
Can you provide a very specific use case for this? I’m trying to understand a testing scenario where you need a fixture to return a value that can’t be accomplished with a normal Python method or built-in SeleniumBase functionality. SeleniumBase has its own built-in fixtures and the ability to customize command-line input to give your tests/scripts specific behavior as needed.

**Comment by symonk** [comment]
have you got any examples of using a fixture to inject a return value into a test using seleniumbase? you cannot pass fixtures directly into tests when unittest.testcase is used, @autouse=True (sure but theres no return/yielded values)

**Comment by mdmintz** [comment]
There’s a hack you can do to get tests to return anything. Look at https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_parameter_script.py 
You can even run tests with pure Python (without pytest). You’ll have to make a few modifications to that model, and setup is more complicated because the required arguments must be declared directly, but then you can wrap it in pure pytest and use whatever fixtures you want.

**Comment by mdmintz** [comment]
@symonk See some of the new formats for this:

```python
"""Context Manager Test. Runs with "python". (pytest not needed)."""
from seleniumbase import SB

with SB() as sb:  # By default, browser="chrome" if not set.
    sb.open("https://seleniumbase.io/realworld/login")
    sb.type("#username", "demo_user")
    sb.type("#password", "secret_pass")
    sb.enter_mfa_code("#totpcode", "GAXG2MTEOR3DMMDG")  # 6-digit
    sb.assert_text("Welcome!", "h1")
    sb.highlight("img#image1")  # A fancier assert_element() call
    sb.click('a:contains("This Page")')  # Use :contains() on any tag
    sb.click_link("Sign out")  # Link must be "a" tag. Not "button".
    sb.assert_element('a:contains("Sign in")')
    sb.assert_exact_text("You have been signed out!", "#top_message")
```

Also see: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md
