### ISSUE TITLE
pytest.mark.parametrize is broken

### ISSUE THREAD

**Issue by frafra** [seleniumbase/SeleniumBase#395]
`pytest.mark.parametrize` works with pytest:

```python3
import pytest
class TestParametrized:
    @pytest.mark.parametrize('value', [0, 1])
    def test(self, value):
        pass
```

...but it doesn't with seleniumbase:
```python3
from seleniumbase import BaseCase
import pytest
class TestParametrized(BaseCase):
    @pytest.mark.parametrize('value', [0, 1])
    def test(self, value):
        pass
```

Error message:
```
[...]
                with outcome.testPartExecutor(self, isTest=True):
>                   testMethod()
E                   TypeError: test() missing 1 required positional argument: 'value'

/usr/lib64/python3.7/unittest/case.py:628: TypeError
```

**Comment by mdmintz** [comment]
@frafra See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py which lets you parameterize tests with the “parameterized” package.

**Comment by mdmintz** [comment]
@frafra To invoke pytest fixtures directly, such as pytest.mark.parameterize, see this example:

```python
import pytest


@pytest.mark.parametrize('value', ["pytest", "selenium"])
def test_sb_fixture_with_no_class(sb, value):
    sb.open("https://google.com/ncr")
    sb.update_text('input[title="Search"]', value + '\n')
    sb.assert_text(value, "div#center_col")


class Test_SB_Fixture():
    @pytest.mark.parametrize('value', ["pytest", "selenium"])
    def test_sb_fixture_inside_class(self, sb, value):
        sb.open("https://google.com/ncr")
        sb.update_text('input[title="Search"]', value + '\n')
        sb.assert_text(value, "div#center_col")
```

Its uses seleniumbase as a fixture to allow the use of any pytest fixture. (``sb`` fixture)

**Comment by mdmintz** [comment]
Here's an example of correct pytest.mark.parameterize usage with SeleniumBase:
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_pytest_parameterize.py

**Comment by frafra** [comment]
Thank you :-) but `pytest.mark.parameterize` does not work with Seleniumbase if you decorate a function inside a class, as my first comment tried to show.

**Comment by mdmintz** [comment]
@frafra That's due to a bug with pytest itself. See https://github.com/pytest-dev/pytest/issues/541 I've created a few different workarounds: 1, by using the ``parameterized`` package; and 2, by creating the ``sb`` fixture for ``seleniumbase``, which passes the ``unittest.TestCase`` class as a fixture into ``pytest`` tests. Without these workarounds, the issue needs to be corrected on the ``pytest``side, and the maintainers of that probably could fix it if they look how I passed all of ``seleniumbase``'s ``unittest.TestCase`` methods through the fixture, instead of a direct class import.
