### ISSUE TITLE
Hello, do not know why this report error?

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#402]

**Comment by meilisong1** [comment]
class CusBaseCase(BaseCase):
	# def __init__(self, *args, **kwargs):
	# 	self.page = Page("element")
	# 	super(CusBaseCase, self).__init__(*args, **kwargs)

	def setUpClass(self):
		super(CusBaseCase, self).setUpClass()
		logger.info("-------")
-----

 @pytest.fixture(scope=scope, autouse=True)
    def fixture(self, request):
        if getattr(self, "__unittest_skip__", None):
            reason = self.__unittest_skip_why__
            pytest.skip(reason)
        if setup is not None:
            if pass_self:
                setup(self, request.function)
            else:
>               setup()
E               TypeError: setUpClass() missing 1 required positional argument: 'self'

**Comment by mdmintz** [comment]
Hi @meilisong1 , in order to use pytest fixtures with SeleniumBase, you need to pass the BaseCase class as a fixture. See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_sb_fixture.py for an example. This is due to compatibility between pytest and unittest’s TestCase class (which SeleniumBase uses).

**Comment by meilisong1** [comment]
Thank you. Solved
