### ISSUE TITLE
Hello, due to the project, the login frequency is limited, so I can't log in frequently. At present, I think every testcase will close the browser, is there any way not to close it every time, or set the bypass through cookies?

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#404]

**Comment by mdmintz** [comment]
If you set the “--user-data-dir=DIR_NAME” command line argument when using Chrome, you can save cookies and session info between tests with Chrome’s user data directory. Then you would only need to login once, assuming you stay logged in. Otherwise, put everything in a single test, because the browser window will close at the end of each test.

**Comment by meilisong1** [comment]
Hey hey, do you have a specific example, I did not try to succeed

**Comment by mdmintz** [comment]
``pytest my_first_test.py --user-data-dir="user_dir"``
After running that, you'll see that ``user_dir`` has been created. It saves the session info and state. If you logged into a website, the session info would get saved, and if you reran the test using that data directory again, you would still be logged in to the sites you logged into, assuming you never logged out. (You'll have to create a different test that logs into a site, because that specific test does not log in.)

**Comment by meilisong1** [comment]
Thank you. I'll try. Close it first

**Comment by mdmintz** [comment]
There's also the pytest option: ``--rs`` to reuse the browser session between tests.
