### ISSUE TITLE
Questions about the click function

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#423]
self.click_visible_elements("//*[contains(text(),'添加星标')]")  --ok

self.click("//*[contains(text(),'添加星标')]")  --failed

Why not just change click to click visible elements, The above example fails to use click directly. Click_visible_elements is ok, It is recommended that click be changed to a click on a visible element.

**Comment by meilisong1** [comment]
> self.click_visible_elements("//*[contains(text(),'添加星标')]") --ok
> 
> self.click("//*[contains(text(),'添加星标')]") --failed
> 
> Why not just change click to click visible elements, The above example fails to use click directly. Click_visible_elements is ok, It is recommended that click be changed to a click on a visible element.

The original plan was put into use in the project, if not stable, it is estimated to re-encapsulate itself

**Comment by mdmintz** [comment]
``self.click()`` is going to find the first matching selector, and then click on it. If ``self.click_visible_elements()`` works, but ``self.click()`` fails, it means that multiple matches exist, and that the first match is not in a visible state. To make ``self.click()`` work in your case, you have to make your selector more specific so that it finds only that element. That's also the reason for ``self.click_visible_elements()`` -> so that it only tries to click the visible ones (and it can perform more than one click if multiple matches exist).

**Comment by meilisong1** [comment]
> `self.click()` is going to find the first matching selector, and then click on it. If `self.click_visible_elements()` works, but `self.click()` fails, it means that multiple matches exist, and that the first match is not in a visible state. To make `self.click()` work in your case, you have to make your selector more specific so that it finds only that element. That's also the reason for `self.click_visible_elements()` -> so that it only tries to click the visible ones (and it can perform more than one click if multiple matches exist).

Ok, I have tried many times, it should be the problem of our web page, our web page is embedded, maybe for compatibility, some elements are not visible, thank god
