### ISSUE TITLE
It is not recommended to close the browser every time a testcase is executed

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#434]
I mentioned this requirement last time, but encapsulating all cases into functions in a testcase will be treated as a case, which is not a good feeling. This requirement is quite normal, so I suggest you optimize it,thx

The login area is too time-consuming, and our project has increased intelligent validation to limit the number of logins, which can be time-consuming once the use cases multiply

Or can you give me directions, where to change the source code, I try to change to see

**Comment by mdmintz** [comment]
@meilisong1 See https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.33.9
### Add an option to reuse the browser session between tests
* Usage:
``--reuse_session`` or ``--reuse-session``
This will keep the main browser window open between ``pytest`` tests so that the Selenium session can be shared from one test to another. (This feature may be useful in some cases, such as tests that require logging in every time: With this feature enabled, SeleniumBase tests would only need to login once, because the session would be kept into the next test.)

* Also update some Python dependencies:
``setuptools``, ``certifi``, ``pygments``, ``tqdm``
* Also update default timeout values when using the SeleniumBase Selenium Grid.
