### ISSUE TITLE
A technical question

### ISSUE THREAD

**Issue by LucasDurian** [seleniumbase/SeleniumBase#468]
As we all known, the webdriver should fit our browser version, I tried to set the path of a chrome_webdriver that was created by the command "sleleniumbase install chromedirver" , however it doesn`t work. I don`t why, could you please tell me the reason.

**Comment by mdmintz** [comment]
Hi @LucasDurian Since it's difficult to tell which version of Chrome is already installed on the user's system, I have made the ``seleniumbase install chromdriver [VERSION]`` command flexible. If no version is specified, it will install chromedriver 2.44 for compatibility reasons, as that's the last version that doesn't expect a specific Chrome version to be installed. You can also specify a version to install specifically, or you can use ``latest`` to install the latest version.
```
seleniumbase install chromedriver
seleniumbase install chromedriver 76.0.3809.126
seleniumbase install chromedriver latest
```
Chromedriver 2.44 is somewhat magical, as it somehow works even with today's latest version of Chrome. Due to Chrome's tendency to auto-update, using one of the newer versions of Chromedriver may lead to issues, as these newer version check the version of Chrome running as it starts up, and if the range isn't exactly in its allowed range, there may be errors. Due to these reasons, it's safer to stay with 2.44, unless you either prevent Chrome from auto-updating, or you can run ``seleniumbase install chromedriver latest`` every time it does.

**Comment by LucasDurian** [comment]
@mdmintz Thanks a lot~!
