### ISSUE TITLE
--log_path option does not take effect

### ISSUE THREAD

**Issue by cjydayang** [seleniumbase/SeleniumBase#486]
Hi， @mdmintz ：
I noticed this change in v1.34.24 ：
https://github.com/seleniumbase/SeleniumBase/commit/5c9694035203c47d9842e62d50ac3034bb6c7597
 sb_config.log_path = 'latest_logs/'  # (No longer editable!)

is this means the --log_path option will not take effect？What is the reason for this change？

**Comment by mdmintz** [comment]
Hi @cjydayang I changed this for safety. Since the ``latest_logs/`` folder is cleaned out every time unless ``--archive-logs`` is set, I don't want someone to accidently set the logs folder to an important location on the file system. If it stays as ``latest_logs/``, users won't be able to accidently change the location to an important folder and delete the contents inside.

**Comment by mdmintz** [comment]
If someone really wanted the logs location to be different, they could fork/clone the repo and make the changes they wanted. But not from the command line with an unchanged version of SeleniumBase.

**Comment by cjydayang** [comment]
@mdmintz thank you for your reply ，Although I think edit log path is necessary in some cases and someone should take responsibility for their actions if they edit log path, I still agree with you
