### ISSUE TITLE
How to use a function with @parameterized.expand?

### ISSUE THREAD

**Issue by createNull** [seleniumbase/SeleniumBase#517]
Hi, 

I want to parametrise a test and I would like to have a function call as an argument instead of a hardcoded element.
I've seen some examples using @pytest.mark.parametrize, but I can't get my head around this time.

This is my code:
```
    @parameterized.expand([(0, 'test_name', None, 'disabled'),
                           (get_random_location, '', None, 'disabled'),
                           (57, 'test_name', None, 'enabled'),
                           (1, 'test_name', '', 'disabled'),
                           (1, '', 'test_another_name', 'disabled'),
                           (1, 'test_name', 'test_another_name', 'enabled')])
```
In line 3, I want to use `get_random_location` function as well instead of the hardcoded value `57`.
Probably I would need to create a fixture in my `BaseTestCase` class while my tests are in `TestSuite` class which inherits the previous one.

To make it easier, I tried to place the function in the `TestSuite` class as a fixture:
```
@fixture
    def get_random_location(self):
        # my function body here
```
but it results in an error:
`FAILED WANP/selenium_tests/test_suite.py::TestSuite::test_letter_button_1 - TypeError: %d format: a number is required, not function
`

Do you have any idea how could I accomplish this?

**Comment by mdmintz** [comment]
Hi @createNull , here's an example of parameterization in SeleniumBase done the usual way: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py , however, since you want to use Pytest fixtures, you'll have to use SeleniumBase as a fixture, and here's the example for of that: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_pytest_parametrize.py

**Comment by createNull** [comment]
I am aware of both of these examples, but unfortunately none of them is helping me.
Don't need to use a pytest fixture, that was only an example from my side.

Imagine that https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py on line 8 instead of having the string "pypi", you would need to use a function that generates that string. 

How would you accomplish that?
This is my question

**Comment by mdmintz** [comment]
@createNull 
Here's a example of that:
```python
from seleniumbase import BaseCase
from parameterized import parameterized


def get_pipi_url():
    return "pypi.org"

class GoogleTestClass(BaseCase):

    @parameterized.expand([
        ["pypi", get_pipi_url()],
    ])
    def test_parameterized_google_search(self, search_term, expected_text):
        self.open('https://google.com/ncr')
        self.update_text('input[title="Search"]', search_term + '\n')
        self.assert_text(expected_text, '#search')
```

**Comment by createNull** [comment]
Never thought to try this one since my method is inside the class:
`class GoogleTestClass(BaseCase):
    def get_pipi_url(self):
        return "pypi.org"

    @parameterized.expand([
        ["pypi", get_pipi_url()],
    ])
    def test_parameterized_google_search(self, search_term, expected_text):
        self.open('https://google.com/ncr')
        self.update_text('input[title="Search"]', search_term + '\n')
        self.assert_text(expected_text, '#search')`

Trying to call `get_pipi_url()`, `self.get_pipi_url()` or `get_pipi_url(self)` won't work, so that's why I assumed a fixture is needed in this situation.

An example on how to implement this would be much appreciated!

**Comment by mdmintz** [comment]
@createNull , since ``parameterized.expand`` is not inside a method, you don't have access to ``self``, and therefore methods that you call inside the ``parameterized.expand`` must exist outside the class. Maybe there's another way, but at that point you should try looking at https://github.com/wolever/parameterized , as that's the tool you're using, and SeleniumBase does not own it. SeleniumBase only uses it.
