### ISSUE TITLE
About @ pytest.fixture

### ISSUE THREAD

**Issue by SubePython** [seleniumbase/SeleniumBase#553]
Hello, I'm a Xiaobai. I have a question. Please help me out:

Now I need to use @ pytest. Fixture() to define my web login in confitest.py, but it seems that it can't be used in the class. How can I solve this problem

**Comment by mdmintz** [comment]
@SubePython There's a special format for using fixtures with SeleniumBase. You'll need to use SeleniumBase as a fixture. Here are examples: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_sb_fixture.py
Also by default, conftest is disabled because it may override the pytest plugin where SeleniumBase fixtures are defined, but if you are aware of that, you can go to your local version of https://github.com/seleniumbase/SeleniumBase/blob/master/pytest.ini from your clone of SeleniumBase and remove the part that says ``--ignore conftest.py``.
The standard way to do reusable methods in SeleniumBase such as login() is to put those methods in a parent class that inherits BaseCase. See https://github.com/seleniumbase/SeleniumBase/tree/master/examples/boilerplates for details, where you will find https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py , where a login() method is defined, and https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/boilerplate_test.py , where the login method is used.

**Comment by SubePython** [comment]
That's a good idea, thank you
