### ISSUE TITLE
May use contains to find a element

### ISSUE THREAD

**Issue by wagnermduarte** [seleniumbase/SeleniumBase#558]
Hello,
Congrats about this job, is awesome.

I want to ask about use contains to find elements? Is it all ready done? or you mind to do a thing similar?

sorry about my rusty english...

**Comment by mdmintz** [comment]
@wagnermduarte  There's ``self.click_link_text(TEXT)`` and ``self.click_partial_link_text(TEXT)`` that you can use instead of ``contains`` in a selector.
Here's an xpath example of it: ``self.click('//a[contains(text(),"Button")]')``
You may want to check out https://github.com/seleniumbase/SeleniumBase/blob/ed68e3e0ad710e77e8de64f0bea04966aae9f818/help_docs/method_summary.md to see all available methods.
