### ISSUE TITLE
setUp method with not able to set fixture scope session

### ISSUE THREAD

**Issue by teamdts** [seleniumbase/SeleniumBase#569]
hello
i want to use login method only one time for all test cases.
so i am trying to set fixture for setup or login related my test case.

but not able to set it.

how i can implement 
https://www.seleniumeasy.com/python/pytest-run-webdriver-tests-in-parallel

thing on our below function 
```
def setUp(self):
   super(BaseCase,self).setUp()
```
can u please help me to resolve this issue ?
or if anything in your architecture related that 
Thanks

**Comment by mdmintz** [comment]
Hi @teamdts , there is the cmd option ``--reuse-session``, which will allow you to reuse the same browser session for all tests. If you're going for one login for all tests, use the pytest marker line:
``@pytest.mark.run(order=1)``
on your first test that does login so that it only happens once.
You also mention multi-threading, which means you'll need to perform the login once per shared-session thread, as opposed to just once total. If you have a method that checks whether login has already occurred, you can call login only when you need it.

This test has an example of pytest method ordering: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/swag_labs_suite.py
This doc includes useful CMD options such as ``--reuse-session``: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/customizing_test_runs.md

**Comment by teamdts** [comment]
hi @mdmintz 
i have already tried before `--reuse-session` and now also try after your suggetion.
but not worked.

**Comment by teamdts** [comment]
@mdmintz 
thanks it is worked as per below method but is is fine to me now.
1. in each test case need to just open url again (my expectation no need to open url again)
2 each test case in automayic reoping browser (my expectation is on same browser all test case executed)

but now it is fine to me.

**Comment by mdmintz** [comment]
Great! Sounds like it's working for you now. Let me know if you have anymore questions.

**Comment by teamdts** [comment]
thanks @mdmintz for your valuable help
its enough now.
