### ISSUE TITLE
Overrides SeleniumBase settings how to add new parameter in overrided file

### ISSUE THREAD

**Issue by teamdts** [seleniumbase/SeleniumBase#576]
hello i want to override default settings.py file and want to add more Timeout variables
`--settings-file=FILE  # (Overrides SeleniumBase settings.py values.)`

so after adding `MICRO_TIMEOUT` parameter how i can use ?
i have tried by adding but it is giving below error

```
AttributeError: module 'seleniumbase.config.settings' has no attribute 'MICRO_TIMEOUT'
```

Thanks

**Comment by mdmintz** [comment]
@teamdts You can't change where the timeouts are used. Those are already built into the code. You can however change their default values. And 99% of the time, you should probably leave the default timeouts as is, because you can always change the timeout when calling a SeleniumBase method that has a timeout parameter.

**Comment by teamdts** [comment]
ok.
thanks
