### ISSUE TITLE
Feature : seleniumbase driver auto download based on browser stable current version

### ISSUE THREAD

**Issue by teamdts** [seleniumbase/SeleniumBase#587]
hello
right now getting issue like i have prepared docker file and in that google stable version is 81.
and using salenium latest it is installing version  83.

so both are mismatch.

so according that suggetion is if something like salenium base read version of browser version and based on that download perticular match driver so it will be good.

Thanks

**Comment by mdmintz** [comment]
Detecting the current version of Chrome installed using Python has proven to be tricky. And if Chrome auto-updates, it could break existing tests. That's why there's a very specific version of ChromeDriver downloaded when using ``seleniumbase install chromedriver`` -> it's one that works with any version of Chrome. There's still the option of using ``seleniumbase install chromedriver latest`` to get the latest version of ChromeDriver if needed, as well as ``seleniumbase install chromedriver VERSION`` to get a specific version of Chromedriver.

**Comment by mdmintz** [comment]
The SeleniumBase Driver Manager (now a few years old) takes care of making sure your driver version matches your browser version.
