### ISSUE TITLE
Running with --demo should automatically activate --gui

### ISSUE THREAD

**Issue by dimaspivak** [seleniumbase/SeleniumBase#671]
As it stands, running tests in demo mode also requires passing `--gui`. Would a patch that uses the inclusion of `--demo` on the command line as reason to activate `--gui` be accepted?

**Comment by mdmintz** [comment]
Hi @dimaspivak, ``--gui`` is the default mode for non-Linux machines. Since Linux machines are mostly headless, ``--headless`` is the default mode for that. Are you running tests on a headed Linux machine? That's the only scenario I see where you might need that option. I don't necessarily want ``--gui`` enabled when using demo mode, because I test demo mode on headless CI machines, so in my case, I wouldn't want ``--gui`` to get switched on automatically when ``--demo`` is used.

**Comment by dimaspivak** [comment]
Ah, fair enough. I didn't think folks would ever run `--demo` in a headless environment (since they'd be pausing between steps but not seeing anything), so I had just assumed it was designed solely for folks running in GUI mode. Thanks for the clarification.
