### ISSUE TITLE
Am I missing a way to close a window created by self.open_new_window?

### ISSUE THREAD

**Issue by bschollnick** [seleniumbase/SeleniumBase#704]
I am trying to simplify code that will take two screenshots and merge them into one final screenshot...  
And the current code is:

1) Take 1st Screenshot
2) Go to 2nd Url 
3) Take 2nd Screenshot
4) Go back to 1st URL

The obvious streamlining is:

1) Take 1st Screenshot
2) Open New Window
3) Go to 2nd Url in New Window
3) Take 2nd Screenshot
4) Close New Window (thus returning to 1st browser window)

I see where we can open a new browser window via self.open_new_window, but I see no way to close the browser window that I created.  I presume I could use self.driver.close() to do so, but I am surprised that there is no wrapper to this.

And is there any method to identify what window you are in?  Yes, I could grab the title of the window I am in, and ensure that it matches when I return?  But wouldn't it be safer to have a function that returns the window ID of the window you are in currently?

self.switch_to_frame(frame, timeout=None)
self.switch_to_window(window, timeout=None)

For Switch_to_xxxx, is frame/window an integer?  I haven't investigated yet, I presume so...

**Comment by mdmintz** [comment]
Hi @bschollnick , in ``self.switch_to_window(window)``, "window" is an integer. In ``self.switch_to_frame(frame)``, "frame" is the name of the frame (or a Selector for the frame).

For switching to a window, performing an action, and closing it, here's an example:

```python
self.switch_to_window(1)
### <Perform an action>
self.driver.close()
self.switch_to_window(0)
```

There's also ``self.open_new_window()``, which will both open a new window, and switch to it.

The ``self.driver.close()`` method does not get it's own SeleniumBase method for two reasons:
* It would do the exact same thing as ``self.driver.close()``
* Since SeleniumBase automatically closes browser windows at the end of each test, let's not confuse people into thinking they have to do that themselves.

For your other question, you can use ``self.driver`` for performing other commands such as determining the window identifier. ``self.driver.window_handles`` will give you the full list of window handles. You'll have to count to determine which one you have if you've opened more than one window.
