### ISSUE TITLE
Issues with self.save_screenshot - doesn't save entire HTML page

### ISSUE THREAD

**Issue by bschollnick** [seleniumbase/SeleniumBase#715]
Running on Windows 10, with Chrome (Latest)

- Is it expected that the screenshot functionality only captures the visible portion of the HTML page that is being seen?

Is there any good workarounds?  (eg I don't see any functionality for page scaling?)

Is there any way to tell if the page needs to be scrolled, so that I can detect that and possible write a workaround (eg scroll to bottom, and screen shot that as well)?

**Comment by bschollnick** [comment]
Okay, on a hunch, I tried using --headless and that does capture the entire screen...  So that seems like a decent workaround, and seems faster too.

I'd still like to try to make this work in non-headless mode (it's easier to debug in).

**Comment by mdmintz** [comment]
Hi @bschollnick Looks like you already discovered the ``--headless`` workaround. The sizing is expected because often times page elements won't appear until scrolling down. There are other workarounds.
You can change the window size before taking a screenshot:

```python
self.set_window_size(width, height)
```

If you're using a custom tearDown step (See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py), you can add the line in right before the ``self.save_teardown_screenshot()`` line.

**Comment by mdmintz** [comment]
@bschollnick Did that answer your question?

**Comment by bschollnick** [comment]
It should be fine for now with headless..  I think that's the way I'll end up eventually running this suite of tests...

**Comment by bschollnick** [comment]
Just as an FYI for anyone else that might run into this issue.
self.maximize does not maximize under headless.  

Please note, this logic makes sense.  What is it to maximize to?  A virtual display doesn't necessarily have a logical "screen size".  But that is what is/was causing the issue with #719 

I used the self.set_window_size(width, height) to my normal screen size, and that seems to have resolved the issue.  See #719
