### ISSUE TITLE
Specify driver path

### ISSUE THREAD

**Issue by Jurij1337** [seleniumbase/SeleniumBase#730]
Hey folks,

My IT has a very strict restrictions so I cannot download a driver via "sbase install chromedriver latest" because this includes an exe file. Is there a possibility to specify another path when executing the tests? So when I download the exe in other ways I want to say: Hey SeleniumBase use the file which you can find on this location...

Thank you

**Comment by mdmintz** [comment]
Hi @Jurij1337 ,
The key is getting the driver into the ``seleniumbase/drivers/`` folder. There's more involved than just downloading a file into that directory because the file may be zipped, which would mean needing to unzip the file and selectively parse out the driver from a ReadMe file that's also likely to be in the zip file. Also the file permissions may need to be changed for the driver to work. All that is done in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/console_scripts/sb_install.py  There's also code for handling versioning, and more. For your case, you may need to build a custom script to get a specific driver that you already have. There's the Python ``requests`` module, which is used in the file above. You could also just build a simple shell script using ``curl`` or ``wget`` to get the driver that you need.

**Comment by Jurij1337** [comment]
Hi  @mdmintz ,
Thank you for your answer. I looked at the file. Are there any unit tests for that? I would like to refactor a little bit and add another parameter so that I can add an URL where to download the drivers from, because this would solve my problem. I can upload it to our own server and that will be ok for our IT. Then I would create a pullrequest

**Comment by Jurij1337** [comment]
If somebody is searching for a workaround: 
from seleniumbase.console_scripts import sb_install

os.environ['HTTPS_PROXY'] = 'your-ip:port'
sb_install.main('edgedriver') #your driver available are: chromedriver, edgedriver, geckodriver

e.g.

os.environ['HTTPS_PROXY'] = '192.168.0.20:80'
sb_install.main('chromedriver')

**Comment by mdmintz** [comment]
@Jurij1337 There are unit tests located in Azure Pipelines and GitHub Actions that test the driver install functionality. As I mentioned earlier, ``There's the Python "requests" module. You could also just build a simple shell script using "curl" or "wget" to get the driver that you need.``.

This looks like a very specific scenario that the majority of users won't encounter, therefore, it should be part of your custom framework that uses SeleniumBase, rather than become a part of SeleniumBase itself. These web drivers need to be installed from trusted sources, which are already included. And these scripts do more than just download a file into the correct directory... they also unzip specifically downloaded zip files to parse out the driver, and give executable permissions, for very specific file structures.
