### ISSUE TITLE
Pip version EnvironmentError

### ISSUE THREAD

**Issue by Jurijnator** [seleniumbase/SeleniumBase#774]
When I try to install Seleniumbase in my venv I get the following error: 
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Zugriff verweigert: (It is german and means Access denied) 'C:\\Users\\foobarUser\\AppData\\Local\\Temp\\pip-uninstall-tbb6v9t1\\pip.exe'
Consider using the `--user` option or check the permissions.

When I upgrade the pip version before it works. Is there another way to solve this problem? I can't use --user. I am using nox to automate things and the venv is created each time in my build pipeline. 
When I install seleniumbase a second time and don't recreate the environment it works, because the first pip version was uninstalled

Thank you for your help

**Comment by mdmintz** [comment]
@Jurijnator There are a few different solutions to this depending on whether you have multiple versions of Python installed on your system, whether you are using a virtual environment or not, whether you're using Windows, and whether you have admin access. See https://stackoverflow.com/a/53916143 for a common solution. (Using ``pip3 install`` instead of ``pip install`` may help). Sometimes you may need to upgrade pip first before installing ``seleniumbase`` because some older versions of pip do not correctly handle both upgrading pip and installing a new package at the same time correctly. (Something about pip 20.2.4 wasn't correct - see https://github.com/pypa/pip/issues/9023). The latest pip (20.3.3) is good. Upgrade to that pip first, and then install packages to avoid issues.

**Comment by Jurijnator** [comment]
Thank you! It was the pip version. I solved it with an update of Nox
