### ISSUE TITLE
The dashboard does not support specifying the storage path, for example --html=../report/report.html

### ISSUE THREAD

**Issue by ItTestKing** [seleniumbase/SeleniumBase#830]
When I tried to store a report in a specified path, I found that Dashboard did not support a specified path. I hope you can provide this feature。

**Comment by mdmintz** [comment]
When combining the use of pytest-html reports with the dashboard, the data from the dashboard will appear in the pytest-html report, which you can customize the location of.

🔵 Here's an example of an upgraded html report:

```bash
pytest test_suite.py --dashboard --html=report.html
```

<img src="https://seleniumbase.io/cdn/img/dash_report.jpg" alt="Dashboard Pytest HTML Report" title="Dashboard Pytest HTML Report" width="520" />

The report will appear at the desired location at the conclusion of the test, which will include all data from the dashboard (mainly the pie chart, as the rest of the data was already included with the pytest-html report).

**Comment by ItTestKing** [comment]
For example, I have a report folder. I want to put dashboard.html and report.html in this folder. When running with this parameter, --dashboard --html=../report/report.html, dashboard.html Cannot be placed in the report folder.
![image](https://user-images.githubusercontent.com/22090651/109742204-9fa6f100-7c09-11eb-840f-013537636746.png)

**Comment by mdmintz** [comment]
@ItTestKing Have you seen the report when also running with the dashboard? I'm saying that the report html file includes the dashboard, so if using both the dashboard and pytest-html report command-line options, you probably don't need the dashboard file also, because it is part of the report. Have you seen it? The super html-report looks like this:

<img src="https://seleniumbase.io/cdn/img/dash_report.jpg" alt="Dashboard Pytest HTML Report" title="Dashboard Pytest HTML Report" width="520" />

Is there something else missing from the html report when also using the dashboard option?

**Comment by ItTestKing** [comment]
Yes, when I pytest test_case --dashboard --html=../report/report.html, the report with dashboard cannot be generated. The generated file is shown in the figure: ：
![image](https://user-images.githubusercontent.com/22090651/109744667-a6cffe00-7c0d-11eb-8c96-df62f38a8c2e.png)
 
![image](https://user-images.githubusercontent.com/22090651/109744590-84d67b80-7c0d-11eb-8051-4d37a065fad2.png)

**Comment by mdmintz** [comment]
@ItTestKing OK, that's a bug. I'll fix the html-report so that it includes the dashboard pie chart when changing the folder location. (This assumes that the ``--dashboard`` option is used together with the ``--html="REPORT_PATH"``)

**Comment by mdmintz** [comment]
@ItTestKing Upgrade to https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.56.4
The pytest html-reports should now include the pie chart even if changing the folder location. (You'll still need to include the arg: ``--dashboard`` so that the pie chart from the completed dashboard can be copied to the top of the pytest html report.)

**Comment by ItTestKing** [comment]
I just tried it, and the report with dashboard can be generated normally. Thank you very much for your help。
