### ISSUE TITLE
Issue using "--proxy=user:pw@ip:port" with "--user-data-dir=DIR"

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#929]
I used proxy --proxy=u:p@ip:port
after the connection failed I ran without proxy, but still can't connect to the network. Could the error be caused by plugins?

**Comment by mdmintz** [comment]
@thanhvodad  I'm not sure of your specific situation, but if you pass the correct args, the proxy should work, such as in the following examples:
```bash
# Run tests through a proxy server
pytest proxy_test.py --proxy=IP_ADDRESS:PORT

# Run tests through a proxy server with authentication
pytest proxy_test.py --proxy=USERNAME:PASSWORD@IP_ADDRESS:PORT
```
Keep in mind that if using an authenticated proxy server, you'll need to use Chrome because the authentication part is processed via Chrome extension.

**Comment by thanhvodad** [comment]
I tried pytest it works, but with --user-data-dir it no longer works.
before that --user-data-dir ran the first time I didn't use --proxy
2nd command has --user-data-dir then it catches auth even though proxy doesn't have auth

**Comment by thanhvodad** [comment]
Now I run the command below it still tells me I'm using a proxy, how can I remove it
pytest hit.py --browser=chrome --time-limit=7200 --user-data-dir="./profiles/bentleeaddison1755@gmail.com"

**Comment by mdmintz** [comment]
@thanhvodad The ``--proxy`` option and the ``--user-data-dir`` option conflict with each other because while ``--proxy`` configures proxy via webdriver and by adding a chrome extension with auth credentials, when you set a user-data-dir, it tells the browser to get all of its settings from that directory instead, rather than the usual configuration, (of if the directory doesn't exist yet, it will create it for the first time and then set configuration). You may have to choose one of the two (``--proxy`` or ``--user-data-dir``), or if you still need proxy while setting a custom user data dir, you'll need to configure the dir to have any settings that you want used.

**Comment by mdmintz** [comment]
@thanhvodad  Expanding on my previous response, if you use both ``--proxy`` and ``--user-data-dir``, then the user-data-dir will save the proxy settings if it's your first time creating the data directory, and therefore those proxy settings may still be present even if you don't use ``--proxy`` anymore (but you still reuse the data directory where those proxy settings were saved).

**Comment by thanhvodad** [comment]
I removed and run --proxy + userdata everything is ok,
But run cmd 1 has userdata, no proxy
cmd 2 has userdata, proxy won't work
---
now i solved it, Thank you.
