### ISSUE TITLE
How is it possible to run multiple threads, with different parameters?

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#935]
I want to run multiple threads with different configuration how to use it

**Comment by mdmintz** [comment]
Hi @thanhvodad, to run multiple threads with different configuration, you'll have to combine a few different things.

First, to run tests via multithreading, you can use a ``pytest`` command-line option such as ``-n=4``, example:
``pytest -n=4`` (That will run your tests using 4 threads.)

Inside your tests, you can change the default configuration set during the ``pytest`` run command by calling the following method with the configuration that you want for your additional browser/driver:
```python
self.get_new_driver(
    browser=None, headless=None, locale_code=None,
    servername=None, port=None, proxy=None, agent=None,
    switch_to=True, cap_file=None, cap_string=None,
    disable_csp=None, enable_ws=None, enable_sync=None,
    use_auto_ext=None, no_sandbox=None, disable_gpu=None,
    incognito=None, guest_mode=None,
    devtools=None, remote_debug=None,
    swiftshader=None, block_images=None, user_data_dir=None,
    extension_zip=None, extension_dir=None, is_mobile=None,
    d_width=None, d_height=None, d_p_r=None)
```
This method opens up a new browser in your test with the configuration specified. The options correspond to SeleniumBase values that you can set on the command-line with ``pytest``. If ``None`` is specified for an option, it uses the default value, or the one set on the command-line.

A simple case of using that method in a test with the default configuration is:
``driver2 = self.get_new_driver()``
(At this point, all SeleniumBase commands will automatically use the new driver by default.)
Then, to switch back to the default driver, use:
``self.switch_to_default_driver()``
And to switch back to driver2 again, use:
``self.switch_to_driver(driver2)``
All SeleniumBase commands will run in the currently active browser/driver, but you can switch between them at any time.

You can combine that with parameterization so that you can run a different version of each test with different configuration. Here's an example of a parameterized test:
```python
from seleniumbase import BaseCase
from parameterized import parameterized

class GoogleTests(BaseCase):
    @parameterized.expand(
        [
            ["PyPI", "pypi.org", 'img[alt="PyPI"]'],
            ["Wikipedia", "wikipedia.org", "img.central-featured-logo"],
            ["SeleniumBase", "seleniumbase/SeleniumBase", 'img[title*="Sel"]'],
        ]
    )
    def test_parameterized_google_search(self, search_key, expected_text, img):
        self.open("https://google.com/ncr")
        self.type('input[title="Search"]', search_key + "\n")
        self.assert_element("#result-stats")
        self.assert_text(expected_text, "#search")
        self.click('a:contains("%s")' % expected_text)
        self.assert_element(img)
```

When combining pytest multithreading, with the ``self.get_new_driver()`` method, and with the ``parameterized`` library, that should get you to the solution you're looking for.

**Comment by thanhvodad** [comment]
I'm doing 10 different profiles, currently I'm using threading, for each threading I'm using os.system('pytest seleniumbase.py --....)
is there any optimal method for me currently, I am learning selenium python

**Comment by mdmintz** [comment]
@thanhvodad, if you're calling tests like that through ``os.system('pytest ...`` individually, then test results won't be grouped together into a single dashboard or report with ``--dashboard`` or ``--html=report.html``. But if grouping test results with the dashboard and the report are not important to you, you can use ``os.system`` for each run, and then set command-line options uniquely for each individual pytest call. For that, there's no set way for how to optimally handle that, but if grouping everything together becomes important, see the description from my first comment on this issue.

**Comment by thanhvodad** [comment]
The problem is that I run multiple user data profiles, I only need to run da thread, 1 thread 1 proxy & 1 profiles, just to optimize the performance,
another problem, how can main.py run the selenium.py file instead of the pytest selenium.py cmd?

**Comment by mdmintz** [comment]
@thanhvodad See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_parameter_script.py for an example of running a test with pure Python, rather than from ``pytest`` directly.
