### ISSUE TITLE
How to do action over and over again ?

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#940]
I run test_settep1(selft) how when the action is done it will run again test_settep1 ?, please guide me without quitting() the browser reopen

**Comment by mdmintz** [comment]
@thanhvodad Run tests with:
``pytest --reuse-session``
and that will keep the browser open for all tests to reuse until the very last test.

**Comment by thanhvodad** [comment]
no i want it to be the same, like while true: pytest... the parameters are the same

**Comment by mdmintz** [comment]
@thanhvodad Then use a method that doesn't start with ``test_``, and call it multiple times from your test method with a loop. If you need to loop a ``test_`` method, use fake parameterization where you call the same test multiple times with ``parameterized`` or ``pytest.mark.parametrize``. At that point, you're following the rules of ``pytest``, rather than ``SeleniumBase``, because SeleniumBase tests are just ``pytest`` tests that call additional libraries by importing ``BaseCase``. If there's a specific way of doing that kind of loop with ``pytest``, you'll have to check with them. If it helps, there's ``--reruns=4``, for example, where you can rerun a test a certain number of times until it passes, but that will only rerun tests that have been failing. You could also loop ``os.system("pytest...")`` from within a test to call ``pytest`` on another test for as many times as needed.
