### ISSUE TITLE
How can I customize firefoxbinary ?

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#944]
firefox_binary=FirefoxBinary('data/Firefox.87/Firefox.exe'),
I want to use my custom firefox how do I do that?

**Comment by mdmintz** [comment]
@thanhvodad It'll use whichever Firefox that is on the system path. If you need multiple Firefox versions, try putting them in Docker contains. https://github.com/SeleniumHQ/docker-selenium might work for that. The Selenium Grid may be useful here in choosing which one to use.

**Comment by thanhvodad** [comment]
I want to select my instance, by seleniumbase, is there any args select exe file for seleniumbase ?

**Comment by mdmintz** [comment]
@thanhvodad There isn't because the current way of selecting the binary is being deprecated in Selenium 4. See https://stackoverflow.com/questions/58296262/python-selenium-4-firefox-firefoxbinary-deprecated
Once Selenium 4 comes out, that could change, but for now, there will be no changes until Selenium 4 finalizes its binary selection process.

**Comment by thanhvodad** [comment]
I can't work with seleniumbase ?

**Comment by mdmintz** [comment]
You can clone it and make changes to your local copy as needed. But I can't add that in now as it is because it will break backwards compatibility when SeleniumBase upgrades to Selenium 4 in the next few months when it comes out (assuming it's on schedule).

**Comment by mdmintz** [comment]
For now, just make sure that the Firefox you want to use is on your System PATH. If you need to use more than one, just swap them out as needed.
