### ISSUE TITLE
How can I customize seleniumbase

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#946]
I want to finish running SeleniumBase with my app's directory because I want to run some things,
main.py
./seleniumbase
How can I call it?

**Comment by mdmintz** [comment]
Hi @thanhvodad, if you're looking for a way to call SeleniumBase scripts without using ``pytest``, see the example here with calling a script with ``python`` alone: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_parameter_script.py

**Comment by thanhvodad** [comment]
No, I want to re-customize seleniumbase to some new places in the core, so I want to call seleniumbase from the directory along with my main.py file, but not in the directory ...\python39\lib\site- packages

**Comment by mdmintz** [comment]
@thanhvodad, I'm not sure I fully understand your question. This sounds like a ``pip``-specific question related to where Python packages are installed when installing with ``pip``. (https://github.com/pypa/pip)
You can change where it's installed by calling:
``pip install -e .`` from the top-level SeleniumBase folder after you've cloned it. If you install it like that, it won't put SeleniumBase in the Python site-packages folder. Instead, it will use the actual folders where you cloned it for all things, such as for driver downloads.
For example, if I use ``pip install -e .`` as above, then after I run ``pip list`` it will display the new location, rather than the default location. Example:
```bash
pip list

Package               Version   Location
--------------------- --------- ----------------------------------
...
selenium              3.141.0
seleniumbase          1.63.16   /Users/michael/github/SeleniumBase
setuptools            57.4.0
setuptools-scm        6.0.1
...
```

**Comment by thanhvodad** [comment]
In case I'm running and the window is open, I accidentally press X to close the browser, what code will catch the browser just closed, and return an error or something?

**Comment by mdmintz** [comment]
@thanhvodad ``self.driver.current_url`` will fail if the browser isn't open. Use try/except to process that situation correctly.
