### ISSUE TITLE
Cannot disable notifications in chrome

### ISSUE THREAD

**Issue by mdoron** [seleniumbase/SeleniumBase#947]
Hi
I want to disable notification (using `{"profile.default_content_setting_values.notifications": 2}` but in the code it's hardcoded as `{"profile.default_content_setting_values.notifications": 0}`. 
Do you have a solution for that?

BTW, in general I don't see why the access to change the chrome options is not available widely in the api.
Is there a reason for that?

**Comment by mdmintz** [comment]
@mdoron See the latest release from 5 minutes ago: https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.63.17, which fixes the issue with https://github.com/seleniumbase/SeleniumBase/pull/948
The original line was meant to disable Chromium notifications, but ``{"profile.default_content_setting_values.notifications": 2}`` is the correct way.
Since Chromium notifications can interfere with tests, they should always be disabled.

**Comment by mdmintz** [comment]
Since the fix was part of v1.63.17, I'll close this ticket. Let me know if you encounter any more issues.
