### ISSUE TITLE
I often get a browser duplication error when running

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#953]
I run Pytest, sometimes due to network short, or high CPU slow load, it will repeat pytest 1 more time, make old browser not closed and it opens new browser, Is there any way to fix it?

**Comment by mdmintz** [comment]
This sounds like a pytest-specific issue and not a ``SeleniumBase`` one. If ``pytest`` decides to rerun a test again, that's ``pytest`` at work and not ``SeleniumBase``. ``SeleniumBase`` does not add any plugins for rerunning tests, but there are outside plugins such as ``pytest-rerunfailures`` that do rerun failing tests.

I'd need to see a stack trace to know why you're experiencing an orphaned browser. Browsers should get closed automatically in the ``tearDown()`` step unless you're running tests with ``--reuse-session``, at which point they should close at the very end of your entire test suite. Seeing your run command will also be useful.

There are also possible issues with Chromedriver, Geckodriver, and raw Selenium that may leave a browser unresponsive and orphaned due to "network short or high CPU slow load", as you mentioned. See tickets such as https://github.com/SeleniumHQ/selenium/issues/6826 and other related tickets on the https://github.com/SeleniumHQ/selenium GitHub page. If there's a bug specific to a certain version of Chromedriver, (for example), that's also out of my control, but you may be able to update your drivers own your own to fix that.

**Comment by thanhvodad** [comment]
I use
While True:
         try:
             subprocess.run("pytest ...")
         except subprocess.CalledProcessError:
             print('wrongcommand does not exist')
             
maybe in the subprocess it crashes and doesn't close the browser, in pytest I also use super().setUp(), is this what causes the browser to not close but still open a new window?

**Comment by mdmintz** [comment]
If you're overriding ``setUp()`` and ``tearDown()``, make sure you're doing it correctly, such as in this example: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py
I'm not sure how you're doing it, so you might be doing it incorrectly. Also, running pytest in a subprocess might have something to do with it, as that could lead to unintended behaviors.

**Comment by thanhvodad** [comment]
I'm using super().setUp() now, let me check
class App(BaseCase):
    def setUp(self):
        super().setUp()

**Comment by mdmintz** [comment]
Aside from indentation, that looks correct. But your issue was with tearDown, not setUp.

**Comment by thanhvodad** [comment]
I run multiple times when high CPU freezes when I open a new browser, or after opening it loads the page, it throws an error, but it doesn't close the browser, And my While True: command continues to execute pytest , making it create a new browser with the same profile I set :(

**Comment by mdmintz** [comment]
What issues do you have when running ``pytest`` standalone, rather than through ``subprocess.run``? Using ``subprocess.run`` might be leading to all these issues you're seeing.

**Comment by thanhvodad** [comment]
I programmed it like an auto, repeating an action with python forces me to run it non-stop :(

**Comment by mdmintz** [comment]
Maybe try ``subprocess.check_call`` instead, with ``shell=True``? I've also used cron jobs and Jenkins jobs for repeated automation actions. In general, having a repeating subprocess like that is likely to lead to the issues you've been seeing if it's not carefully written. Also, be careful about spinning up too many parallel processes, which could lead to a quick spike in memory usage.

**Comment by thanhvodad** [comment]
I'll check it out it's a headache :(
