### ISSUE TITLE
Exception: module 'seleniumbase.fixtures.constants' has no attribute 'MultiBrowser

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#989]
except Exception as e:
                if headless:
>                   raise Exception(e)
E                   Exception: module 'seleniumbase.fixtures.constants' has no attribute 'MultiBrowser'

**Comment by mdmintz** [comment]
@thanhvodad It's right here:
https://github.com/seleniumbase/SeleniumBase/blob/7ad83c4bfa4b2f53dd430a380545223b1a9e9133/seleniumbase/fixtures/constants.py#L55
So that probably means you've made custom changes to a GitHub clone of SeleniumBase where you changed ``constants.py``; or you updated ``browser_launcher.py`` in your custom SeleniumBase clone without updating ``constants.py`` along with it. Either ``git pull`` all the updates, or reinstall ``seleniumbase`` so that all files are in sync.
