### ISSUE TITLE
How to exit? Message: chrome not reachable   (Session info: chrome=93.0.4577.82)

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#991]
During the test, I accidentally shut down the browser, while the command is still running, how when it generates an error, it can tearDown exit by itself

**Comment by mdmintz** [comment]
If you manually shut down the browser during the test, you'll run into errors because SeleniumBase can no longer reach the browser. During ``tearDown()`` SeleniumBase will save screenshots on failures (which it can't if you manually closed the browser window). During ``tearDown()``, SeleniumBase will also close the browser window on its own.

**Comment by thanhvodad** [comment]
This is the problem I have, when it overflows memory, the browser closes by itself, but the webdriver still works and gives the error on

**Comment by mdmintz** [comment]
That seems like more of a system issue than a SeleniumBase one. Try https://stackoverflow.com/a/53887935 , or some of the other solutions. If the browser closes before the test, there are going to be unavoidable errors. But there are solutions like the one above for handling errors on specific environments. Without specific details of your environment, or a stack trace, I don't have enough information to debug outside of pointing to possible Stack Overflow solutions.
